// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexusForever.Database.Chat;

#nullable disable

namespace NexusForever.Database.Sqlite.Migrations.Chat
{
    [DbContext(typeof(ChatContext))]
    [Migration("20260607222228_ChatSqliteInitial")]
    partial class ChatSqliteInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.16");

            modelBuilder.Entity("NexusForever.Database.Chat.Model.CharacterChatChannelModel", b =>
                {
                    b.Property<ulong>("CharacterId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("characterId");

                    b.Property<ushort>("RealmId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("realmId");

                    b.Property<ulong>("ChatId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("chatId");

                    b.HasKey("CharacterId", "RealmId", "ChatId");

                    b.HasIndex("ChatId", "CharacterId", "RealmId")
                        .IsUnique();

                    b.ToTable("character_chat_channel", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.Chat.Model.CharacterModel", b =>
                {
                    b.Property<ulong>("CharacterId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("characterId");

                    b.Property<ushort>("RealmId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("realmId");

                    b.Property<uint>("Faction")
                        .HasColumnType("INTEGER")
                        .HasColumnName("faction");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("INTEGER")
                        .HasColumnName("isOnline");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("RealmName")
                        .HasColumnType("TEXT")
                        .HasColumnName("realmName");

                    b.HasKey("CharacterId", "RealmId");

                    b.ToTable("character", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.Chat.Model.ChatChannelMemberModel", b =>
                {
                    b.Property<ulong>("ChatId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("chatId");

                    b.Property<ulong>("CharacterId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("characterId");

                    b.Property<ushort>("RealmId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("realmId");

                    b.Property<int>("Flags")
                        .HasColumnType("INTEGER")
                        .HasColumnName("flags");

                    b.HasKey("ChatId", "CharacterId", "RealmId");

                    b.HasIndex("CharacterId", "RealmId");

                    b.ToTable("chat_channel_member", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.Chat.Model.ChatChannelModel", b =>
                {
                    b.Property<ulong>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("chatId");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT")
                        .HasColumnName("password");

                    b.Property<byte?>("ReferenceType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("referenceType");

                    b.Property<ulong?>("ReferenceValue")
                        .HasColumnType("INTEGER")
                        .HasColumnName("referenceValue");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER")
                        .HasColumnName("type");

                    b.HasKey("ChatId");

                    b.HasIndex("Type", "Name")
                        .IsUnique();

                    b.HasIndex("Type", "ReferenceType", "ReferenceValue")
                        .IsUnique();

                    b.ToTable("chat_channel", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.Chat.Model.ChatChannelOwnerModel", b =>
                {
                    b.Property<ulong>("ChatId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("chatId");

                    b.Property<ulong>("CharacterId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("characterId");

                    b.Property<ushort>("RealmId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("realmId");

                    b.HasKey("ChatId");

                    b.HasIndex("ChatId", "CharacterId", "RealmId")
                        .IsUnique();

                    b.ToTable("chat_channel_owner", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.Chat.Model.InternalMessageModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("messageId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("createdAt");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("data");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("processedAt");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("ProcessedAt");

                    b.ToTable("internal_message", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.Chat.Model.CharacterChatChannelModel", b =>
                {
                    b.HasOne("NexusForever.Database.Chat.Model.CharacterModel", "Character")
                        .WithMany("Channels")
                        .HasForeignKey("CharacterId", "RealmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusForever.Database.Chat.Model.ChatChannelMemberModel", "Member")
                        .WithOne()
                        .HasForeignKey("NexusForever.Database.Chat.Model.CharacterChatChannelModel", "ChatId", "CharacterId", "RealmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("NexusForever.Database.Chat.Model.ChatChannelMemberModel", b =>
                {
                    b.HasOne("NexusForever.Database.Chat.Model.ChatChannelModel", "ChatChannel")
                        .WithMany("Members")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusForever.Database.Chat.Model.CharacterModel", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId", "RealmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("ChatChannel");
                });

            modelBuilder.Entity("NexusForever.Database.Chat.Model.ChatChannelOwnerModel", b =>
                {
                    b.HasOne("NexusForever.Database.Chat.Model.ChatChannelModel", "ChatChannel")
                        .WithOne("Owner")
                        .HasForeignKey("NexusForever.Database.Chat.Model.ChatChannelOwnerModel", "ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusForever.Database.Chat.Model.ChatChannelMemberModel", "Member")
                        .WithOne()
                        .HasForeignKey("NexusForever.Database.Chat.Model.ChatChannelOwnerModel", "ChatId", "CharacterId", "RealmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatChannel");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("NexusForever.Database.Chat.Model.CharacterModel", b =>
                {
                    b.Navigation("Channels");
                });

            modelBuilder.Entity("NexusForever.Database.Chat.Model.ChatChannelModel", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Owner");
                });
#pragma warning restore 612, 618
        }
    }
}
