using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace NexusForever.PacketSourceGenerator;

[Generator(LanguageNames.CSharp)]
public sealed class PacketSerializationGenerator : IIncrementalGenerator
{
    private const string PacketSerializableAttributeName = "NexusForever.Network.Message.PacketSerializableAttribute";
    private const string PacketFieldAttributeName = "NexusForever.Network.Message.PacketFieldAttribute";

    private const string AttributeSource = """
// <auto-generated />
namespace NexusForever.Network.Message
{
    internal enum PacketSerializationMode
    {
        Read,
        Write,
        ReadWrite
    }

    internal enum PacketStringEncoding
    {
        Ascii,
        Wide,
        FixedWide
    }

    [global::System.AttributeUsage(global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct)]
    internal sealed class PacketSerializableAttribute : global::System.Attribute
    {
        public PacketSerializableAttribute(PacketSerializationMode mode)
        {
            Mode = mode;
        }

        public PacketSerializationMode Mode { get; }
    }

    [global::System.AttributeUsage(global::System.AttributeTargets.Field | global::System.AttributeTargets.Property)]
    internal sealed class PacketFieldAttribute : global::System.Attribute
    {
        public PacketFieldAttribute()
        {
        }

        public PacketFieldAttribute(uint bits)
        {
            Bits = bits;
        }

        public uint Bits { get; }
        public PacketStringEncoding StringEncoding { get; set; }
    }
}
""";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static output =>
            output.AddSource("PacketSerializationAttributes.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

        IncrementalValuesProvider<PacketType> packetTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is TypeDeclarationSyntax typeDeclaration && typeDeclaration.AttributeLists.Count != 0,
                static (ctx, _) => CreatePacketType(ctx))
            .Where(static packetType => packetType != null)
            .Select(static (packetType, _) => packetType!);

        context.RegisterSourceOutput(packetTypes.Collect(), static (ctx, packetTypes) =>
        {
            foreach (PacketType packetType in packetTypes)
                ctx.AddSource(packetType.HintName, SourceText.From(packetType.Source, Encoding.UTF8));
        });
    }

    private static PacketType? CreatePacketType(GeneratorSyntaxContext context)
    {
        var typeDeclaration = (TypeDeclarationSyntax)context.Node;
        if (context.SemanticModel.GetDeclaredSymbol(typeDeclaration) is not INamedTypeSymbol typeSymbol)
            return null;

        AttributeData? packetAttribute = typeSymbol.GetAttributes()
            .FirstOrDefault(a => SymbolEquals(a.AttributeClass, PacketSerializableAttributeName));
        if (packetAttribute == null)
            return null;

        if (!typeDeclaration.Modifiers.Any(SyntaxKind.PartialKeyword))
            return null;

        PacketSerializationMode mode = GetMode(packetAttribute);
        ImmutableArray<PacketField> fields = CreateFields(context.SemanticModel, typeDeclaration);

        string source = GenerateType(typeSymbol, mode, fields);
        string hintName = $"{typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat).Replace("global::", string.Empty).Replace('.', '_')}.PacketSerialization.g.cs";
        return new PacketType(hintName, source);
    }

    private static ImmutableArray<PacketField> CreateFields(SemanticModel semanticModel, TypeDeclarationSyntax typeDeclaration)
    {
        var fields = ImmutableArray.CreateBuilder<PacketField>();
        foreach (MemberDeclarationSyntax member in typeDeclaration.Members)
        {
            ISymbol? symbol = member switch
            {
                PropertyDeclarationSyntax property => semanticModel.GetDeclaredSymbol(property),
                FieldDeclarationSyntax field => field.Declaration.Variables.Count == 1
                    ? semanticModel.GetDeclaredSymbol(field.Declaration.Variables[0])
                    : null,
                _ => null
            };

            if (symbol == null)
                continue;

            AttributeData? fieldAttribute = symbol.GetAttributes()
                .FirstOrDefault(a => SymbolEquals(a.AttributeClass, PacketFieldAttributeName));
            if (fieldAttribute == null)
                continue;

            ITypeSymbol fieldType = symbol switch
            {
                IPropertySymbol property => property.Type,
                IFieldSymbol field => field.Type,
                _ => null!
            };

            fields.Add(new PacketField(
                symbol.Name,
                fieldType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                fieldType.SpecialType,
                fieldType.TypeKind == TypeKind.Enum,
                GetUInt(fieldAttribute, "Bits", 0u),
                GetStringEncoding(fieldAttribute)));
        }

        return fields.ToImmutable();
    }

    private static string GenerateType(INamedTypeSymbol typeSymbol, PacketSerializationMode mode, ImmutableArray<PacketField> fields)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable disable");
        builder.Append("namespace ").AppendLine(typeSymbol.ContainingNamespace.ToDisplayString());
        builder.AppendLine("{");

        AppendContainingTypes(builder, typeSymbol);

        string typeKeyword = typeSymbol.TypeKind == TypeKind.Struct ? "struct" : "class";
        builder.Append("    ");
        for (INamedTypeSymbol? containingType = typeSymbol.ContainingType; containingType != null; containingType = containingType.ContainingType)
            builder.Append("    ");
        builder.Append("partial ").Append(typeKeyword).Append(' ').AppendLine(typeSymbol.Name);
        builder.Append("    ");
        for (INamedTypeSymbol? containingType = typeSymbol.ContainingType; containingType != null; containingType = containingType.ContainingType)
            builder.Append("    ");
        builder.AppendLine("{");

        if (mode is PacketSerializationMode.Write or PacketSerializationMode.ReadWrite)
            AppendWriteMethod(builder, typeSymbol, fields);

        if (mode is PacketSerializationMode.Read or PacketSerializationMode.ReadWrite)
            AppendReadMethod(builder, typeSymbol, fields);

        builder.Append("    ");
        for (INamedTypeSymbol? containingType = typeSymbol.ContainingType; containingType != null; containingType = containingType.ContainingType)
            builder.Append("    ");
        builder.AppendLine("}");

        CloseContainingTypes(builder, typeSymbol);

        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void AppendWriteMethod(StringBuilder builder, INamedTypeSymbol typeSymbol, ImmutableArray<PacketField> fields)
    {
        string indent = GetMemberIndent(typeSymbol);
        builder.Append(indent).AppendLine("public void Write(global::NexusForever.Network.GamePacketWriter writer)");
        builder.Append(indent).AppendLine("{");
        foreach (PacketField field in fields)
        {
            builder.Append(indent).Append("    ");
            if (field.SpecialType == SpecialType.System_String)
            {
                builder.Append(GetStringWriteMethod(field.StringEncoding)).Append('(').Append(field.Name).AppendLine(");");
            }
            else
            {
                builder.Append("writer.Write(").Append(field.Name);
                if (field.Bits != 0u)
                    builder.Append(", ").Append(field.Bits).Append('u');
                builder.AppendLine(");");
            }
        }

        builder.Append(indent).AppendLine("}");
    }

    private static void AppendReadMethod(StringBuilder builder, INamedTypeSymbol typeSymbol, ImmutableArray<PacketField> fields)
    {
        string indent = GetMemberIndent(typeSymbol);
        builder.Append(indent).AppendLine("public void Read(global::NexusForever.Network.GamePacketReader reader)");
        builder.Append(indent).AppendLine("{");
        foreach (PacketField field in fields)
        {
            builder.Append(indent).Append("    ").Append(field.Name).Append(" = ");
            if (field.IsEnum)
            {
                builder.Append("reader.ReadEnum<").Append(field.TypeName).Append(">(");
                if (field.Bits != 0u)
                    builder.Append(field.Bits).Append('u');
                builder.AppendLine(");");
                continue;
            }

            builder.Append(GetReadExpression(field)).AppendLine(";");
        }

        builder.Append(indent).AppendLine("}");
    }

    private static string GetReadExpression(PacketField field)
    {
        string bits = field.Bits == 0u ? string.Empty : $"{field.Bits}u";
        return field.SpecialType switch
        {
            SpecialType.System_Boolean => "reader.ReadBit()",
            SpecialType.System_Byte => $"reader.ReadByte({bits})",
            SpecialType.System_UInt16 => $"reader.ReadUShort({bits})",
            SpecialType.System_Int16 => $"reader.ReadShort({bits})",
            SpecialType.System_UInt32 => $"reader.ReadUInt({bits})",
            SpecialType.System_Int32 => $"reader.ReadInt({bits})",
            SpecialType.System_Single => $"reader.ReadSingle({bits})",
            SpecialType.System_Double => $"reader.ReadDouble({bits})",
            SpecialType.System_UInt64 => $"reader.ReadULong({bits})",
            SpecialType.System_Int64 => $"reader.ReadLong({bits})",
            SpecialType.System_String => GetStringReadMethod(field.StringEncoding),
            _ => throw new NotSupportedException($"Unsupported packet field type {field.TypeName}.")
        };
    }

    private static string GetStringReadMethod(PacketStringEncoding encoding)
    {
        return encoding switch
        {
            PacketStringEncoding.Ascii => "reader.ReadString()",
            PacketStringEncoding.Wide => "reader.ReadWideString()",
            PacketStringEncoding.FixedWide => "reader.ReadWideStringFixed()",
            _ => throw new NotSupportedException($"Unsupported string encoding {encoding}.")
        };
    }

    private static string GetStringWriteMethod(PacketStringEncoding encoding)
    {
        return encoding switch
        {
            PacketStringEncoding.Ascii => "writer.WriteString",
            PacketStringEncoding.Wide => "writer.WriteStringWide",
            PacketStringEncoding.FixedWide => "writer.WriteStringFixed",
            _ => throw new NotSupportedException($"Unsupported string encoding {encoding}.")
        };
    }

    private static void AppendContainingTypes(StringBuilder builder, INamedTypeSymbol typeSymbol)
    {
        var containingTypes = new List<INamedTypeSymbol>();
        for (INamedTypeSymbol? containingType = typeSymbol.ContainingType; containingType != null; containingType = containingType.ContainingType)
            containingTypes.Add(containingType);

        containingTypes.Reverse();

        for (int i = 0; i < containingTypes.Count; i++)
        {
            INamedTypeSymbol containingType = containingTypes[i];
            string indent = new string(' ', (i + 1) * 4);
            string typeKeyword = containingType.TypeKind == TypeKind.Struct ? "struct" : "class";
            builder.Append(indent).Append("partial ").Append(typeKeyword).Append(' ').AppendLine(containingType.Name);
            builder.Append(indent).AppendLine("{");
        }
    }

    private static void CloseContainingTypes(StringBuilder builder, INamedTypeSymbol typeSymbol)
    {
        int depth = 0;
        for (INamedTypeSymbol? containingType = typeSymbol.ContainingType; containingType != null; containingType = containingType.ContainingType)
            depth++;

        for (int i = depth; i > 0; i--)
            builder.Append(new string(' ', i * 4)).AppendLine("}");
    }

    private static string GetMemberIndent(INamedTypeSymbol typeSymbol)
    {
        int depth = 2;
        for (INamedTypeSymbol? containingType = typeSymbol.ContainingType; containingType != null; containingType = containingType.ContainingType)
            depth++;

        return new string(' ', depth * 4);
    }

    private static PacketSerializationMode GetMode(AttributeData attribute)
    {
        if (attribute.ConstructorArguments.Length == 0)
            return PacketSerializationMode.Write;

        return (PacketSerializationMode)(int)attribute.ConstructorArguments[0].Value!;
    }

    private static uint GetUInt(AttributeData attribute, string propertyName, uint defaultValue)
    {
        if (attribute.ConstructorArguments.Length != 0
            && attribute.ConstructorArguments[0].Value is uint ctorValue)
            return ctorValue;

        foreach (KeyValuePair<string, TypedConstant> argument in attribute.NamedArguments)
            if (argument.Key == propertyName && argument.Value.Value is uint namedValue)
                return namedValue;

        return defaultValue;
    }

    private static PacketStringEncoding GetStringEncoding(AttributeData attribute)
    {
        foreach (KeyValuePair<string, TypedConstant> argument in attribute.NamedArguments)
            if (argument.Key == "StringEncoding" && argument.Value.Value is int value)
                return (PacketStringEncoding)value;

        return PacketStringEncoding.Ascii;
    }

    private static bool SymbolEquals(ISymbol? symbol, string fullyQualifiedMetadataName)
    {
        return symbol?.ToDisplayString() == fullyQualifiedMetadataName;
    }

    private sealed class PacketType
    {
        public PacketType(string hintName, string source)
        {
            HintName = hintName;
            Source = source;
        }

        public string HintName { get; }
        public string Source { get; }
    }

    private sealed class PacketField
    {
        public PacketField(
            string name,
            string typeName,
            SpecialType specialType,
            bool isEnum,
            uint bits,
            PacketStringEncoding stringEncoding)
        {
            Name = name;
            TypeName = typeName;
            SpecialType = specialType;
            IsEnum = isEnum;
            Bits = bits;
            StringEncoding = stringEncoding;
        }

        public string Name { get; }
        public string TypeName { get; }
        public SpecialType SpecialType { get; }
        public bool IsEnum { get; }
        public uint Bits { get; }
        public PacketStringEncoding StringEncoding { get; }
    }

    private enum PacketSerializationMode
    {
        Read,
        Write,
        ReadWrite
    }

    private enum PacketStringEncoding
    {
        Ascii,
        Wide,
        FixedWide
    }
}
