namespace NexusForever.Network.Message
{
    public enum GameMessageOpcode
    {
        State                           = 0x0000,
        State2                          = 0x0001,
        ServerHello                     = 0x0003,
        Server0x0015                    = 0x0015, // native 140081f00 reads one 5-bit field plus one uint32; shared with matching opcode 0x0628 and semantics unresolved
        ServerMaxCharacterLevelAchieved = 0x0036,
        Client0x003D                    = 0x003D, // ClientWorldOpcodeRegister_MovementSpline @ 1400a8190 registers a 0x18-byte payload with writer Client0x003D_WritePayload @ 1400aba70; field order is uint14 + uint32 + wide string + uint64 and the same layout is reused inside Client0x0760 realm rows
        ServerPlayerEnteredWorld        = 0x0061,
        ServerPetSpawned                = 0x0068,
        ServerClientEntityUpdateInterval = 0x0070,
        ServerAuthEncrypted             = 0x0076,
        ServerGameCameraRotation        = 0x0091,
        ServerLogoutUpdate              = 0x0092,
        ClientCommodityOrderCancel      = 0x0093,
        ClientAuctionCancel             = 0x0094,
        ClientActivateUnitCastPosition  = 0x0096, // activate-unit family request with context token, selector nibbles, target id, and position
        ClientActivateUnitCast          = 0x0097, // activate-unit cast request with { ContextToken, ActivateUnitId }
        ClientActivateUnitCastTarget    = 0x0098, // activate-unit family request with { ContextToken, TargetField }
        ClientCastPathExplorerSearching = 0x0099,
        ClientCastSpell                 = 0x009A,
        ClientCastSpellPosition         = 0x009B,
        ClientCastSpellSelected         = 0x009D, // spell-cast variant with context token, selected entry id, target id, and position
        ServerChallengeShared           = 0x00A9,
        ServerChallengeShareTimeout     = 0x00AA,
        ServerChangeWorld               = 0x00AD,
        ServerAchievementInit           = 0x00AE,
        ServerAchievementUpdate         = 0x00AF,
        ServerLasOpeningUInt18          = 0x00B0, // 18-bit Spell4Id; reader ServerUInt18_ReadPayload @ 140080d30
        ClientRequestActionSetChanges   = 0x00B1,
        ServerActionSetClearCache       = 0x00B2, // server sends this after a ClientRequestActionSetChanges (0xB1)
        ClientActivateUnit              = 0x00B3, // direct activate-unit request with { ActivateUnitId }
        ClientLootAssignMaster          = 0x00B5,
        ClientItemContextAction         = 0x00B6, // inventory item-click/context action with item guid and selector bit
        ServerItemContextActionAck      = 0x00B7, // 1-byte ack after ClientItemContextAction
        ClientFriendshipBlock           = 0x00B8,
        ServerBuybackItemUpdated        = 0x00BA,
        ClientBuybackItemFromVendor     = 0x00BB,
        ServerBuybackItems              = 0x00BC,
        ServerBuybackItemRemoved        = 0x00BD,
        ClientVendorPurchase            = 0x00BE,
        ClientLogoutRequest             = 0x00BF,
        ClientLogoutConfirm             = 0x00C0,
        ServerDuelCancelWarning         = 0x00C1,
        ClientSpellCastWithServiceToken = 0x00C2,
        ClientCCStateStunUpdate         = 0x00C3,
        ServerCCStateStunDirection      = 0x00C4,
        ClientChallengeChoice           = 0x00C5, // native 14006c290 binds 0x00C5 to ClientChallengeChoice_WritePayload 14008a210 / ReadPayload 14008a200 (size 0xC); send cluster 140710c10/140710d60/140711ea0/140711f10 emits choice bytes 1/2/0xE/0xF via Network_SendOpcodePayloadHelper
        ServerChallengeResult           = 0x00C6,
        ServerChallengeUpdate           = 0x00C7,
        Client0x00C8                    = 0x00C8, // Network_RegisterServerOpcode_0351 @ 14006c290 binds decimal 200 to shared ClientMatchType_ReadPayload 14008a140 / WritePayload 14008a150 with size 4; FindPointerInData 14008a150 returned zero .data pointers — writer referenced only via registration LEA; send_helper and Network_SendMessageById filters blocked — do not alias to queue-leave or challenge (0x00C5 owns challenge sends)
        ClientHousingResidencePrivacyLevel = 0x00C9,
        ServerHousingResidenceKeyedUpdate = 0x00CA, // uint64 + uint32 fields; semantics unresolved
        ServerHousingResidenceEmpty     = 0x00CB, // empty; reader ServerEmpty_ReadPayload @ 14007d8e0
        ServerHousingResidenceUInt15    = 0x00CC, // 15-bit scalar; reader ServerUInt15_ReadPayload @ 14007c3a0
        ServerHousingResidenceUInt15Alt = 0x00CD, // 15-bit scalar; shares reader with 0x00CC
        ServerHousingResidenceWideString = 0x00CE, // wide string housing residence output
        ServerHousingResidenceEmptyFollowUp = 0x00D1, // empty; reader ServerEmpty_ReadPayload @ 14007d8e0
        ClientClosedInstanceSettings    = 0x00D2,
        ServerHideInstanceGameModeDialog = 0x00D3,
        ClientCombatOptions             = 0x00D5,
        ServerPublicEventEnd            = 0x00D6,
        ClientConvertResource           = 0x00D7,
        ServerCostume                   = 0x00D8,
        ServerCostumeList               = 0x00D9,
        ServerCharacterCreate           = 0x00DC,
        ServerChannelUpdateLoot         = 0x00DD,
        ClientDashCast                  = 0x00DE,
        ServerDatacubeAuxByte           = 0x00DF, // 1-byte datacube cluster aux
        ServerDatacubeUpdateList        = 0x00E0,
        ServerDatacubeUpdate            = 0x00E1,
        ServerDatacubeVolumeUpdate      = 0x00E2,
        ClientSpellCastState            = 0x00E3, // one-bit spell-cast state update from local cast gating
        ClientResurrectRequest          = 0x00E4,
        ServerCharacterDeleteResult     = 0x00E6,
        ServerCharacterDisabled         = 0x00E7,
        ClientDuelAccept                = 0x00E8,
        ClientDuelDecline               = 0x00E9,
        ClientDuelForfeit               = 0x00EA,
        ServerDuelFailure               = 0x00EB,
        ClientDuelInitiate              = 0x00EC,
        Client0x00ED                    = 0x00ED, // uint64 + uint32 + uint64 + three trailing bits; exact 0xED immediate hits resolve to mail-side GameFormula lookups, not packet ownership
        ServerDuelAuxByte               = 0x00EE, // 1-byte duel cluster aux
        ClientPathScientistDismissScanbot = 0x00F0,
        ServerInstanceSettings          = 0x00F1, // handler sends 0x00D5 and ClientPlayerMovementSpeedUpdate
        ClientEnteredWorld              = 0x00F2,
        ClientPathExplorerProgressReport = 0x00F3,
        ServerPathMissionAdvanced       = 0x00F4,
        ServerPathExplorerPowerMapStarted = 0x00F5,
        ServerPathExplorerPowerMapEntered = 0x00F6,
        ServerPathExplorerPowerMapExited = 0x00F7,
        ServerPathExplorerPowerMapFailed = 0x00F8,
        ClientPathExplorerPowerMapProgress = 0x00F9,
        ServerPathExplorerPowerMapWaiting = 0x00FA,
        ClientMovementFallDamage        = 0x00FB, // movement/fall branch sends one float from local movement state
        ClientMovementFallLand          = 0x00FC, // movement state payload sent when local fall/landing state changes
        ServerCharacterFlagsUpdated     = 0x00FE,
        ClientFlightPathPurchase        = 0x00FF,
        ServerResurrectionState         = 0x0100,
        ServerResurrectionAuxByte       = 0x0101, // 1-byte resurrection cluster aux
        ServerGalacticArchiveRefresh    = 0x0102,
        ClientGalacticArchiveUnlock     = 0x0103,
        ServerGalacticArchiveUpdate     = 0x0104,
        ClientGalacticArchiveViewed     = 0x0105,
        ServerGenericError              = 0x0106,
        ServerHazardAction              = 0x0109,
        ServerHazardList                = 0x010A,
        ServerHazardModifiers           = 0x010B,
        ClientGuildHolomarkUpdate       = 0x010C,
        ServerHousingBasicsEmpty        = 0x010D, // empty; reader ServerEmpty_ReadPayload @ 14007d8e0
        ServerHousingBasics             = 0x010E,
        ServerCharacterListEntry        = 0x010F, // standalone 0xA0 character-list row; shares the ServerCharacterList.Character payload reader
        ServerHousingBasicsFollowup     = 0x0110, // uint32 + 18-bit + uint32 + 8-bit; reader 14008de70
        ServerItemAdd                   = 0x0111,
        ServerPublicEventStart          = 0x0112,
        ServerPublicEventLeave          = 0x0113,
        ServerDuelLeftArea              = 0x0114,
        ServerCharacterDeletedInfo      = 0x0116,
        ServerCharacterList             = 0x0117,
        Client0x011B                    = 0x011B, // native client registration binds 0x011B to shared zero-payload ClientCraftingAbandon_WritePayload 140001ba0; owner unresolved
        ServerLootBindOnPickup          = 0x011C,
        Client0x011D                    = 0x011D, // native client registration binds 0x011D to shared ClientTradeskillResetTalents_WritePayload 14007d010; current model stays one raw uint32 diagnostic field
        ClientMailDelete                = 0x011E,
        ClientMailOpen                  = 0x0122,
        ClientMailPayCod                = 0x0123,
        ClientMailReturn                = 0x0124,
        ClientMailTakeAllFromSelection  = 0x0125,
        ClientMailTakeAttachment        = 0x0126,
        ClientMailTakeCash              = 0x0127,
        ServerUnlockMount               = 0x0129,
        ClientItemMoveToSupplySatchel   = 0x012A,
        ClientOptions                   = 0x012B,
        ServerQuestObjectiveWorldLocation = 0x012C,
        Client0x012D                    = 0x012D, // native client registration binds 0x012D to ClientSuggest_WritePayload 14007ae80; send_helper_filter_12d on Network_SendOpcodePayloadHelper and accountitem010_filter on AccountItem_SendViaNetworkMessageId 140016010 both found no 0x12D — sender blocked
        ServerPetCustomisationList      = 0x012E,
        ServerPetCustomisation          = 0x012F,
        ServerPublicEventStatsUpdate    = 0x0130,
        ServerPublicEventLocationUpdate = 0x0131,
        ServerPublicEventObjectiveUpdate = 0x0132,
        ServerPublicEventObjectiveNotificationMode = 0x0133,
        ServerPublicEventObjectiveStatusUpdate = 0x0134,
        ServerPublicEventTeamMultiplier = 0x0135,
        ServerPublicEventTimeUpdate     = 0x0136,
        ServerPublicEventPersonalStatsUpdate = 0x0137,
        ServerPublicEventMapRegionUpdate = 0x0138,
        ServerPublicEventAuxRaw         = 0x0139, // 0x10-byte public-event cluster aux
        ServerPublicEventResetObjectiveState = 0x013A,
        ServerPublicEventPersonalStatUpdate = 0x013B,
        ServerPveRatingUpdate           = 0x013C,
        ServerPvpCooldownClear          = 0x013D,
        ServerPvpCooldownUpdate         = 0x013E,
        ServerPvpRatingUpdate           = 0x0140,
        ClientRapidTransport            = 0x0141,
        ClientRealmTransfer             = 0x0142, // native sender ClientRealmTransfer_SendFromLuaDispatch 140027d80 is registered beside GetRealmTransferDestinations/RealmTransfer table strings; payload is u64 selected-character id, u14 target realm id, and one trailing transfer flag
        ServerAppearanceAuxByte         = 0x0143, // 1-byte appearance cluster aux
        ClientCharacterAppearanceChange = 0x0144,
        ServerCharacterAppearanceResult = 0x0145,
        ServerItemDelete                = 0x0148,
        ClientItemDelete                = 0x0149,
        ServerAbilityRemove             = 0x014A,
        ServerCharacterRenameResult     = 0x014B,
        ClientRepairItemVendor          = 0x014C, // repair item/all vendor request; zero item branch carries total repair cost
        ServerLootAuxByte               = 0x014D, // 1-byte loot cluster aux
        ClientEntityInteractChair       = 0x014E,
        ClientLootItem                  = 0x014F,
        ClientResetAttributePoints      = 0x0150,
        ClientRespecAmps                = 0x0151,
        ServerAmpRespecResult           = 0x0152,
        ClientResetSingleInstance       = 0x0153,
        ServerInstanceResetFailed       = 0x0154,
        ServerInstanceResetResult       = 0x0155,
        ServerInstanceResetAux          = 0x0157, // 8-byte instance-reset cluster aux
        ServerShowInstanceRestrictedDialog = 0x0158,
        ClientResurrectAccept           = 0x015A,
        ServerResurrectRequest          = 0x015B,
        ClientCCStateKnockdownBreak     = 0x015C,
        ClientLootRollAction            = 0x015D,
        ClientItemUseLootBag            = 0x015E,
        ClientPathScientistDismissScanbotPathAction = 0x015F,
        ServerPathMissionAuxByte        = 0x0160, // 1-byte path-mission cluster aux
        ClientPathScientistRequestScanbot = 0x0180,
        ServerPathScientistAuxUInt32    = 0x0181, // 4-byte path-scientist cluster aux
        ServerCharacterSelectFail       = 0x0162,
        ClientSetInstanceSettings       = 0x0163,
        ServerShowInstanceGameModeDialog = 0x0164,
        ClientSellItemToVendor          = 0x0166,
        ClientRepairVendorStatusRequest = 0x0167,
        ClientMailSend                  = 0x0168,
        ServerAbilityPoints             = 0x0169,
        ClientNonSpellActionSetChanges  = 0x016A,
        ServerActionSetDualUInt32Lists  = 0x016B, // uint32 pair + counted uint32 lists; reader FUN_14008dc30
        ServerShowActionBar             = 0x016C,
        ServerActionSetUInt16           = 0x016D, // 16-bit scalar; reader LAB_14008ed80
        ServerActionSetUInt32           = 0x016E, // uint32 scalar; reader ServerUInt32_ReadPayload
        ClientSetStance                 = 0x016F,
        ClientSetIgnoreDuelRequests     = 0x0170,
        ServerPhaseVisibilityWorldLocation = 0x0171,
        ServerPlaneVisibilitySpellSlingerVoid = 0x0172,
        ClientPvpToggleFlags            = 0x0173,
        ClientSetSpec                   = 0x0174,
        ServerSpecChanged               = 0x0175,
        ServerQuestSpellShortcut        = 0x0176,
        ClientToggleWeapons             = 0x0177,
        ServerSoundTrigger              = 0x0178,
        ServerTutorial                  = 0x0179,
        ClientAbilityBookActivateSpell  = 0x017A,
        ServerSpellUpdate               = 0x017B,
        ClientSpendAttributePoints      = 0x017C,
        ClientItemSplit                 = 0x017D,
        ClientSpellToggleCast           = 0x017E,
        ServerItemStackCountUpdate      = 0x017F,
        ClientItemMove                  = 0x0182,
        ServerItemUnlockUInt32Flag      = 0x0183, // uint32 + flag item-unlock aux
        ClientItemMoveFromSupplySatchel = 0x0184,
        ClientEntitySelect              = 0x0185,
        ServerEntitySelectAuxUInt32     = 0x0186, // 4-byte entity-select cluster aux
        ServerEntitySelectAuxByte       = 0x0187, // 1-byte entity-select cluster aux
        ServerFlightPathUpdate          = 0x0188,
        ServerTitleSet                  = 0x0189,
        ServerTitleUpdate               = 0x018A,
        ServerTitles                    = 0x018B,
        ClientP2PTradingAcceptInvite    = 0x018C,
        ClientP2PTradingAddItem         = 0x018D,
        ServerP2PTradeUpdateItem        = 0x018E,
        ClientP2PTradingCancelTrade     = 0x018F,
        ClientP2PTradingCommit          = 0x0190,
        ClientP2PTradingDeclineInvite   = 0x0191,
        ClientP2PTradingInitiateTrade   = 0x0192,
        ServerP2PTradeInvite            = 0x0193,
        ClientP2PTradingRemoveItem      = 0x0194,
        ServerP2PTradeItemRemoved       = 0x0195,
        ServerP2PTradeResult            = 0x0196,
        ClientP2PTradingSetMoney        = 0x0197,
        ServerP2PTradeUpdateMoney       = 0x0198,
        ServerSupplySatchelUpdate       = 0x0199,
        ServerSupplySatchelAux          = 0x019A, // 8-byte supply-satchel cluster aux
        ServerPlayerChanged             = 0x019B,
        ServerActionSetUInt16List       = 0x019C, // 7-bit count + ushort rows; reader FUN_14008e1f0
        ServerActionSet                 = 0x019D,
        ServerAttributePoints           = 0x019E,
        ServerStanceChanged             = 0x019F,
        ServerAbilityBook               = 0x01A0,
        ServerAmpPowerUpdate            = 0x01A1,
        ClientCommitAmpSpec             = 0x01A2,
        ServerAmpList                   = 0x01A3,
        ServerActionSetFiveUInt32       = 0x01A4, // five uint32 fields; reader FUN_1400819b0 (shared with 0x01AC)
        ServerReputationUpdate          = 0x01A5,
        ServerReputationAuxUInt32       = 0x01A6, // 4-byte reputation follow-up aux
        ServerReputationAuxRow          = 0x01A7, // 0x10-byte reputation follow-up aux
        ServerReputationAuxRowAlt       = 0x01A8, // 0x10-byte reputation follow-up aux
        ServerReputationAuxUInt64       = 0x01A9, // 8-byte reputation follow-up aux
        ServerPathUpdateXP              = 0x01AA,
        ServerResurrectionUpdate        = 0x01AB,
        ServerExperienceGained          = 0x01AC,
        ClientLootVacuum                = 0x01AD,
        ServerUnlockVanityPet           = 0x01AE,
        ClientVehicleDisembark          = 0x01AF,
        ClientVehicleEmbark             = 0x01B0,
        ServerVehicleEmbarkAux          = 0x01B2, // 0x10-byte vehicle embark cluster aux
        ServerResurrectionShow          = 0x01B3,
        ServerZoneMap                   = 0x01B4,
        ServerChatAction                = 0x01B5,
        ServerChatFlag                  = 0x01B7,
        ServerChatAuxBulk               = 0x01B8, // 0x68-byte chat cluster aux
        ClientChatJoin                  = 0x01BA,
        ServerChatJoinResult            = 0x01BB,
        ServerChatJoin                  = 0x01BC,
        ClientChatKick                  = 0x01BD,
        ClientChatLeave                 = 0x01BE,
        ServerChatLeave                 = 0x01BF,
        ServerChatList                  = 0x01C0,
        ServerChatAuxPayload            = 0x01C1, // 0x20-byte chat cluster aux
        ServerChatAccept                = 0x01C2,
        ClientChat                      = 0x01C3,
        ServerChatAuxPayloadAlt         = 0x01C4, // 0x20-byte chat cluster aux
        ServerChatNPC                   = 0x01C6,
        ServerChat                      = 0x01C8,
        ServerChatNPCCustom             = 0x01CA,
        ClientChatModerator             = 0x01CD,
        ClientChatMute                  = 0x01CE,
        ClientChatOwner                 = 0x01CF,
        ClientChatPassword              = 0x01D0,
        ClientChatList                  = 0x01D2,
        ServerChatResult                = 0x01D3,
        ClientChatWhisper               = 0x01D4,
        ServerChatWhisperFail           = 0x01D9,
        ServerChatZoneChange            = 0x01DA,
        ServerChatAuxNotification       = 0x01EF, // 0x10-byte chat/cinematic boundary aux
        ServerCinematicComplete         = 0x0210,
        ServerCinematicPlatformAdd      = 0x0211,
        ServerCinematicTransitionPosition = 0x0212,
        ServerCinematicCameraAttach     = 0x0213,
        ServerCinematicCameraPosVel     = 0x0214,
        ServerCinematicCameraSpline     = 0x0215,
        ServerCinematicCameraTransition = 0x0216,
        ServerCinematicCameraUnit       = 0x0217, // delay, unit id, and target flag for the cinematic camera subject
        ServerCinematicCamera           = 0x0218,
        ServerCinematicPlayerControl    = 0x0219,   
        ServerCinematicFullScreenEffectAdd = 0x021A,
        ServerCinematicMissileActorAdd  = 0x021B,
        ServerCinematicVisualEffectAdd  = 0x021C,
        ServerCinematicActorRemove      = 0x021D,
        ServerCinematicPlatformDetachActor = 0x021E,
        ServerCinematicAdvanceToEnding  = 0x021F,
        ServerCinematicActorVisibility  = 0x0220,
        ServerCinematicCameraRotation   = 0x0221,
        ServerCinematicTransitionDurationSet = 0x0222, // scale transition type plus start/mid/end durations
        ServerCinematicFullScreenEffectRemove = 0x0223,
        ServerCinematicMissileActorRemove = 0x0224,
        ServerCinematicVisualEffectEnd  = 0x0225,
        ServerCinematicSequenceOffset   = 0x0226, // adjusts scheduled cinematic action timing relative to current time
        ServerCinematicFlags            = 0x0227,
        ServerCinematicActorAdd         = 0x0228,
        ServerCinematicStoryPanelDialogHide = 0x0229,
        ServerCinematicText             = 0x022A,
        ServerCinematicDelayFlag        = 0x022B, // cinematic setup shell carrying one 32-bit delay and one trailing flag bit; bootstrap sends zeroed payload while Q3673 sets the flag before transition duration setup
        ServerCinematicEnd              = 0x022C,
        ServerCinematicWhiteOut         = 0x022D,
        ServerCinematicStart            = 0x022E,
        ServerCinematicActorSpline      = 0x022F,
        ServerCinematicActorAngle       = 0x0230,
        ServerCinematicActorMode        = 0x0231,
        ServerCinematicNotify           = 0x0232,
        ClientAccountItemClaimPendingItemGroup = 0x0233,
        ServerUiWindowState             = 0x0237, // one 32-bit UI window state/id used by vehicle and vendor-style panes
        ServerPetClearFlair             = 0x023B,
        ClientStatisticsWatchdog        = 0x023C,
        ClientStatisticsWindowOpen      = 0x023D,
        ClientStatisticsGfx             = 0x023E,
        ClientStatisticsConnection      = 0x023F,
        ClientStatisticsFramerate       = 0x0240,
        ClientPregameKeepAlive          = 0x0241,
        ClientEncrypted                 = 0x0244,
        ServerCombatLog                 = 0x0247,
        ClientCombatLogDisableOthers    = 0x0248,
        ClientCombatLogDisables         = 0x0249,
        ServerCommodityAuctionFilledPartial = 0x024A,
        ServerCommodityAuctionRemoved   = 0x024B,
        ServerCommodityInfoResults      = 0x024C,
        ServerHousingCommunityRename    = 0x024D,
        ServerQuestContractGoodQualityChanged = 0x0252,
        ClientCostumeSave               = 0x0255,
        ClientCostumeSet                = 0x0256,
        ServerCostumeSave               = 0x0257,
        ServerCostumeItemUnlockMultiple = 0x0258,
        ServerCostumeItemUnlock         = 0x0259,
        ServerCostumeItemList           = 0x025A,
        ClientCharacterCreate           = 0x025B,
        ClientPacked                    = 0x025C, // the same as ClientEncrypted except the contents isn't encrypted?
        ServerPlayerCreate              = 0x025E,
        ServerEntityCreateAuxRow        = 0x025F, // entity-create aux row; reader 140095c20
        ServerEntityCreateAuxRowList    = 0x0260, // counted 0x025F rows; reader 140095ce0
        ServerEntityCreateAuxBitPackedRowList = 0x0261, // counted 0x0263 rows; reader 140095a80
        ServerEntityCreate              = 0x0262,
        ServerEntityCreateAuxBitPackedRow = 0x0263, // entity-create aux bit-packed row; reader 1400959c0
        ServerEntityCreateAuxScalarList = 0x0264, // entity-create aux scalar list; reader 140095b40
        ClientCREDDExchangeBuyOrderSubmit = 0x0265,
        ClientCREDDExchangeCancelOrder  = 0x0267,
        ClientCREDDRedeem               = 0x0268,
        ClientCREDDExchangeRequestInfo  = 0x0269,
        ServerCREDDExchangeInfoResults  = 0x026A,
        ClientCREDDExchangeSellOrderSubmit = 0x026B,
        ServerSubscriptionInfo          = 0x033D,
        ServerCustomerSurveyRequest     = 0x033E,
        ClientCustomerSurveySubmit      = 0x033F,
        ServerSupportUInt32WideString       = 0x0347, // uint32 + wide string; reader 1400980f0
        ServerSupportUInt32HeaderAndTriplets = 0x0348, // 3x uint32 + 3x uint32 triplet; reader 1400a40c0
        ServerSupportEmptyAck349            = 0x0349, // empty; reader 14007d8e0
        ServerSupportUInt32Ack34A           = 0x034A, // uint32; reader 14007ab50
        ServerSupportEmptyAck34B            = 0x034B, // empty; reader 14007d8e0
        ServerSupportUInt5AndSixUInt32      = 0x034C, // 5-bit + 6x uint32; reader 1400a4040
        ServerSupportUInt32HeaderAndFourTriplets = 0x034D, // 4x uint32 + 4x triplet; reader 1400a4150
        ServerSupportSurveyList             = 0x034E, // wide string + header + counted rows; reader 1400a4260
        ServerSupportUInt32AndFlags         = 0x034F, // uint32 + 2-bit; reader 1400a3f70
        ServerSupportUInt32Ack350           = 0x0350, // uint32; reader 14007ab50
        ServerSupportUInt32AndTwoTriplets   = 0x0351, // uint32 + 2x triplet + uint32; reader 1400a3fd0
        ClientCharacterDelete           = 0x0352,
        ServerEntityDestroy             = 0x0355,
        ClientDialogOpened              = 0x0356,  
        ServerDialogStart               = 0x0357,
        ServerDialogEnd                 = 0x0358,
        ServerQuestLuaEvent             = 0x0359,
        ClientQuestAbandon              = 0x035A,
        ClientQuestAccept               = 0x035B,
        ServerQuestStateChange          = 0x035C,
        ClientQuestComplete             = 0x035D,
        ClientQuestSetIgnore            = 0x035E,
        ServerQuestInit                 = 0x035F,
        ClientCommunicatorAction        = 0x0360,
        ServerQuestObjectiveUpdate      = 0x0361,
        ServerQuestPeriodicReset        = 0x0362,
        ServerQuestShared               = 0x0363,
        ClientQuestSetTracked           = 0x0364,
        ClientQuestRetry                = 0x0365,
        ServerDisabledGameplaySystems   = 0x0366,
        ServerForceKick                 = 0x036A,
        ClientEmote                     = 0x037E,
        ServerCostumeItemAux            = 0x037F, // 0x18-byte costume/emote cluster aux
        ClientCostumeItemForget         = 0x038B,
        ClientPackedWorld               = 0x038C,
        ClientFriendshipAccountAddByEmail = 0x0397,
        ClientFriendshipAccountUpgradeFromFriend = 0x0398,
        ServerFriendshipAccountUpdate   = 0x0399,
        ServerFriendshipAccountRemovedCharacter = 0x039A,
        ClientFriendshipAccountSetPublicDisplayName  = 0x039B,
        ServerFriendshipAccountDisplayNameUpdate = 0x039C,
        ClientFriendshipAccountSetPrivateData = 0x039D,
        ClientFriendshipIgnoreStrangersState = 0x039E,
        ServerFriendshipAccountInviteList = 0x039F,
        ServerFriendshipAccountInviteRemove = 0x03A0,
        ClientFriendshipAccountInviteResponse = 0x03A1,
        ClientFriendshipAccountInviteMarkSeen = 0x03A2,
        ServerFriendshipAccountList     = 0x03A3,
        ServerFriendshipAccountCharacterZoneChanged = 0x03A4,
        ServerFriendshipIgnoreStrangersState = 0x03A5,
        ServerFriendshipAccountPersonalStatus = 0x03A6,
        ClientFriendshipAccountPersonalPresenceChange = 0x03A7,
        ServerFriendshipAccountPresenceUpdate = 0x03AA,
        ClientFriendshipAccountSetPublicNote = 0x03AC,
        ServerFriendshipAccountPublicNote = 0x03AD,
        ServerFriendshipAccountPrivateNote = 0x03AE,
        ClientFriendshipAccountRemove   = 0x03AF,
        ServerFriendshipAccountRemoved  = 0x03B0,
        ServerFriendshipAccountLastOnlineUpdate = 0x03B1,
        ServerFriendshipAccountCharacterLevelUpdate = 0x03B2,
        ClientFriendshipAccountAddByIdentity = 0x03B3,
        ClientFriendshipAddByName       = 0x03B4,
        ServerFriendshipAdd             = 0x03B5,
        ClientFriendshipSetAutoResponseMessage = 0x03B7,
        ServerFriendshipInviteList      = 0x03BA,
        ServerFriendshipInviteRemove    = 0x03BB,
        ClientFriendshipInviteResponse  = 0x03BC,
        ClientFriendshipInviteMarkSeen  = 0x03BD,
        ServerFriendshipList            = 0x03BE,
        ClientFriendshipGetLocations    = 0x03BF,
        ServerFriendshipLocationUpdate  = 0x03C0,
        ClientFriendshipRemoveByIdentity = 0x03C1,
        ClientFriendshipRemoveByName    = 0x03C2,
        ServerFriendshipRemove          = 0x03C3,
        ServerFriendshipResult          = 0x03C4,
        ServerFriendshipLevelUpdate     = 0x03C6,
        ClientFriendshipSetNoteByIdentity = 0x03C7,
        ClientFriendshipSetNoteByName   = 0x03C8,
        ServerFriendshipSetNote         = 0x03C9,
        ServerFriendshipLastOnlineUpdate = 0x03CA,
        ServerFriendshipTypeUpdate      = 0x03CB,
        ClientFortuneFlipCard           = 0x03CD,
        ServerFortuneCardUpdate         = 0x03CF,
        ServerFortuneReset              = 0x03D0,
        ServerFortuneCards              = 0x03D1,
        ServerFortuneRewards            = 0x03D2,
        ClientFortuneNotifyStorefront   = 0x03D3,
        ClientFortuneStart              = 0x03D4,
        ServerRealmInfo                 = 0x03DB,
        ServerRealmEncrypted            = 0x03DC,
        ClientCheat                     = 0x03E0,
        ServerRealmBroadcast            = 0x03E1,
        ClientRequestCommodityInfo      = 0x03E6,
        ClientCREDDExchangeRequestHistory = 0x03E7,
        ClientRequestOwnedCommodityOrders = 0x03EC,
        ClientRequestOwnedItemAuctions  = 0x03ED,
        ClientGetRealmTransferDestinations = 0x03EE,
        ServerRealmTransferDestinationsAux = 0x03EF, // 0x10-byte realm-transfer cluster aux
        ClientAccountItemGiftPendingItemGroupToAccount = 0x03F1,
        ClientAccountItemGiftPendingItemGroupToCharacter = 0x03F2,
        ClientItemGenericUnlock         = 0x0400,
        ServerGroupMemberAdd            = 0x0405,
        ClientGroupFlagsChanged         = 0x0406,
        ClientGroupSetRole              = 0x0408,
        ServerGroupFlagsChanged         = 0x0410,
        ClientGroupGotoGroupInstance    = 0x0411,
        ClientGroupSetInstanceDifficulty = 0x0412,
        ServerGroupInstanceDifficultyResponse = 0x0414, // 0x18-byte payload; response to ClientGroupSetInstanceDifficulty (0x0412). Field layout needs Ghidra verification.
        ClientGroupInvite               = 0x0416,
        ClientGroupInviteResponse       = 0x041A,
        ServerGroupInviteResult         = 0x041D,
        ServerGroupInviteReceived       = 0x041F,
        ClientGroupRequestJoin          = 0x0422,
        ServerGroupRequestJoinResponse  = 0x0424,
        ServerGroupJoin                 = 0x0427,
        ClientGroupKick                 = 0x0428,
        ServerGroupKickResult            = 0x042A, // 0xC-byte payload; response to ClientGroupKick (0x0428).
        ClientGroupLeave                = 0x042B,
        ServerGroupLeave                = 0x042D,
        ClientGroupLootRulesChange      = 0x042E,
        ServerGroupLootRulesChange      = 0x042F,
        ServerGroupLootRuleValidationResult = 0x0431, // 0x18-byte payload; after ServerGroupLootRulesChange (0x042F).
        ClientGroupMarkUnit             = 0x0432,
        ServerGroupRosterUpdate          = 0x0436, // 0x60-byte payload; per-member roster/stat refresh (FUN_140607490).
        ServerGroupMemberFlagsChanged   = 0x0437,
        ServerGroupMemberRoleChange      = 0x0438, // native reader 140083990 is group id + leading uint32 + counted identity array + parallel uint32 array; current model remains provisional
        ServerGroupReadyCheckStatusUpdate = 0x0441, // 0x38-byte payload; ready check status broadcast.
        ServerGroupActionResult         = 0x0443,
        ClientGroupPromote              = 0x0446,
        ServerGroupPromote              = 0x0447,
        ClientGroupSendReadyCheck       = 0x044A,
        ServerGroupSendReadyCheck       = 0x044C,
        ServerGroupReferral             = 0x044F,
        ServerGroupRemove               = 0x0450,
        ClientGroupRequestJoinResponse  = 0x0453,
        ServerGroupRequestJoinResult    = 0x0456,
        ServerGroupRequestJoinWindow     = 0x045A, // 0x20-byte payload; join request dialog for leader.
        ServerGroupMarkUnit             = 0x045B,
        ClientQuestShareResult          = 0x045E,
        ClientQuestShare                = 0x045F,
        ServerQuestShareResult           = 0x0461, // 0x10-byte payload; quest share result between ClientQuestShare (0x045F) and ServerGroupMaxSizeChange (0x0462).
        ServerGroupMaxSizeChange        = 0x0462,
        ServerGroupMemberStatUpdate     = 0x0466,
        ServerGroupUpdatePlayerRealm    = 0x0467,
        ServerGroupMemberDetailUpdate    = 0x0468, // native reader 140084280 is group id + target identity + uint32 count + counted uint64 array; current model remains provisional
        ServerGroupPositionUpdate       = 0x0469,
        ServerGuildBankInventoryAdd     = 0x046F,
        ServerGuildBankInventoryRemove  = 0x0470,
        ClientGuildBankTransaction      = 0x0471,
        ClientGuildBankTransaction2     = 0x0473,
        ServerGuildBankInventoryCount   = 0x0476,
        ClientGuildBankTabOpen          = 0x0477,
        ServerGuildBankTabCount         = 0x0478,
        ServerGuildBankTabRename        = 0x0479,
        ServerGuildBankTabInventory     = 0x047A,
        ServerGuildClassification       = 0x0480,
        ClientGuildRegister             = 0x0481,
        ServerGuildEventLogChange       = 0x0487,
        ServerGuildEventLog             = 0x0489,
        ServerGuildEventLogDeleteEntry  = 0x048A,
        ServerGuildFlagsUpdate          = 0x048B,
        ServerGuildInfluenceAndMoney    = 0x048D,
        ServerGuildInfoMessageUpdate    = 0x048F,
        ClientGuildInviteResponse       = 0x0490,
        ServerGuildInvite               = 0x0491,   
        ServerGuildJoin                 = 0x0493,
        ServerGuildRemove               = 0x0495,
        ServerGuildInit                 = 0x0497,
        ServerGuildRecruitmentAvailability = 0x049F,
        ServerGuildRoster               = 0x04A0,
        ServerGuildBankWithdraw         = 0x04A1,
        ServerGuildMemberRemove         = 0x04A2,
        ServerGuildMemberChange         = 0x04A3,
        ServerGuildMotdUpdate           = 0x04A5,
        ClientGuildStandardModify       = 0x04A6,
        ClientGuildBankMoneyTransaction = 0x04A8,
        ServerGuildNameplateChange      = 0x04AC,
        ServerUnitGuildNameplateChanged = 0x04AE,
        ServerGuildRename               = 0x04AF,
        ClientGuildOperation            = 0x04B1,
        ClientGuildPerkActivate         = 0x04B2,
        ClientGuildBankTabRename        = 0x04B3,
        ServerGuildPerkActivated        = 0x04B6,
        ServerGuildPerkDeactivated      = 0x04BA,
        ServerGuildPerkUnlocked         = 0x04BD,
        ServerGuildPvpStatsUpdate       = 0x04C1,
        ServerGuildQueueStateChanged    = 0x04C3,
        ServerGuildRankChange           = 0x04C5,
        ServerGuildResult               = 0x04C9,
        ServerGuildResult2              = 0x04CA,
        ClientGuildSetStandard          = 0x04CF,
        ServerGuildStandard             = 0x04D0,
        ServerUnitMemberOfGuildChange   = 0x04D4,
        ServerHealthyGamingUpdate       = 0x04DA,
        ClientCastSpellContinuous       = 0x04DB,
        ServerHousingPlacedResidencesList = 0x04DD,
        ServerHousingResidenceDecor     = 0x04DE,
        ServerHousingProperties         = 0x04DF,
        ServerHousingPlots              = 0x04E1,
        ClientItemUseDecor              = 0x04E7,
        ClientHousingCommunityRemoval   = 0x04EA,
        ClientHousingCrateAllDecor      = 0x04EC,
        ClientHousingCommunityDonate    = 0x04F5,
        ServerHousingCommunityDonateUpdate = 0x04FE,
        ServerHousingNeighborhoodEntry  = 0x0501,
        ServerHousingNeighborhoodList   = 0x0506,
        ServerHousingNeighbors          = 0x0507,
        ServerHousingVendorList         = 0x0508,
        ServerHousingHarvestItemsSentToOwner = 0x0509, // payload @ Harvest_DispatchItemsSentToOwnerEvent (1404bbb80); opcode inferred from housing gap
        ClientHousingRemodel            = 0x050A,
        ClientHousingDecorUpdate        = 0x050B,
        ClientHousingInteriorWallpaperUpdate = 0x050D, // Residence.RemoveInteriorWallpaper/PurchaseInteriorWallpaper six-slot plug item update
        ClientHousingFlagsUpdate        = 0x050E,
        ClientHousingPlugUpdate         = 0x0510,
        ClientHousingNeighborInvite     = 0x0512,
        ClientHousingNeighborInviteResponse = 0x0513,
        ServerHousingNeighborInvitePrompt = 0x0514,
        ClientHousingNeighborEvict      = 0x0515,
        ServerHousingNeighborInviteResult = 0x0516, // native row shape mapped; shared neighbor row plus 7-bit HousingResult
        ClientHousingNeighborSetPermission = 0x0518,
        ServerHousingNeighborUpdate    = 0x0519, // native row shape mapped; shared neighbor row plus 3-bit update action
        ServerHousingCommunityPlotReservation = 0x051F,
        ClientHousingVendorList         = 0x0525,
        ServerHousingRandomCommunityList = 0x0526,
        ServerHousingRandomResidenceList = 0x0527,
        ClientHousingRenameProperty     = 0x0529,
        ClientHousingPlacedResidencesList = 0x052A,
        ClientHousingCommunityPlacement = 0x052B,
        ClientHousingRandomCommunityList = 0x052C,
        ClientHousingRandomResidenceList = 0x052D,
        ClientHousingReturn             = 0x052E,
        ClientHousingVisitResidence     = 0x052F,
        ClientHousingVisit              = 0x0531,
        ServerHousingOwnership          = 0x0533,
        ServerHousingResult             = 0x0536,
        ClientHousingCommunityPrivacyLevel = 0x0538,
        ServerHousingCommunityPlacement = 0x053A, // target community residence, placed residence id, property index
        ServerHousingCommunityPrivacyLevelUpdate = 0x053B, // target community residence, type-7 cache flags, 3-bit Lua privacy value
        ClientHousingEditMode           = 0x053C,
        ClientICCommChannelJoin         = 0x0546,
        ServerICCommChannelJoinResult   = 0x0547,
        ServerICCommChannelJoin         = 0x0548,
        ClientICCommChannelNotJoined    = 0x0549,
        ServerICCommChannelLeft         = 0x054A,
        ClientICCommMessage             = 0x054B,
        ServerICCommMessageResult       = 0x054C,
        ServerICCommOrderedMessage      = 0x054D,
        ServerICCommDirectedMessage     = 0x054E,
        Client0x0550                    = 0x0550, // native ClientWorldOpcodeRegister_MovementSpline 1400a8190 (not ICComm table 14006c290) binds 0x0550 to ClientTradeskillResetTalents_WritePayload 14007d010; send_helper_filter_0550 and 1403355e0 filter found no 0x550 immediate — sender blocked via message-id rail; compound cluster 14007dd40 is registered for 0x06EA not 0x0550
        ServerSpellList                 = 0x0551,
        ClientInspectPlayerRequest      = 0x0552,
        ServerInspectPlayerResponse     = 0x0553,
        ServerInstanceBusy              = 0x0555,
        ClientAuctionBuyOrderSubmit     = 0x055E,
        ServerAuctionBidPosted          = 0x055F,
        ServerAuctionBidResult          = 0x0560,
        ServerAuctionExpired            = 0x0561,
        ServerAuctionOutbid             = 0x0562,
        ServerAuctionSearchResults      = 0x0563,
        ServerAuctionWon                = 0x0564,
        ServerAuctionCancelResult       = 0x0565,
        ServerMailItemDeprecation       = 0x0566,
        ServerItemSwapAux               = 0x0567, // 0x10-byte item-swap cluster aux
        ServerItemSwap                  = 0x0568,
        ServerItemMove                  = 0x0569,
        ServerItemError                 = 0x056A,
        ServerOptionAuxPayload          = 0x056B, // 0x20-byte options cluster aux
        ServerOptionAuxPayloadLarge     = 0x056C, // 0x28-byte options cluster aux
        ServerOptionAuxPayloadMedium    = 0x056D, // 0x18-byte options cluster aux
        BiInputKeySet                   = 0x056F,
        ClientRequestInputKeySet        = 0x0570,
        ClientSetInputKeySet            = 0x0571,
        ServerLeaderboardPve            = 0x0579,
        ServerLeaderboardPvp            = 0x057A,
        ClientLeavePendingRemovalInstance = 0x057C,
        ClientHelloRealm                = 0x058F,
        ServerAuthAccepted              = 0x0591,
        ClientHelloAuth                 = 0x0592,
        ServerLogout                    = 0x0594,
        ClientPlayerInfoRequest         = 0x0597,
        ServerPlayerInfoBasicResponse   = 0x0598,
        ServerPlayerInfoFullResponse    = 0x0599,
        ClientRealmInfoRequest          = 0x059C,
        ServerRealmInfoResponse         = 0x059D,
        ServerRealmAuxUInt32TripletList = 0x05A1, // count + uint32 triplet rows; reader 140080b00
        ServerMailResult                = 0x05A2,
        ServerMailAvailable             = 0x05A3,
        ServerMailUnavailable           = 0x05A7,
        ServerMailTakeAttachment        = 0x05A8,
        ServerMatchingManagerFlag       = 0x05B0, // native 14006c290 binds 0x05B0 to shared reader slot LAB_1400807f0 with registered size 4; disassembly at 1400807f0 uses MOV R8D,0x1 (one-byte read) before 14006c090; apply cell not opcode-index proven; current model stays a structural one-flag surface reused by 0x05CC and 0x05F1
        ClientMatchingRoleCheckResponse = 0x05B2, // native client registration binds 0x05B2 to 140098e10, which serialises one 5-bit MatchType, one 32-bit Roles field, and one trailing response bit
        ClientMatchingQueueLeaveAll     = 0x05B4, // native client registration binds 0x05B4 to shared zero-payload ClientCraftingAbandon_WritePayload 140001ba0
        ClientMatchingQueueLeave        = 0x05B5, // native client registration binds 0x05B5 to shared local writer slot LAB_14008a150; FindCallsToTarget 14008a150 total_calls=0; send_helper_filter_05b5 and sendmsg filter on Network_SendMessageById found no 0x05B5 — sender blocked
        ClientMatchingQueueLeaveAsGroup = 0x05B6, // native client registration binds 0x05B6 to shared local writer slot LAB_14008a150; send_helper_filter_05b6 on Network_SendOpcodePayloadHelper found no 0x05B6 immediate — sender blocked
        ServerMatchingEligibilityChanged = 0x05B8, // native 14007ab50 reads one uint32 eligibility-flags field
        ServerMatchingMatchReadyCancel  = 0x05BC, // native 14007d8e0 reads no payload fields
        ServerMatchingMatchFinished     = 0x05BE, // native 14007d8e0 reads no payload fields
        ServerMatchingMatchEntered      = 0x05BF, // native 14007ab50 reads one uint32 matching-game-map id field
        ServerMatchingMatchExited       = 0x05C0, // native 14007d8e0 reads no payload fields
        ServerMatchingMatchInProgressReady = 0x05C4, // native 140099700 reads a 5-bit match type followed by two uint32 count fields
        ServerMatchingMatchJoined       = 0x05C6, // native 14006c290 binds 0x05C6 to local reader slot LAB_14007a530 with registered size 4; current model stays a structural one-uint14 surface for the joined matching map id
        ClientMatchingGameReadyResponse = 0x05C8, // native client registration binds 0x05C8 to shared ClientBool_WritePayload 14007e610
        ServerMatchingMatchReady        = 0x05CA, // native 140099700 reads a 5-bit match type followed by two uint32 count fields
        ServerMatchingMatchParticipantCountUpdate = 0x05CC, // native 14006c290 binds 0x05CC to shared reader slot LAB_1400807f0 with registered size 4; disassembly at 1400807f0 uses MOV R8D,0x1 (one-byte read); matching apply table has zero-payload apply cluster (1405c2440/1405c24a0 etc.) but opcode-to-cell index still blocked; current model stays a structural one-flag surface reused by 0x05B0 and 0x05F1
        ServerMatching0x05CF            = 0x05CF, // native 14006c290 binds 0x05CF to ServerUInt32_LocalReadThunk 140099110 (size 4); matching-manager apply table 140e1e228 maps apply fns via .rdata cells — tentative consumer MatchingManager_ApplyManagerUInt32Field0xA0@1405c41c0 (cell 140e1e66c) writes payload uint32 to manager+0xa0 without ClientEvent; opcode-index proof still blocked; emit blocked; F-010 sniff recommended
        ClientMatchingMatchInitiateVoteToKick = 0x05D1, // native client registration binds 0x05D1 to shared local writer slot LAB_1400867f0 with registered size 0x10; current model stays a single Identity payload
        ClientMatchingMatchInitiateVoteToSurrender = 0x05D3, // native client registration binds 0x05D3 to shared zero-payload ClientCraftingAbandon_WritePayload 140001ba0
        ClientMatchingMatchInitiateLookingForReplacements = 0x05D5, // native client registration binds 0x05D5 to shared ClientTradeskillResetTalents_WritePayload 14007d010
        ServerMatchingPenaltyUpdated    = 0x05D9, // native 14006c290 binds 0x05D9 to local reader slot LAB_140099920 with registered size 0x40; current model stays a fixed 16xuint32 penalty table ordered by MatchType
        ClientMatchingMatchLeave        = 0x05DA, // native client registration binds 0x05DA to shared zero-payload ClientCraftingAbandon_WritePayload 140001ba0; sender Matching_SendMatchLeave 14076a9f0 when match UI state==0x10
        ServerMatchingMatchLeft         = 0x05DC, // native 14006c290 binds 0x05DC to shared ServerUInt5_ReadPayload 14007e950
        ServerMatchingQueueJoin         = 0x05DF, // native 1400995f0 reads map block 1400988f0 + queue block 1400989d0 + one queued-roles uint32
        ServerMatchingQueueResultAnnounce = 0x05E1, // native 1400998c0 reads one 6-bit queue result followed by one 4-bit queue status
        ServerMatchingQueueStatus       = 0x05E3, // native 140099650 reads 4-bit status, two 5-bit match-type fields, and 16 trailing queue-membership bits
        ServerMatchingMatchPvpPoolUpdated = 0x05E5, // native 14006c290 binds 0x05E5 to local reader slot LAB_140099270 with registered size 8; current model stays a two-uint32 lives surface
        ServerMatchingPvpInactivityAlert = 0x05E6, // native 14006c290 binds 0x05E6 to shared ServerUInt32_ReadPayload 14007ab50
        ServerMatchingPvpKillNotification = 0x05E7, // native 140099440 reads killer/victim opponent variants, one 2-bit victim team, and one 3-bit death reason
        ServerMatchingMatchPvpStateInitial = 0x05E8, // native 140099190 reads a 2-bit team followed by shared state payload 140099130
        ServerMatchingMatchPvpFinished  = 0x05E9, // native 140099200 reads 2-bit winner, 3-bit end reason, and two uint32 rating deltas
        ServerMatchingMatchPvpStateUpdated = 0x05EA, // native 140099130 reads the shared 3-bit PvpGameState plus uint32 elapsed-time payload
        ServerMatchingPvpRatingUpdated  = 0x05ED, // native 140099330 reads four uint32 counters plus one 3-bit rating type
        ServerMatchingPvpTeamInfoUpdate = 0x05EE, // native 140099290 reads two wide strings plus two uint32 rating fields
        ClientMatchingQueue             = 0x05EF, // native client writer 140098a70 serialises MatchingMap plus one uint32 roles field and one uint32 prime-level field; sender Matching_QueueDispatchFromUi 14076c830
        ServerMatchingRoleCheckStarted  = 0x05F1, // native 14006c290 binds 0x05F1 to shared reader slot LAB_1400807f0, the same structural one-flag path reused by 0x05B0 and 0x05CC
        ServerMatchingGroupIsQueued     = 0x05F2, // native 14006c290 binds 0x05F2 to ServerEmpty_ReadPayload 14007d8e0
        ClientMatchingQueueParty        = 0x05F3, // native client writer 140098a70 serialises MatchingMap plus one uint32 roles field and one uint32 prime-level field; sender Matching_QueueDispatchFromUi 14076c830
        ClientMatchingQueueRandom       = 0x05F8, // native client writer 140098c00 serialises one 5-bit match type, one uint32 MatchingQueueFlags field, and one uint32 roles field; sender Matching_QueueDispatchFromUi 14076c830
        ClientMatchingQueueRandomParty  = 0x05F9, // native client writer 140098c00 serialises one 5-bit match type, one uint32 MatchingQueueFlags field, and one uint32 roles field; sender Matching_QueueDispatchFromUi 14076c830
        ServerMatchingGroupMemberRoleSelection = 0x0600, // native 14006c290 registers 0x0600 to 140086e70, the same identity + uint32 housing reservation reader as 0x051F; current model remains provisional
        ClientMatchingStopLookingForReplacements = 0x602, // native client registration binds 0x0602 to shared zero-payload ClientCraftingAbandon_WritePayload 140001ba0
        ServerMatchingLeftQueue         = 0x0604, // native 14006c290 binds 0x0604 to ServerEmpty_ReadPayload 14007d8e0
        ClientMatchingTransferIntoMatch = 0x0606, // native client registration binds 0x0606 to shared zero-payload ClientCraftingAbandon_WritePayload 140001ba0; sender Matching_SendTransferIntoMatch 14076ac30 after map lookup + flag gate
        ServerMatchingListPlayersQueuedForMap = 0x60A, // native 140099770 reads map id + count + queued-player rows via 140098500/1400ad150
        ServerMatchingMatchVoteKickCancelled = 0x060D, // native 14006c290 binds 0x060D to ServerEmpty_ReadPayload 14007d8e0
        ServerMatchingMatchVoteKickFailed = 0x0612, // native 14006c290 binds 0x0612 to ServerEmpty_ReadPayload 14007d8e0
        ServerMatchingMatchVoteKickBegin = 0x0614, // native 140099840 reads initiator identity followed by member-to-kick identity
        ServerMatchingMatchKickCooldownUpdate = 0x0616, // native 14007fcf0 reads one 6-bit MatchingQueueResult plus one uint32 wait-time field
        ClientMatchingMatchCastVoteKick = 0x0617, // native client registration binds 0x0617 to shared ClientRealmScopedIdAndBit_WritePayload 140099030
        ServerMatchingMatchVoteKickSucceeded = 0x061A, // native 14006c290 binds 0x061A to ServerEmpty_ReadPayload 14007d8e0
        ServerMatchingMatchVoteSurrenderFailed = 0x061F, // native 14006c290 binds 0x061F to ServerEmpty_ReadPayload 14007d8e0
        ServerMatchingMatchVoteSurrenderBegin = 0x0621, // native 14006c290 binds 0x0621 to ServerEmpty_ReadPayload 14007d8e0
        ServerMatchingMatchOperationResult = 0x0623, // native 14007fcf0 reads one 6-bit MatchingQueueResult plus one uint32 wait-time field
        ClientMatchingMatchCastVoteSurrender = 0x0624, // native client registration binds 0x0624 to shared ClientBool_WritePayload 14007e610
        ServerMatchingAverageWaitTimeUpdate = 0x0628, // native 140081f00 reads one 5-bit field plus one uint32 field; runtime maps this shared 8-byte reader as MatchType + average wait time and unresolved server opcode 0x0015 reuses it
        Client0x062A                    = 0x062A, // native client registration in ClientWorldOpcodeRegister_MovementSpline 1400a8190 binds 0x062A to ClientTradeskillResetTalents_WritePayload 14007d010; send_helper and sendmsg filters on Network_SendOpcodePayloadHelper/Network_SendMessageById found no 0x62A — sender blocked; static path exhausted — F-010 live sniff recommended
        Client0x0634                    = 0x0634, // same registration/writer as 0x062A; send_helper and sendmsg filters negative — sender blocked; static path exhausted — F-010 live sniff recommended
        ClientMovementControlAck        = 0x0635, // native client registration in 1400a8190 binds 0x0635 to shared ClientTradeskillResetTalents_WritePayload 14007d010; current model stays a single uint32 movement-control ticket
        ServerMovementControl           = 0x0636, // runtime sender in Player.SetControl currently writes ticket + immediate flag + controlled unit id; client acknowledges with 0x0635 and zone transfers can follow with 0x063A
        ClientEntityCommand             = 0x0637, // runtime movement input envelope consumed by MovementManager.HandleClientEntityCommands: uint32 client time + uint32 command count + repeated 5-bit command ids and payloads
        ServerEntityCommand             = 0x0638, // runtime movement sync envelope built by MovementManager.BuildNetworkEntityCommands: guid + time + time-reset/server-control bits + 5-bit command count + repeated commands
        ServerMovementControlRemove     = 0x0639, // runtime sender in Player.SetControl clears movement control with an empty payload when control is removed
        ClientZoneChange                = 0x063A,
        ClientPlayerMovementSpeedUpdate = 0x063B, // native 1404dafb0 builds and sends one raw uint32 movement-speed scalar, then dispatches PlayerMovementSpeedUpdate
        ServerAuthDenied                = 0x063D,
        Client0x063E                    = 0x063E, // native client registration in ClientWorldOpcodeRegister_MovementSpline 1400a8190 binds 0x063E to ClientSuggest_WritePayload 14007ae80; send_helper_filter_63e and accountitem010_filter on 140016010 found no 0x63E — sender blocked
        ServerMarketplaceStatus         = 0x0640,
        ServerPrerequisiteFailure       = 0x0642,
        ServerOwnedCommodityOrders      = 0x064C,
        ServerOwnedItemAuctions         = 0x064D,
        ServerPathScientistExperimentationInvoke = 0x667,
        ServerPathScientistScanbotState = 0x0669,
        ClientPathMissionAttemptScientistExperimentation = 0x066A,
        ServerPathSettlerBuildResult    = 0x066C,
        ServerPathSettlerBuildInvoke    = 0x066D,
        ServerPathSettlerBuildStatusList = 0x066E,
        ServerPathSettlerHubReward      = 0x066F,
        ClientPathSettlerImprovementBuildTier = 0x0670,
        ServerPathSettlerBuildStatus    = 0x0671,
        ServerPathSettlerNotifyUse      = 0x0672,
        ServerPathSettlerInfrastructureComplete = 0x0673,
        ServerPathSettlerInfrastructureUpdated = 0x0674,
        ServerPathSettlerInfrastructureStarted = 0x0675,
        ServerPathSoldierSoldierBuildInvoke = 0x0676,
        ServerPathSoldierTriggerOrdersTextOnUnit = 0x0677,
        ServerPathSoldierTowerDefenseUnitUpdate = 0x0678,
        ServerPathSoldierHoldOutNextWave = 0x679,
        ServerPathSoldierTowerDefenseUnitRemove = 0x067A,
        ServerPathSoldierHoldoutStatus  = 0x067B,
        ServerPathSoldierHoldoutEnd     = 0x067C,
        ClientPathSoldierImprovementBuild = 0x067D,
        ServerPathSoldierWhackAMoleBurrows = 0x067E, // delay-until-pop plus burrow unit id list
        ServerPathSoldierHoldoutDeath   = 0x067F,
        ServerPathSoldierBuildCredits   = 0x0680,
        ServerPathSoldierAddTowerDefense = 0x0681,
        ServerPendingWorldRemovalCancel = 0x0688,
        ServerPendingWorldRemoval       = 0x0689,
        ServerPetCustomisationFailed    = 0x068B,
        ClientPathScientistSetScannerName = 0x068C,
        ServerUnlockPetFlair            = 0x068D,
        ClientPetSetStance              = 0x068E,
        ServerPetStanceChanged          = 0x068F,
        ClientPlayedRequest             = 0x0693,
        ServerPlayedResponse            = 0x0694,
        ClientPathChangeRequest         = 0x06B2,
        ServerPathChangeResult          = 0x06B3,
        ServerPathRefresh               = 0x06B4,
        ServerPathEpisodeProgress       = 0x06B5,
        ServerPathExplorerScavengerHuntClueRemoveByClueIdAndUnitId = 0x06B6,
        ServerPathExplorerScavengerHuntClueRemoveByClueId = 0x06B7,
        ServerPathExplorerScavengerHuntClueAddWorldLocation = 0x06B8,
        ServerPathExplorerScavengerHuntClueAddUnitList = 0x06B9,
        ServerPathMissionActivate       = 0x06BA, 
        ServerPathMissionUpdate         = 0x06BB,
        ServerPathInitialise            = 0x06BC,
        ClientPathUnlockRequest         = 0x06BD,
        ServerPathUnlockResult          = 0x06BE,
        ServerPathSetCurrentEpisode     = 0x06BF,
        ClientIncidentReport            = 0x06C5,
        ClientSupportTicket             = 0x06D1,
        ClientCommoditySellOrderSubmit  = 0x06DA,
        ServerCommodityOrderResult      = 0x06DB,
        ClientAuctionSellOrderSubmit    = 0x06DC,
        ServerAuctionPostResult         = 0x06DD,
        ServerAuctionPostAux            = 0x06DF, // 0x20-byte auction-post cluster aux
        ClientInitiatePTRCharacterCopy  = 0x06E7, // native sender Client0x06E7_SendFromLuaDispatch 140022270 pairs with CharacterScreenLib InitiatePTRCharacterCopy @ 1409edc80; payload is selected-character u64
        ClientPtrCopy                   = 0x06E8, // native registration size 1 via ClientCraftingAbandon_WritePayload; send sites FUN_14063f540 and FUN_140707d80 emit one zero padding byte; separate from ClientInitiatePTRCharacterCopy 0x06E7
        ServerPtrCharacterCopyQueued    = 0x06EA, // native ServerEmpty_ReadPayload size 1; client consumer FUN_140020ea0 fires Lua PTRCharacterCopyQueued @ 1409ed738; no NexusForever emit mapped yet
        ClientPublicEventVote           = 0x06EE,
        ServerPublicEventVoteInitiate   = 0x06F1,
        ServerPublicEventBombDropped    = 0x06F5,
        ServerPublicEventBombStatus     = 0x06F6,
        ServerPublicEventVoteAux        = 0x06F7, // 8-byte public-event vote cluster aux
        ServerPublicEventObjectiveStart = 0x06F9,
        ClientPublicEventRequestScoreboard = 0x06FA,
        ServerPublicEventVoteEnd        = 0x06FD,
        ServerPublicEventDetailedVoteInitiate = 0x06FE,
        ServerPublicEventVoteTally      = 0x06FF,
        ServerPublicEventTriggerUiUpdates = 0x0700,
        Client0x0701                    = 0x0701, // Network_RegisterServerOpcode_0351 @ 14006c290 registers 8-byte slot with writer Client0x0701_WritePayload @ 1400a69d0 (2-bit field + uint32); semantics unresolved
        ServerQueueFinish               = 0x0715,
        ServerQueueStatus               = 0x0717,
        ServerRaidQueueStatus            = 0x0718, // native 14008bf80 reads uint64 + 15-bit uint32 + uint64 + uint32 + uint32; registered object size 0x20 maps to 0x1A wire bytes
        ClientRaidInfoRequest           = 0x0719,
        ServerRaidInfoResponse          = 0x071A,
        ClientRandomRollRequest         = 0x071B,
        ServerRandomRollResponse        = 0x071C,
        ClientCinematicCameraSubjectPosVel = 0x071D,
        ClientCinematicCameraSubjectSpline = 0x071E,
        ClientCinematicCameraSubjectUnit = 0x071F,
        ClientCinematicState            = 0x0720,
        ClientCinematicWhiteOutFinished = 0x0721,
        ServerGenericFloaterLocalised   = 0x0723,
        ServerGenericFloaterString      = 0x0724,
        ServerGenericMapNode            = 0x0737,
        ServerGenericFloaterComplex     = 0x0738,
        ServerStoryTextCommunicator     = 0x073A,
        ServerStoryCommunicatorAux      = 0x074A, // 0x18-byte story communicator cluster aux
        ServerStoryTextUnit             = 0x0753,
        ClientGenericMapNodeChosen      = 0x0754,
        ServerUnitInUse                 = 0x0755,
        ServerCommunicatorMessage       = 0x0757,
        ServerGenericMapShow            = 0x0758,
        ServerStoryPanelHide            = 0x0759,
        ServerStoryPanelShow            = 0x075A,
        ServerStoryPanelCustomShow      = 0x075B,
        ServerStoryTextUnitYell         = 0x075C,
        ServerRealmFirstAchievement     = 0x075F,
        Client0x0760                    = 0x0760, // ClientWorldOpcodeRegister_MovementSpline @ 1400a8190 registers 0x58-byte slot with writer Client0x0760_WritePayload @ 1400abd30; row shape mirrors ServerRealmList realm entries; send/consumer event unresolved
        ServerRealmList                 = 0x0761,
        Client0x0762                    = 0x0762, // ClientWorldOpcodeRegister_MovementSpline @ 1400a8190 registers 0x10-byte slot with writer Client0x0762_WritePayload @ 1400ac410; row shape mirrors ServerRealmList message entries; send/consumer event unresolved
        ServerRealmMessages             = 0x0763,
        ServerRealmTransferResult       = 0x0765,
        ServerRecruitmentGuildsList     = 0x0767,
        ServerRecruitmentGuildDemands   = 0x0768,
        ServerRecruitmentGuildDescription = 0x0769,
        ServerRecruitmentGuildDetails   = 0x076A,
        ServerRecruitmentGuildsUpdate   = 0x076B,
        ServerRecruitmentGuildMinLevel  = 0x076C,
        ServerRecruitmentGuildsRecruiters = 0x076D,
        ClientRecruitmentGuildGetDetailedGuildInfo = 0x076E,
        ClientRecruitmentGuildSubscribe = 0x076F,
        ServerRecruitmentAuxFourUInt32  = 0x077E, // four uint32 fields; recruitment/pet boundary cluster
        ServerPetDespawned              = 0x077F,
        ClientCharacterRename           = 0x0786,
        ClientHousingCommunityRename    = 0x0788,
        ServerHousingCommunityRenameResult = 0x078C,
        ClientTitleSet                  = 0x078E,
        ClientDailyLoginClaimReward     = 0x078F, // FUN_1400070f0 sends zero-byte payload
        ClientAccountRedeemCoupon       = 0x0790, // wide-string coupon; wire/handler verified; native client sender still unlabeled
        ClientFortuneNotifyGame         = 0x0793,
        ClientLeaderboardPvpRequest     = 0x0799,
        ClientLeaderboardPveRequest     = 0x079A,
        ServerNewRealm                  = 0x07A1,
        ClientRealmList                 = 0x07A4,
        ClientReplayLevelUp             = 0x07A5, // replay-level request carrying the desired level
        ClientResetInstances            = 0x07B4,
        ClientAddonModuleList           = 0x07B6, // four uint32 header fields + uint32 row count + counted rows of { 4-bit nibble, bit, byte, wide string }; native sender FUN_1403f42e0 mirrors Lua_GetAddons module walk (skips Options/FrontEnd/ExternalTool); gameplay semantics unresolved
        ClientAccountItemReturnPendingItemGroup = 0x07C6,
        ServerRewardRotationEntryStateUpsert = 0x07C7, // inference: lowest delta opcode → add/upsert entry-state row
        ServerRewardRotationEntryStateArray  = 0x07C8,
        ServerRewardRotationEntryStateUpdate = 0x07C9, // inference: middle delta opcode → update entry-state row
        ServerRewardRotationScheduleArray    = 0x07CA,
        ServerRewardRotationEntryStateRemove = 0x07CB, // inference: highest delta opcode → remove entry-state row
        ClientRewardUpdateRequest       = 0x07CC,
        ServerRewardRotationContentContext = 0x07CD, // 0x28-byte payload; consumer semantics unresolved
        ClientGenericMapNodeRequest     = 0x07CF, // GenericMapNodeChoose sends missing node id before local GenericFloater
        ServerRewardRotationContentContextArray = 0x07D3, // count + count * 0x28-byte content-context rows
        ServerAuctionsByFilterAux       = 0x07D5, // 0x14-byte auctions-by-filter cluster aux
        ClientAuctionsByFilterRequest   = 0x07DC,
        ClientCharacterSelect           = 0x07DD,
        ClientCharacterList             = 0x07E0,
        Client0x07E3                    = 0x07E3, // native ClientWorldOpcodeRegister_MovementSpline 1400a8190 binds 0x07E3 to shared ClientTradeskillResetTalents_WritePayload 14007d010; current model stays one raw uint32 diagnostic field
        ServerDestinationArrowClear     = 0x07E4,
        ServerDestinationArrowSet       = 0x07E5,
        ClientEntityInteract            = 0x07EA,
        ClientPetCustomisation          = 0x07ED,
        ClientSelectRealm               = 0x07DF,
        ServerLootNotify                = 0x07F2,
        ServerSpellGo                   = 0x07F4,
        ServerSpellCastTargetUnit       = 0x07F5, // spell broadcast target unit triplet after 0x07F4/0x07FF
        ServerSpellEffectDamage         = 0x07F6, // spell effect damage payload with combat-result detail
        ServerSpellCastTargetUnit2      = 0x07F7, // second spell broadcast target unit triplet after 0x07F4/0x07FF
        ServerSpellEffectNestedTargets  = 0x07F8, // nested spell effect target-detail broadcast
        ServerSpellCastCancel           = 0x07F9, // live cast cancel notification
        ServerSpellCastTargetStatus     = 0x07FA, // spell cast target status triplet
        ServerSpellCastTargetReport     = 0x07FB, // spell cast target report list
        ServerSpellCastResult           = 0x07FC,
        ServerSpellCastPositionSync     = 0x07FD, // position and telegraph sync follow-up
        ServerSpellFinish               = 0x07FE,
        ServerSpellStart                = 0x07FF,
        ClientSpellStopCast             = 0x0801,
        ClientCancelEffect              = 0x0802,
        ServerCooldown                  = 0x0804,
        ServerSpellUInt32TripletList    = 0x080F, // count + uint32 triplet rows; semantics unresolved
        ServerSpellUInt32TripletListVariant = 0x0810, // shares 0x080F reader; semantics unresolved
        ServerSpellCastTargetList       = 0x0811, // spell broadcast casting-id target list
        ServerSpellFourUInt32           = 0x0812, // four uint32 fields; semantics unresolved
        ServerSpellBuffRemove           = 0x0813,
        ServerSpellThresholdClear       = 0x0814, // threshold-family Spell4 id plus trailing packed value; raw PE table maps 0x0814 to dispatcher 1403ef384, distinct from the single-Spell4 clear follow-up at 0x0815
        ServerSpellThresholdSpell4      = 0x0815, // single Spell4 id threshold-clear follow-up; dispatch 1403ef372 -> SpellThreshold_HandleClear @ 1403bed60
        ServerSpellThresholdStart       = 0x0816, // three Spell4 ids plus casting id; dispatch 1403ef34e -> SpellThreshold_HandleStartWrapper @ 1403be940
        ServerSpellThresholdUpdate      = 0x0817, // Spell4 id plus threshold stage byte; dispatch 1403ef360 -> SpellThreshold_HandleUpdate @ 1403bea90
        ServerSpellWrapperTierEntry     = 0x0818, // spell-wrapper id plus nested entity tier-entry; dispatch 1403ee403 -> SpellService_LookupSpellWrapperByWrapperId @ 140561c30 -> SpellWrapper_ApplyEntityVariantTierEntryAndBroadcast @ 14053f710, updating wrapper-local node, buff, and visual-group state
        ServerSpellWrapperNodeRemove    = 0x0819, // payload model [entityId, spellWrapperId]; dispatch 1403ee3af -> SpellWrapperNode_PruneChildrenAndRefresh @ 140718af0, pruning child nodes and recomputing the remaining buff window
        ClientSpline2NodeData           = 0x081A, // client Spline2 node data with counted 10-uint records
        ClientSpline2NodePositionData   = 0x081B, // client Spline2 node position data with counted uint payload
        ClientSpline2DataRequest        = 0x081C, // client Spline2 id request
        ClientSpline2Request            = 0x081D, // periodic stale Spline2 id request
        ClientSteamAchievements         = 0x0823,
        ClientStorefrontPurchaseAccount = 0x0828,
        ClientStorefrontPurchaseCharacter = 0x082A,
        ClientStorefrontRequestCatalog  = 0x082D,
        ClientStorefrontPurchaseVirtualCurrencyPackage = 0x082E,
        ClientSummonVanityPet           = 0x082F,
        ClientReportBug                 = 0x0830,
        ClientStuck                     = 0x0831,
        ClientSuggest                   = 0x0833,
        ClientAccountItemTake           = 0x0839,
        ServerLoadingScreen             = 0x083C,
        ServerTimeOfDay                 = 0x0845,
        ServerTimeOfDayAuxUInt32        = 0x0846, // 4-byte time-of-day cluster aux
        ServerMapTrackedUnitDisable     = 0x0848,
        ServerMapTrackedUnitUpdate      = 0x0849,
        ClientCraftingAdditive          = 0x084A,
        ServerCraftingAuxFourUInt32FloatUInt32 = 0x084B, // uint32,uint32,uint32,uint32,float,uint32; reader 1400a3af0
        ServerProfessionModifiers       = 0x084C,
        ClientCraftingAbandon           = 0x084D,
        ClientTradeskillPickTalent      = 0x084E,
        ClientCraftingComplexCraft      = 0x084F,
        ClientCraftingSimpleCraft       = 0x0850,
        ClientCraftingCraftItem         = 0x0851,
        ClientCraftingCraftItemAutoCraft = 0x0852,
        ServerCraftingFinish            = 0x0853,
        ServerCraftingCurrentCraft      = 0x0854, // reader ServerCraftingCurrentCraft_ReadPayload 1400a46b0; crafting current schematic/stats/discovery payload
        ServerCraftingAuxUInt32AndTwoFloats = 0x0855, // uint32,float,float; reader 140081df0
        ServerProfessionsLoad           = 0x0856,
        ClientTradeskillLearn           = 0x0857,
        ClientTradeskillResetTalents    = 0x0858, // native sender Tradeskill_SendClientTradeskillResetTalents 14059acb0 sends 0x0858 through shared ClientTradeskillResetTalents_WritePayload 14007d010; current model reads one 32-bit tradeskill id
        ClientCraftingRuneSlotAdd       = 0x0859,
        ClientCraftingRuneSlotClear     = 0x085A,
        ClientCraftingRuneInstall       = 0x085B,
        ClientCraftingRuneSlotReroll    = 0x085C,
        ServerTradeskillSigilResult     = 0x085D,
        ServerSchematicRemoveLearned    = 0x085E,
        ServerSchematicAddLearned       = 0x085F,
        ServerProfessionUpdate          = 0x0860,
        ServerTradeskillRelearnCooldown = 0x0861,
        ServerTransferDestinationRealmList = 0x0862,
        ServerVehiclePassengerAdd       = 0x086F,
        ServerEntityAggroSwitch         = 0x0876,
        ServerEntityCCStateSet          = 0x087F,
        ServerEntityCCStateRemove       = 0x0880,
        ServerEntityCCTetherUnit        = 0x0881,
        ServerReputationOverrideRemove  = 0x0885,
        ServerEntityStatUInt32Triplet   = 0x0889, // three uint32 fields; shares threat-update reader shape
        ServerEntityDeathState          = 0x088C,
        ServerDuelCountdown             = 0x0893,
        ServerDuelResult                = 0x0894,
        ServerDuelStart                 = 0x0895,
        ServerDuelChallenge             = 0x0896,
        ServerUnitEnteredCombat         = 0x089A,
        ServerVehiclePassengerSelf      = 0x089B, // local player vehicle/seat assignment
        ServerLootCanLoot               = 0x089F,
        ServerLootItemUpdate            = 0x08A0,
        ServerLootRemove                = 0x08A1, 
        ServerLootRoll                  = 0x08A2,
        ServerLootWinner                = 0x08A3,
        ServerLootGrant                 = 0x08A5,
        ServerLootNotification          = 0x08A6,
        ServerEntityVisualInfoUpdate    = 0x08A8, // compact Creature2/display update; flag meanings unresolved
        ServerPathScientistAddCreatureInfoToCreature = 0x08B2,
        ServerPathScientistUnitScanParameters = 0x08B3,
        ServerPathScientistAddSpecimenSurveyToCreature = 0x08B4,
        ServerPathScientistAddFieldStudyToCreature = 0x08B5,
        ServerPathSettlerAddImprovementInfoToUnit = 0x08B6,
        ServerPathSettlerHubUpdate      = 0x08B7,
        ServerSetUnitPathType           = 0x08B8,
        ServerPublicEventUnitAdd        = 0x08BB,
        ServerPublicEventUnitUpdate     = 0x08BC,
        ServerUnitPvpStateChange        = 0x08BD,
        ServerVehiclePassengerRemove    = 0x08C7,
        ServerEntityStatUInt32WideString = 0x08CC, // uint32 + wide string; reader 1400980f0
        ServerUnitSetChair              = 0x08CF,
        ServerReputationOverrideAdd     = 0x08D7,
        ServerEntityStatUInt32UInt5UInt32 = 0x08F4, // uint32 + 5-bit + uint32; reader 140097620
        ServerEntityVisualUpdate        = 0x0905,
        ServerEntityTargetUnit          = 0x0908,
        ServerEntityThreatListUpdate    = 0x0909,
        ServerEntityThreatUpdate        = 0x090A,
        ServerVendorItemsUpdated        = 0x090B,
        ClientCostumeItemUnlock         = 0x090F,
        ServerSpellAbilityCharges       = 0x0914,
        ServerEntitlement               = 0x0918,
        ServerCombatReward              = 0x0919,
        ServerCooldownList              = 0x091B,
        Client0x0928                    = 0x0928, // ClientWorldOpcodeRegister_MovementSpline @ 1400a8190 registers 8-byte slot with writer Client0x0928_WritePayload @ 1400898b0 (uint32 + 5-bit field); semantics unresolved
        ServerRewardPropertySet         = 0x092C,
        ServerPlayerHealthUpdate        = 0x092F,
        ServerEntityBoneUpdate          = 0x0931,
        ServerItemVisualUpdate          = 0x0933,
        ServerEntityFaction             = 0x0934,
        ServerEntityStatUpdateFloat     = 0x0935,
        ServerEntityGroupAssociation    = 0x0936,
        ServerEntityHealthUpdate        = 0x0937,
        ServerEntityStatUpdateInteger   = 0x0938,
        ServerEntityStatUInt32UInt14UInt18WideString = 0x0939, // reader 140097ee0
        ServerEntityPropertiesUpdate    = 0x093A,
        ServerUnitUpdateObjectiveIndex  = 0x093B,
        ServerEmote                     = 0x093C,
        ServerEntityStatUInt32UInt5Pair = 0x093D, // uint32 + 5-bit + two uint32; reader 140097690
        ServerEntityStatTwoUInt32UInt64 = 0x093E, // two uint32 + uint64; reader 140097f70
        ClientItemUse                   = 0x0943,
        ClientCastGuildBossToken        = 0x094F,
        ServerWarPartyBossTokens        = 0x0951,
        ServerWarPartyMatchResults      = 0x0954,
        ClientWarPartyBossTokensRequest = 0x0956,
        ServerWarPlotPlugState          = 0x0958,
        ClientWhoRequest                = 0x0959,
        ServerWhoResponse               = 0x095A,
        ServerMapUpdateHexGroup         = 0x0965,
        ServerAccountCurrencySet        = 0x0966,
        ServerAccountCurrencyGrant      = 0x0967,
        ServerAccountEntitlements       = 0x0968,
        ServerAccountItemCooldowns     = 0x0969,
        ServerAccountItemCacheAdd      = 0x096A, // leading uint32 unused by consumer (emit 0)
        ServerAccountItemCacheListAppend = 0x096B, // leading uint32 unused by consumer (emit 0)
        ServerAccountItemCacheRemove   = 0x096C, // leading uint32 unused by consumer (emit 0)
        ServerAccountItems              = 0x096D,
        ServerDailyLoginUpdate         = 0x096E,
        ServerAccountOperationResult    = 0x0970,
        ServerAccountPrivilegeRestrictionUpdate = 0x0971,
        ServerSupportTicketResult       = 0x0972,
        ServerAccountEntitlement        = 0x0973,
        ServerAccountItemCooldownSet    = 0x0974,
        ServerAccountItemAdd            = 0x0975,
        ServerAccountPendingItemAdd    = 0x0976,
        ServerAccountPendingItemsClear = 0x0977,
        ServerCREDDOperationHistory    = 0x0978,
        ServerAccountItemsPending       = 0x0979,
        ServerCREDDExchangeOrderCacheRows = 0x097A, // internal cache rows; OrderId/CreditAmount/SideFlag mapped; no client event
        ServerCREDDRedeemResult        = 0x097B,
        ServerAccountItemDelete         = 0x097C,
        ServerAccountPendingItemGroupDelete = 0x097D,
        ServerAccountPendingItemDelete = 0x097E,
        ServerAccountTier               = 0x097F,
        ServerWalletUpdate              = 0x0980,
        ServerGenericUnlockAccountList  = 0x0981,
        ServerGenericUnlockAccount      = 0x0982,
        ServerGenericUnlockCharacterList = 0x0983,
        ServerGenericUnlockCharacterRefresh = 0x0984,
        ServerGenericUnlockResult       = 0x0985,
        ServerAccountUInt64Payload     = 0x0986, // uint64; no mapped client consumer — do not emit live
        ServerStoreFinalise             = 0x0987,
        ServerStoreCategories           = 0x0988,
        ServerStoreCatalogUpdated      = 0x0989,
        ServerStoreError               = 0x098A,
        ServerStoreOffers               = 0x098B,
        ServerStorePurchaseOfferResult = 0x098C, // character purchase success (client 0x082A @ 140450720)
        ServerStorePurchaseOfferResultVariant = 0x098D, // account purchase success (client 0x0828 @ 1404507e0)
        ServerStorePurchaseHistoryReady = 0x098E,
        ServerStoreCurrencyPackageRow  = 0x098F, // store currency-package shape; no client event — catalog uses 0x0988
        ServerStoreCompleteOrderVirtualCurrencyPackageResult = 0x0990,
        ServerStorePurchaseVirtualCurrencyPackageResult = 0x0991,
    }
}
