#!/usr/bin/env python3
"""
Export promoted DataMapping runtime rows as a standalone world-database SQL seed.

This is for fresh machines that should be able to import reviewed runtime data
from checked-in SQL without rebuilding Jabbithole/WildStar mapping outputs.
The normal output is data-only; EF migrations own the runtime schema.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path
from typing import Optional, Sequence


DEFAULT_MYSQL = r"C:\Program Files\MySQL\MySQL Server 8.0\bin\mysql.exe"
ENTITY_ID_BASE = 1_000_000_000
ENTITY_ID_MAX = 1_999_999_999
LAUGHINGWS_ENTITY_ID_RANGES = [
    (1_100_000_000, 1_100_099_999),
    (1_100_100_000, 1_100_199_999),
    (1_100_200_000, 1_100_299_999),
    (1_100_300_000, 1_100_399_999),
    (2_000_000_000, 2_099_999_999),
    (2_100_000_000, 2_147_483_647),
]
REVIEWED_WORLD_ENTITY_IDS = [
    1_000_003_084,
    1_000_009_115,
    1_000_107_802,
    1_000_285_998,
    1_000_415_265,
    1_005_221_261,
    1_006_129_819,
    1_006_132_630,
    1_006_289_549,
    1_006_289_665,
]
CUSTOM_TABLES = [
    "creature_loot",
    "loot_group",
    "entity_loot",
    "item_loot",
    "loot_item",
    "item_salvage",
    "creature_info_property",
    "creature_info_stat",
]
REQUIRED_RUNTIME_TABLES = [
    "entity",
    "entity_event",
    "entity_property",
    "entity_script",
    "entity_spline",
    "entity_stats",
    "entity_vendor",
    "entity_vendor_category",
    "entity_vendor_item",
    *CUSTOM_TABLES,
]


def mysql_command(args: argparse.Namespace, extra: Optional[Sequence[str]] = None) -> list[str]:
    command = [
        str(args.mysql_exe),
        f"--host={args.host}",
        f"--port={args.port}",
        f"--user={args.user}",
        f"--password={args.password}",
        "--default-character-set=utf8mb4",
        "--batch",
        "--raw",
        "--skip-column-names",
    ]
    if extra:
        command.extend(extra)
    return command


def mysqldump_command(args: argparse.Namespace, table: str, where: str) -> list[str]:
    return [
        str(args.mysqldump_exe),
        f"--host={args.host}",
        f"--port={args.port}",
        f"--user={args.user}",
        f"--password={args.password}",
        "--default-character-set=utf8mb4",
        "--single-transaction",
        "--quick",
        "--skip-comments",
        "--compact",
        "--skip-add-locks",
        "--skip-disable-keys",
        "--no-create-info",
        "--complete-insert",
        "--extended-insert",
        "--hex-blob",
        f"--where={where}",
        args.world_db,
        table,
    ]


def run_text(command: Sequence[str], *, input_text: Optional[str] = None) -> str:
    result = subprocess.run(
        command,
        input=input_text,
        text=True,
        encoding="utf-8",
        errors="replace",
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip() or f"{command[0]} exited with {result.returncode}")
    if result.stderr.strip():
        print(result.stderr.strip(), file=sys.stderr)
    return result.stdout


def sql_string(value: str) -> str:
    return "'" + value.replace("\\", "\\\\").replace("'", "''") + "'"


def mysql_scalar_list(args: argparse.Namespace, query: str) -> list[str]:
    output = run_text(mysql_command(args, [args.world_db, "-e", query]))
    return [line.strip() for line in output.splitlines() if line.strip()]


def comma_ids(ids: Sequence[str]) -> str:
    if not ids:
        return "0"
    return ",".join(ids)


def exclude_laughingws_ranges_sql(column: str) -> str:
    return " AND ".join(
        f"NOT ({column} BETWEEN {start} AND {end})"
        for start, end in LAUGHINGWS_ENTITY_ID_RANGES
    )


def primary_entity_range_sql(column: str) -> str:
    return (
        f"{column} BETWEEN {ENTITY_ID_BASE} AND {ENTITY_ID_MAX}"
        f" AND {exclude_laughingws_ranges_sql(column)}"
    )


def write_header(handle, args: argparse.Namespace) -> None:
    handle.write("-- Promoted NexusForever DataMapping runtime world seed.\n")
    handle.write("-- Generated by Tools/DataMapping/export_runtime_world_seed.py.\n")
    handle.write("-- This file is import-only and does not require nf_map_*, jabbithole, or wildstar_client tables.\n\n")
    handle.write(f"USE `{args.world_db}`;\n\n")
    handle.write("SET @NF_OLD_FOREIGN_KEY_CHECKS := @@FOREIGN_KEY_CHECKS;\n")
    handle.write("SET FOREIGN_KEY_CHECKS = 0;\n\n")
    write_required_table_check(handle)
    handle.write("START TRANSACTION;\n")


def write_required_table_check(handle) -> None:
    values = ",\n  ".join(f"('{table_name}')" for table_name in sorted(REQUIRED_RUNTIME_TABLES))
    handle.write(
        f"""
DROP TEMPORARY TABLE IF EXISTS tmp_nf_required_runtime_tables;
CREATE TEMPORARY TABLE tmp_nf_required_runtime_tables (
  table_name VARCHAR(128) NOT NULL PRIMARY KEY
) ENGINE=Memory;

INSERT INTO tmp_nf_required_runtime_tables (table_name) VALUES
  {values};

SET @nf_missing_runtime_tables := (
  SELECT GROUP_CONCAT(r.table_name ORDER BY r.table_name SEPARATOR ', ')
  FROM tmp_nf_required_runtime_tables r
  LEFT JOIN information_schema.tables t
    ON t.table_schema = DATABASE()
   AND t.table_name = r.table_name
  WHERE t.table_name IS NULL
);
SET @nf_missing_runtime_tables_sql := IF(
  @nf_missing_runtime_tables IS NULL,
  'DO 0',
  CONCAT('SIGNAL SQLSTATE ''45000'' SET MESSAGE_TEXT = ', QUOTE(LEFT(CONCAT('Missing runtime table(s). Run EF migrations first: ', @nf_missing_runtime_tables), 128)))
);
PREPARE nfMissingRuntimeTablesStatement FROM @nf_missing_runtime_tables_sql;
EXECUTE nfMissingRuntimeTablesStatement;
DEALLOCATE PREPARE nfMissingRuntimeTablesStatement;

""".lstrip()
    )


def write_cleanup(handle, vendor_ids: Sequence[str]) -> None:
    vendor_id_list = comma_ids(vendor_ids)
    primary_entity_filter = primary_entity_range_sql("id")
    handle.write(
        f"""
DELETE FROM entity_loot
WHERE comment LIKE 'DataMapping %'
   OR ({primary_entity_filter});

DELETE FROM item_loot
WHERE comment LIKE 'DataMapping %';

DELETE li
FROM loot_item li
JOIN loot_group lg ON lg.id = li.id
WHERE lg.comment LIKE 'DataMapping %';

DELETE FROM loot_group
WHERE comment LIKE 'DataMapping %';

DELETE FROM item_salvage
WHERE comment LIKE 'DataMapping %';

DELETE FROM creature_loot;

DELETE FROM entity_stats
WHERE {primary_entity_filter};

DELETE FROM entity
WHERE {primary_entity_filter};

DELETE FROM entity_vendor_item
WHERE id IN ({vendor_id_list});

DELETE FROM entity_vendor_category
WHERE id IN ({vendor_id_list});

DELETE FROM entity_vendor
WHERE id IN ({vendor_id_list});

DELETE FROM creature_info_property
WHERE `property` IN (7, 41);

DELETE FROM creature_info_stat
WHERE `stat` IN (21);

-- Rider's Reef tutorial combat cleanup promoted from the reviewed import.
DELETE FROM entity
WHERE world = 3460
  AND creature = 73665;

UPDATE entity
SET type = 0,
    faction1 = CASE creature
        WHEN 73494 THEN 1441
        WHEN 74862 THEN 1442
        ELSE faction1
    END,
    faction2 = CASE creature
        WHEN 73494 THEN 1441
        WHEN 74862 THEN 1442
        ELSE faction2
    END
WHERE world = 3460
  AND creature IN (73494, 74862);

-- Northern Wilds Deadeye Brightland Q3479/Q3480 static quest-giver correction.
-- Retail video proof shows the dialog NPC at WorldLocation2 7726 standing still;
-- reject the generated/official spline 2900 attachment when it is present.
DELETE es
FROM entity_spline es
JOIN entity e ON e.id = es.id
WHERE e.world = 426
  AND e.area = 596
  AND e.creature = 11063
  AND ABS(e.x - 4185.583) < 5.0
  AND ABS(e.y - (-722.691)) < 5.0
  AND ABS(e.z - (-5695.496)) < 5.0;

-- Northern Wilds avalanche static row cleanup.
-- Creature2 15615 rows are imported visible static chute/runout markers and
-- Creature2 67662 rows are legacy caster markers. The moving avalanche hazards
-- are script-owned fallbacks that loop downhill from their source.
DELETE es
FROM entity_spline es
JOIN entity e ON e.id = es.id
WHERE e.world = 426
  AND e.creature IN (15615, 67662);

DELETE ep
FROM entity_property ep
JOIN entity e ON e.id = ep.id
WHERE e.world = 426
  AND e.creature IN (15615, 67662);

DELETE ev
FROM entity_event ev
JOIN entity e ON e.id = ev.id
WHERE e.world = 426
  AND e.creature IN (15615, 67662);

DELETE esc
FROM entity_script esc
JOIN entity e ON e.id = esc.id
WHERE e.world = 426
  AND e.creature IN (15615, 67662);

DELETE est
FROM entity_stats est
JOIN entity e ON e.id = est.id
WHERE e.world = 426
  AND e.creature IN (15615, 67662);

DELETE el
FROM entity_loot el
JOIN entity e ON e.id = el.id
WHERE e.world = 426
  AND e.creature IN (15615, 67662);

DELETE evi
FROM entity_vendor_item evi
JOIN entity e ON e.id = evi.id
WHERE e.world = 426
  AND e.creature IN (15615, 67662);

DELETE evc
FROM entity_vendor_category evc
JOIN entity e ON e.id = evc.id
WHERE e.world = 426
  AND e.creature IN (15615, 67662);

DELETE evn
FROM entity_vendor evn
JOIN entity e ON e.id = evn.id
WHERE e.world = 426
  AND e.creature IN (15615, 67662);

DELETE FROM entity
WHERE world = 426
  AND creature IN (15615, 67662);

-- Official world visible duplicate cleanup promoted from duplicate audit.
DELETE es
FROM entity_spline es
JOIN entity e ON e.id = es.id
WHERE
  (e.id = 47922 AND e.world = 3404 AND e.creature = 71468 AND e.area = 4826 AND ABS(e.x - (-72.8101)) < 0.001 AND ABS(e.y - (-844.8)) < 0.001 AND ABS(e.z - 7.84299) < 0.001)
  OR (e.id = 47937 AND e.world = 3404 AND e.creature = 71628 AND e.area = 1622 AND ABS(e.x - 37.2705) < 0.001 AND ABS(e.y - (-840.065)) < 0.001 AND ABS(e.z - 173.363) < 0.001)
  OR (e.id = 29208 AND e.world = 3460 AND e.creature = 73690 AND e.area = 5969 AND ABS(e.x - 1290.97) < 0.001 AND ABS(e.y - (-495.031)) < 0.001 AND ABS(e.z - 354.958) < 0.001)
  OR (e.id = 29209 AND e.world = 3460 AND e.creature = 73690 AND e.area = 5969 AND ABS(e.x - 1294.33) < 0.001 AND ABS(e.y - (-495.328)) < 0.001 AND ABS(e.z - 337.609) < 0.001);

DELETE ep
FROM entity_property ep
JOIN entity e ON e.id = ep.id
WHERE
  (e.id = 47922 AND e.world = 3404 AND e.creature = 71468 AND e.area = 4826 AND ABS(e.x - (-72.8101)) < 0.001 AND ABS(e.y - (-844.8)) < 0.001 AND ABS(e.z - 7.84299) < 0.001)
  OR (e.id = 47937 AND e.world = 3404 AND e.creature = 71628 AND e.area = 1622 AND ABS(e.x - 37.2705) < 0.001 AND ABS(e.y - (-840.065)) < 0.001 AND ABS(e.z - 173.363) < 0.001)
  OR (e.id = 29208 AND e.world = 3460 AND e.creature = 73690 AND e.area = 5969 AND ABS(e.x - 1290.97) < 0.001 AND ABS(e.y - (-495.031)) < 0.001 AND ABS(e.z - 354.958) < 0.001)
  OR (e.id = 29209 AND e.world = 3460 AND e.creature = 73690 AND e.area = 5969 AND ABS(e.x - 1294.33) < 0.001 AND ABS(e.y - (-495.328)) < 0.001 AND ABS(e.z - 337.609) < 0.001);

DELETE ev
FROM entity_event ev
JOIN entity e ON e.id = ev.id
WHERE
  (e.id = 47922 AND e.world = 3404 AND e.creature = 71468 AND e.area = 4826 AND ABS(e.x - (-72.8101)) < 0.001 AND ABS(e.y - (-844.8)) < 0.001 AND ABS(e.z - 7.84299) < 0.001)
  OR (e.id = 47937 AND e.world = 3404 AND e.creature = 71628 AND e.area = 1622 AND ABS(e.x - 37.2705) < 0.001 AND ABS(e.y - (-840.065)) < 0.001 AND ABS(e.z - 173.363) < 0.001)
  OR (e.id = 29208 AND e.world = 3460 AND e.creature = 73690 AND e.area = 5969 AND ABS(e.x - 1290.97) < 0.001 AND ABS(e.y - (-495.031)) < 0.001 AND ABS(e.z - 354.958) < 0.001)
  OR (e.id = 29209 AND e.world = 3460 AND e.creature = 73690 AND e.area = 5969 AND ABS(e.x - 1294.33) < 0.001 AND ABS(e.y - (-495.328)) < 0.001 AND ABS(e.z - 337.609) < 0.001);

DELETE est
FROM entity_stats est
JOIN entity e ON e.id = est.id
WHERE
  (e.id = 47922 AND e.world = 3404 AND e.creature = 71468 AND e.area = 4826 AND ABS(e.x - (-72.8101)) < 0.001 AND ABS(e.y - (-844.8)) < 0.001 AND ABS(e.z - 7.84299) < 0.001)
  OR (e.id = 47937 AND e.world = 3404 AND e.creature = 71628 AND e.area = 1622 AND ABS(e.x - 37.2705) < 0.001 AND ABS(e.y - (-840.065)) < 0.001 AND ABS(e.z - 173.363) < 0.001)
  OR (e.id = 29208 AND e.world = 3460 AND e.creature = 73690 AND e.area = 5969 AND ABS(e.x - 1290.97) < 0.001 AND ABS(e.y - (-495.031)) < 0.001 AND ABS(e.z - 354.958) < 0.001)
  OR (e.id = 29209 AND e.world = 3460 AND e.creature = 73690 AND e.area = 5969 AND ABS(e.x - 1294.33) < 0.001 AND ABS(e.y - (-495.328)) < 0.001 AND ABS(e.z - 337.609) < 0.001);

DELETE FROM entity
WHERE
  (id = 47922 AND world = 3404 AND creature = 71468 AND area = 4826 AND ABS(x - (-72.8101)) < 0.001 AND ABS(y - (-844.8)) < 0.001 AND ABS(z - 7.84299) < 0.001)
  OR (id = 47937 AND world = 3404 AND creature = 71628 AND area = 1622 AND ABS(x - 37.2705) < 0.001 AND ABS(y - (-840.065)) < 0.001 AND ABS(z - 173.363) < 0.001)
  OR (id = 29208 AND world = 3460 AND creature = 73690 AND area = 5969 AND ABS(x - 1290.97) < 0.001 AND ABS(y - (-495.031)) < 0.001 AND ABS(z - 354.958) < 0.001)
  OR (id = 29209 AND world = 3460 AND creature = 73690 AND area = 5969 AND ABS(x - 1294.33) < 0.001 AND ABS(y - (-495.328)) < 0.001 AND ABS(z - 337.609) < 0.001);
""".lstrip()
    )


def dump_table(args: argparse.Namespace, table: str, where: str) -> str:
    output = run_text(mysqldump_command(args, table, where))
    return "\n".join(line for line in output.splitlines() if line and not line.startswith("/*!")) + "\n"


def write_data(handle, args: argparse.Namespace) -> None:
    primary_entity_filter = primary_entity_range_sql("id")
    non_laughingws_filter = exclude_laughingws_ranges_sql("id")
    reviewed_entity_ids = comma_ids([str(entity_id) for entity_id in REVIEWED_WORLD_ENTITY_IDS])
    table_filters = [
        ("entity", f"{primary_entity_filter} AND id NOT IN ({reviewed_entity_ids})"),
        ("entity_stats", f"{primary_entity_filter} AND id NOT IN ({reviewed_entity_ids})"),
        ("entity_vendor", non_laughingws_filter),
        ("entity_vendor_category", non_laughingws_filter),
        ("entity_vendor_item", non_laughingws_filter),
        ("creature_loot", "1=1"),
        ("loot_group", "comment LIKE 'DataMapping %'"),
        ("entity_loot", f"comment LIKE 'DataMapping %' OR ({primary_entity_filter})"),
        ("item_loot", "comment LIKE 'DataMapping %'"),
        ("loot_item", "id IN (SELECT id FROM loot_group WHERE comment LIKE 'DataMapping %')"),
        ("item_salvage", "comment LIKE 'DataMapping %'"),
        ("creature_info_property", "`property` IN (7, 41)"),
        ("creature_info_stat", "`stat` IN (21)"),
    ]
    for table, where in table_filters:
        handle.write(f"\n-- Data for `{table}`.\n")
        handle.write(dump_table(args, table, where))
        if table == "entity":
            write_reviewed_world_entity_rows(handle)


def write_reviewed_world_entity_rows(handle) -> None:
    handle.write(
        """
-- Reviewed Ruins of Kel Voreth exit-portal placement.
-- InstancePortal 42 / Jabbithole creature 1961 / source coordinate 9115
-- maps uniquely to Creature2 40771. Placement/model availability only;
-- exit interaction and destination behavior remain blocked pending client smoke.
INSERT INTO `entity` (`id`, `type`, `creature`, `world`, `area`, `x`, `y`, `z`, `rx`, `ry`, `rz`, `displayInfo`, `outfitInfo`, `faction1`, `faction2`, `questChecklistIdx`, `activePropId`, `worldSocketId`, `mode`) VALUES
  (1000009115,14,40771,1336,1661,-15,-737,1007,0,0,0,26914,0,219,219,0,0,0,0);

-- Reviewed Ultimate Protogames exit-portal placement.
-- InstancePortal 152 / Jabbithole creature 28307 / source coordinate 6132630
-- maps uniquely to Creature2 67513. Placement/model availability only;
-- exit interaction and destination behavior remain blocked pending client smoke.
INSERT INTO `entity` (`id`, `type`, `creature`, `world`, `area`, `x`, `y`, `z`, `rx`, `ry`, `rz`, `displayInfo`, `outfitInfo`, `faction1`, `faction2`, `questChecklistIdx`, `activePropId`, `worldSocketId`, `mode`) VALUES
  (1006132630,14,67513,2980,4376,-12512,-788,-6877,0,0,0,29666,0,219,219,0,0,0,0);

-- Jabbithole/DataMapping records explicit zero interrupt armour for this row.
INSERT INTO `entity_stats` (`id`, `stat`, `value`) VALUES
  (1006132630,21,0);

-- Reviewed Ultimate Protogames Tea Time achievement placement.
-- Jabbithole creature 29894 / source coordinate 6289549 maps uniquely to
-- Creature2 69876 Wiggle Wellingsworth. Adjacent Jabbithole creature 29896 /
-- source coordinate 6289665 is reviewed to Creature2 69883 because that exact
-- build-16042 [UP] Tea Cup row owns activate spell 79328, prerequisite 37093,
-- and AchievementAdvance effect 208728 for achievement 5881; same-name
-- Creature2 56874 is a Grimvault flavor NPC without an activate spell.
-- Placement and table-backed activation are evidence-backed; persistence,
-- relog notification, and full client smoke remain blocked.
INSERT INTO `entity` (`id`, `type`, `creature`, `world`, `area`, `x`, `y`, `z`, `rx`, `ry`, `rz`, `displayInfo`, `outfitInfo`, `faction1`, `faction2`, `questChecklistIdx`, `activePropId`, `worldSocketId`, `mode`) VALUES
  (1006289549,0,69876,2980,4337,-28714,-25,-2788,0,0,0,21631,0,219,219,0,0,0,0),
  (1006289665,10,69883,2980,4337,-28715,-25,-2788,0,0,0,28132,0,219,219,0,0,0,0);

-- Jabbithole/DataMapping records exact Wiggle health/level and explicit zero
-- shield/interrupt armour; the Tea Cup records zero interrupt armour.
INSERT INTO `entity_stats` (`id`, `stat`, `value`) VALUES
  (1006289549,0,101),
  (1006289549,10,1),
  (1006289549,20,0),
  (1006289549,21,0),
  (1006289665,21,0);

-- Reviewed Stormtalon's Lair exit-portal placement.
-- InstancePortal 41 / Jabbithole creature 788 / source coordinate 3084
-- maps uniquely to Creature2 40770. Placement/model availability only;
-- exit interaction and destination behavior remain blocked pending client smoke.
INSERT INTO `entity` (`id`, `type`, `creature`, `world`, `area`, `x`, `y`, `z`, `rx`, `ry`, `rz`, `displayInfo`, `outfitInfo`, `faction1`, `faction2`, `questChecklistIdx`, `activePropId`, `worldSocketId`, `mode`) VALUES
  (1000003084,14,40770,382,271,10,-9,237,0,0,0,26914,0,219,219,0,0,0,0);

-- Jabbithole/DataMapping records explicit zero interrupt armour for this row.
INSERT INTO `entity_stats` (`id`, `stat`, `value`) VALUES
  (1000003084,21,0);

-- Reviewed Sanctuary of the Swordmaiden current exit-portal placement.
-- InstancePortal 53 / Jabbithole creature 6860 / source coordinate 5221261
-- maps uniquely to Creature2 41148 and is current-last-seen 7. Placement/model
-- availability only; source coordinate 54254 is older-last-seen 4 and is not
-- promoted. Exit interaction and destination behavior remain blocked.
INSERT INTO `entity` (`id`, `type`, `creature`, `world`, `area`, `x`, `y`, `z`, `rx`, `ry`, `rz`, `displayInfo`, `outfitInfo`, `faction1`, `faction2`, `questChecklistIdx`, `activePropId`, `worldSocketId`, `mode`) VALUES
  (1005221261,14,41148,1271,2260,4244,-774,-3252,0,0,0,26914,0,219,219,0,0,0,0);

-- Jabbithole/DataMapping records explicit zero interrupt armour for this row.
INSERT INTO `entity_stats` (`id`, `stat`, `value`) VALUES
  (1005221261,21,0);

-- Reviewed Fragment Zero transport-portal placement.
-- InstancePortal 185 / Jabbithole creature 28122 / source coordinate 6129819
-- maps uniquely to Creature2 69013 and is current-last-seen 7.
-- Placement/model availability only; transport destination and return behavior
-- remain blocked pending client smoke.
INSERT INTO `entity` (`id`, `type`, `creature`, `world`, `area`, `x`, `y`, `z`, `rx`, `ry`, `rz`, `displayInfo`, `outfitInfo`, `faction1`, `faction2`, `questChecklistIdx`, `activePropId`, `worldSocketId`, `mode`) VALUES
  (1006129819,14,69013,3180,4619,9861,-760,-5810,0,0,0,22991,0,219,219,0,0,0,0);

-- Jabbithole/DataMapping records explicit zero interrupt armour for this row.
INSERT INTO `entity_stats` (`id`, `stat`, `value`) VALUES
  (1006129819,21,0);

-- Reviewed Skullcano exit-portal placements.
-- InstancePortal 27 / Jabbithole creature 12396 maps to Creature2 32419
-- because the competing exact-name Creature2 40772 links to InstancePortal 43.
-- Both source coordinates 285998 and 415265 are distinct current-last-seen 7
-- placements in world 1263 / area 1220. Placement/model availability only;
-- exit interaction and destination behavior remain blocked pending client smoke.
INSERT INTO `entity` (`id`, `type`, `creature`, `world`, `area`, `x`, `y`, `z`, `rx`, `ry`, `rz`, `displayInfo`, `outfitInfo`, `faction1`, `faction2`, `questChecklistIdx`, `activePropId`, `worldSocketId`, `mode`) VALUES
  (1000285998,14,32419,1263,1220,674,-1002,-88,0,0,0,22402,0,219,219,0,0,0,0),
  (1000415265,14,32419,1263,1220,-699,-692,-413,0,0,0,22402,0,219,219,0,0,0,0);

-- Jabbithole/DataMapping records explicit zero interrupt armour for both rows.
INSERT INTO `entity_stats` (`id`, `stat`, `value`) VALUES
  (1000285998,21,0),
  (1000415265,21,0);

-- Reviewed Gauntlet exit-portal placement.
-- InstancePortal 71 / Jabbithole creature 9475 / source coordinate 107802
-- maps uniquely to Creature2 48933 and is current-last-seen 7 in the Safe Zone.
-- The separate InstancePortal 16 Return to Nexus source remains unpromoted
-- because two different client models share that portal link.
INSERT INTO `entity` (`id`, `type`, `creature`, `world`, `area`, `x`, `y`, `z`, `rx`, `ry`, `rz`, `displayInfo`, `outfitInfo`, `faction1`, `faction2`, `questChecklistIdx`, `activePropId`, `worldSocketId`, `mode`) VALUES
  (1000107802,14,48933,2183,2613,-1003,3,800,0,0,0,23861,0,219,219,0,0,0,0);

-- Jabbithole/DataMapping records explicit zero interrupt armour for this row.
INSERT INTO `entity_stats` (`id`, `stat`, `value`) VALUES
  (1000107802,21,0);
""".lstrip()
    )


def write_footer(handle) -> None:
    primary_entity_filter = primary_entity_range_sql("id")
    handle.write(
        f"""
-- Algoroc Dodger stale DataMapping coordinate reject.
-- Source coordinate 1556666 is superseded by official/current coordinate 4460.
DELETE FROM entity_stats
WHERE id = 1001556666;

DELETE FROM entity
WHERE id = 1001556666
  AND creature = 54640
  AND world = 51
  AND area = 23
  AND ABS(x - 3773) < 0.001
  AND ABS(y - (-999)) < 0.001
  AND ABS(z - (-4500)) < 0.001;

COMMIT;

SET FOREIGN_KEY_CHECKS = @NF_OLD_FOREIGN_KEY_CHECKS;

SELECT 'runtime_seed_entity_spawns' AS table_name, COUNT(*) AS row_count
FROM entity
WHERE {primary_entity_filter}
UNION ALL SELECT 'runtime_seed_entity_spawn_stats', COUNT(*)
FROM entity_stats
WHERE {primary_entity_filter}
UNION ALL SELECT 'entity_vendor', COUNT(*) FROM entity_vendor
UNION ALL SELECT 'entity_vendor_category', COUNT(*) FROM entity_vendor_category
UNION ALL SELECT 'entity_vendor_item', COUNT(*) FROM entity_vendor_item
UNION ALL SELECT 'creature_loot', COUNT(*) FROM creature_loot
UNION ALL SELECT 'loot_group_mapped', COUNT(*) FROM loot_group WHERE comment LIKE 'DataMapping %'
UNION ALL SELECT 'entity_loot_mapped', COUNT(*) FROM entity_loot WHERE comment LIKE 'DataMapping %'
UNION ALL SELECT 'item_loot_mapped', COUNT(*) FROM item_loot WHERE comment LIKE 'DataMapping %'
UNION ALL SELECT 'loot_item_mapped', COUNT(*) FROM loot_item li JOIN loot_group lg ON lg.id = li.id WHERE lg.comment LIKE 'DataMapping %'
UNION ALL SELECT 'item_salvage_mapped', COUNT(*) FROM item_salvage WHERE comment LIKE 'DataMapping %'
UNION ALL SELECT 'creature_info_property', COUNT(*) FROM creature_info_property
UNION ALL SELECT 'creature_info_stat', COUNT(*) FROM creature_info_stat;
""".lstrip()
    )


def parse_args(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path, default=Path.cwd())
    parser.add_argument("--mysql-exe", type=Path, default=Path(DEFAULT_MYSQL))
    parser.add_argument("--mysqldump-exe", type=Path)
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=3306)
    parser.add_argument("--user", default="bankai")
    parser.add_argument("--password", default="bankai")
    parser.add_argument("--world-db", default="nexus_forever_world")
    parser.add_argument("--output", type=Path)
    args = parser.parse_args(argv)
    args.repo_root = args.repo_root.resolve()
    args.mysql_exe = args.mysql_exe.resolve()
    args.mysqldump_exe = (
        args.mysqldump_exe
        or args.mysql_exe.with_name("mysqldump.exe")
    ).resolve()
    args.output = (
        args.output
        or args.repo_root / "Tools" / "DataMapping" / "sql" / "runtime_world_seed.sql"
    ).resolve()
    return args


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = parse_args(argv)
    if not args.mysql_exe.exists():
        raise FileNotFoundError(args.mysql_exe)
    if not args.mysqldump_exe.exists():
        raise FileNotFoundError(args.mysqldump_exe)
    vendor_ids = mysql_scalar_list(
        args,
        f"SELECT id FROM entity_vendor WHERE {exclude_laughingws_ranges_sql('id')} ORDER BY id;",
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8", newline="\n") as handle:
        write_header(handle, args)
        write_cleanup(handle, vendor_ids)
        write_data(handle, args)
        write_footer(handle)

    print(f"Wrote {args.output}")
    print(f"Vendor ids: {len(vendor_ids)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
