#!/usr/bin/env python3
"""
Export promoted DataMapping runtime rows as a standalone world-database SQL seed.

This is for fresh machines that should be able to import reviewed runtime data
from checked-in SQL without rebuilding Jabbithole/WildStar mapping outputs.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path
from typing import Optional, Sequence


DEFAULT_MYSQL = r"C:\Program Files\MySQL\MySQL Server 8.0\bin\mysql.exe"
ENTITY_ID_BASE = 1_000_000_000
ENTITY_ID_MAX = 1_999_999_999
CUSTOM_TABLES = [
    "creature_loot",
    "loot_group",
    "entity_loot",
    "item_loot",
    "loot_item",
    "creature_info_property",
    "creature_info_stat",
]


def mysql_command(args: argparse.Namespace, extra: Optional[Sequence[str]] = None) -> list[str]:
    command = [
        str(args.mysql_exe),
        f"--host={args.host}",
        f"--port={args.port}",
        f"--user={args.user}",
        f"--password={args.password}",
        "--default-character-set=utf8mb4",
        "--batch",
        "--raw",
        "--skip-column-names",
    ]
    if extra:
        command.extend(extra)
    return command


def mysqldump_command(args: argparse.Namespace, table: str, where: str) -> list[str]:
    return [
        str(args.mysqldump_exe),
        f"--host={args.host}",
        f"--port={args.port}",
        f"--user={args.user}",
        f"--password={args.password}",
        "--default-character-set=utf8mb4",
        "--single-transaction",
        "--quick",
        "--skip-comments",
        "--compact",
        "--skip-add-locks",
        "--skip-disable-keys",
        "--no-create-info",
        "--complete-insert",
        "--extended-insert",
        "--hex-blob",
        f"--where={where}",
        args.world_db,
        table,
    ]


def run_text(command: Sequence[str], *, input_text: Optional[str] = None) -> str:
    result = subprocess.run(
        command,
        input=input_text,
        text=True,
        encoding="utf-8",
        errors="replace",
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip() or f"{command[0]} exited with {result.returncode}")
    if result.stderr.strip():
        print(result.stderr.strip(), file=sys.stderr)
    return result.stdout


def sql_string(value: str) -> str:
    return "'" + value.replace("\\", "\\\\").replace("'", "''") + "'"


def mysql_scalar_list(args: argparse.Namespace, query: str) -> list[str]:
    output = run_text(mysql_command(args, [args.world_db, "-e", query]))
    return [line.strip() for line in output.splitlines() if line.strip()]


def comma_ids(ids: Sequence[str]) -> str:
    if not ids:
        return "0"
    return ",".join(ids)


def table_create_sql(args: argparse.Namespace, table_name: str) -> str:
    apply_sql = args.apply_sql.read_text(encoding="utf-8")
    pattern = re.compile(
        rf"CREATE TABLE IF NOT EXISTS\s+{re.escape(table_name)}\s*\(.*?\)\s*ENGINE=InnoDB[^;]*;",
        re.IGNORECASE | re.DOTALL,
    )
    match = pattern.search(apply_sql)
    if not match:
        raise RuntimeError(f"Could not find CREATE TABLE block for {table_name} in {args.apply_sql}")
    return match.group(0).strip()


def write_header(handle, args: argparse.Namespace) -> None:
    handle.write("-- Promoted NexusForever DataMapping runtime world seed.\n")
    handle.write("-- Generated by Tools/DataMapping/export_runtime_world_seed.py.\n")
    handle.write("-- This file is import-only and does not require nf_map_*, jabbithole, or wildstar_client tables.\n\n")
    handle.write(f"USE `{args.world_db}`;\n\n")
    handle.write("SET @NF_OLD_FOREIGN_KEY_CHECKS := @@FOREIGN_KEY_CHECKS;\n")
    handle.write("SET FOREIGN_KEY_CHECKS = 0;\n\n")
    for table_name in CUSTOM_TABLES:
        handle.write(table_create_sql(args, table_name))
        handle.write("\n\n")
    handle.write(
        """
SET @hasOldCreatureInfoPropertyValue = (
  SELECT COUNT(*)
  FROM information_schema.columns
  WHERE table_schema = DATABASE()
    AND table_name = 'creature_info_property'
    AND column_name = 'alue'
);
SET @hasCreatureInfoPropertyValue = (
  SELECT COUNT(*)
  FROM information_schema.columns
  WHERE table_schema = DATABASE()
    AND table_name = 'creature_info_property'
    AND column_name = 'value'
);
SET @repairCreatureInfoPropertyValue = IF(
  @hasOldCreatureInfoPropertyValue > 0 AND @hasCreatureInfoPropertyValue = 0,
  'ALTER TABLE creature_info_property CHANGE COLUMN `alue` `value` float NOT NULL',
  'DO 0'
);
PREPARE repairCreatureInfoPropertyValueStatement FROM @repairCreatureInfoPropertyValue;
EXECUTE repairCreatureInfoPropertyValueStatement;
DEALLOCATE PREPARE repairCreatureInfoPropertyValueStatement;

START TRANSACTION;
""".lstrip()
    )


def write_cleanup(handle, vendor_ids: Sequence[str]) -> None:
    vendor_id_list = comma_ids(vendor_ids)
    handle.write(
        f"""
DELETE FROM entity_loot
WHERE comment LIKE 'DataMapping %'
   OR id BETWEEN {ENTITY_ID_BASE} AND {ENTITY_ID_MAX};

DELETE FROM item_loot
WHERE comment LIKE 'DataMapping %';

DELETE li
FROM loot_item li
JOIN loot_group lg ON lg.id = li.id
WHERE lg.comment LIKE 'DataMapping %';

DELETE FROM loot_group
WHERE comment LIKE 'DataMapping %';

DELETE FROM creature_loot;

DELETE FROM entity_stats
WHERE id BETWEEN {ENTITY_ID_BASE} AND {ENTITY_ID_MAX};

DELETE FROM entity
WHERE id BETWEEN {ENTITY_ID_BASE} AND {ENTITY_ID_MAX};

DELETE FROM entity_vendor_item
WHERE id IN ({vendor_id_list});

DELETE FROM entity_vendor_category
WHERE id IN ({vendor_id_list});

DELETE FROM entity_vendor
WHERE id IN ({vendor_id_list});

DELETE FROM creature_info_property
WHERE `property` IN (7, 41);

DELETE FROM creature_info_stat
WHERE `stat` IN (21);

-- Rider's Reef tutorial combat cleanup promoted from the reviewed import.
DELETE FROM entity
WHERE world = 3460
  AND creature = 73665;

UPDATE entity
SET type = 0,
    faction1 = CASE creature
        WHEN 73494 THEN 1441
        WHEN 74862 THEN 1442
        ELSE faction1
    END,
    faction2 = CASE creature
        WHEN 73494 THEN 1441
        WHEN 74862 THEN 1442
        ELSE faction2
    END
WHERE world = 3460
  AND creature IN (73494, 74862);
""".lstrip()
    )


def dump_table(args: argparse.Namespace, table: str, where: str) -> str:
    output = run_text(mysqldump_command(args, table, where))
    return "\n".join(line for line in output.splitlines() if line and not line.startswith("/*!")) + "\n"


def write_data(handle, args: argparse.Namespace) -> None:
    table_filters = [
        ("entity", f"id BETWEEN {ENTITY_ID_BASE} AND {ENTITY_ID_MAX}"),
        ("entity_stats", f"id BETWEEN {ENTITY_ID_BASE} AND {ENTITY_ID_MAX}"),
        ("entity_vendor", "1=1"),
        ("entity_vendor_category", "1=1"),
        ("entity_vendor_item", "1=1"),
        ("creature_loot", "1=1"),
        ("loot_group", "comment LIKE 'DataMapping %'"),
        ("entity_loot", f"comment LIKE 'DataMapping %' OR id BETWEEN {ENTITY_ID_BASE} AND {ENTITY_ID_MAX}"),
        ("item_loot", "comment LIKE 'DataMapping %'"),
        ("loot_item", "id IN (SELECT id FROM loot_group WHERE comment LIKE 'DataMapping %')"),
        ("creature_info_property", "`property` IN (7, 41)"),
        ("creature_info_stat", "`stat` IN (21)"),
    ]
    for table, where in table_filters:
        handle.write(f"\n-- Data for `{table}`.\n")
        handle.write(dump_table(args, table, where))


def write_footer(handle) -> None:
    handle.write(
        f"""
COMMIT;

SET FOREIGN_KEY_CHECKS = @NF_OLD_FOREIGN_KEY_CHECKS;

SELECT 'runtime_seed_entity_spawns' AS table_name, COUNT(*) AS row_count
FROM entity
WHERE id BETWEEN {ENTITY_ID_BASE} AND {ENTITY_ID_MAX}
UNION ALL SELECT 'runtime_seed_entity_spawn_stats', COUNT(*)
FROM entity_stats
WHERE id BETWEEN {ENTITY_ID_BASE} AND {ENTITY_ID_MAX}
UNION ALL SELECT 'entity_vendor', COUNT(*) FROM entity_vendor
UNION ALL SELECT 'entity_vendor_category', COUNT(*) FROM entity_vendor_category
UNION ALL SELECT 'entity_vendor_item', COUNT(*) FROM entity_vendor_item
UNION ALL SELECT 'creature_loot', COUNT(*) FROM creature_loot
UNION ALL SELECT 'loot_group_mapped', COUNT(*) FROM loot_group WHERE comment LIKE 'DataMapping %'
UNION ALL SELECT 'entity_loot_mapped', COUNT(*) FROM entity_loot WHERE comment LIKE 'DataMapping %'
UNION ALL SELECT 'item_loot_mapped', COUNT(*) FROM item_loot WHERE comment LIKE 'DataMapping %'
UNION ALL SELECT 'loot_item_mapped', COUNT(*) FROM loot_item li JOIN loot_group lg ON lg.id = li.id WHERE lg.comment LIKE 'DataMapping %'
UNION ALL SELECT 'creature_info_property', COUNT(*) FROM creature_info_property
UNION ALL SELECT 'creature_info_stat', COUNT(*) FROM creature_info_stat;
""".lstrip()
    )


def parse_args(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path, default=Path.cwd())
    parser.add_argument("--mysql-exe", type=Path, default=Path(DEFAULT_MYSQL))
    parser.add_argument("--mysqldump-exe", type=Path)
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=3306)
    parser.add_argument("--user", default="bankai")
    parser.add_argument("--password", default="bankai")
    parser.add_argument("--world-db", default="nexus_forever_world")
    parser.add_argument("--apply-sql", type=Path)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args(argv)
    args.repo_root = args.repo_root.resolve()
    args.mysql_exe = args.mysql_exe.resolve()
    args.mysqldump_exe = (
        args.mysqldump_exe
        or args.mysql_exe.with_name("mysqldump.exe")
    ).resolve()
    args.output = (
        args.output
        or args.repo_root / "Tools" / "DataMapping" / "sql" / "runtime_world_seed.sql"
    ).resolve()
    args.apply_sql = (
        args.apply_sql
        or args.repo_root / "Tools" / "DataMapping" / "sql" / "apply_safe_world_imports_from_staging.sql"
    ).resolve()
    return args


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = parse_args(argv)
    if not args.mysql_exe.exists():
        raise FileNotFoundError(args.mysql_exe)
    if not args.mysqldump_exe.exists():
        raise FileNotFoundError(args.mysqldump_exe)
    if not args.apply_sql.exists():
        raise FileNotFoundError(args.apply_sql)

    vendor_ids = mysql_scalar_list(args, "SELECT id FROM entity_vendor ORDER BY id;")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8", newline="\n") as handle:
        write_header(handle, args)
        write_cleanup(handle, vendor_ids)
        write_data(handle, args)
        write_footer(handle)

    print(f"Wrote {args.output}")
    print(f"Vendor ids: {len(vendor_ids)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
