#!/usr/bin/env python3
"""Extract safe map entrance rows from LaughingWS world SQL."""

from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

from analyze_laughingws_worlddb import (
    normalise_column,
    read_text,
    split_top_level_commas,
    split_value_rows,
)


SET_WORLD_RE = re.compile(r"\bSET\s+@WORLD\s*:?=\s*(\d+)\b", re.IGNORECASE)
INSERT_MAP_ENTRANCE_RE = re.compile(
    r"\bINSERT\s+INTO\s+`?map_entrance`?\s*\((?P<columns>.*?)\)\s*"
    r"VALUE(?:S)?\s*(?P<values>.*?);",
    re.IGNORECASE | re.DOTALL,
)


@dataclass(frozen=True)
class MapEntranceRow:
    map_id: int
    team: int
    world_location_id: int
    source_file: str

    @property
    def key(self) -> tuple[int, int]:
        return (self.map_id, self.team)


def default_laughingws_path(repo_root: Path) -> Path:
    return repo_root.parent / "NexusForever.WorldDatabase.New-Zones-and-more"


def default_official_worlddb_path(repo_root: Path) -> Path:
    return repo_root.parent / "NexusForever.WorldDatabase"


def iter_sql_files(root: Path) -> Iterable[Path]:
    yield from sorted(root.rglob("*.sql"))


def parse_world_variable(text: str) -> int | None:
    match = SET_WORLD_RE.search(text)
    if match:
        return int(match.group(1))
    return None


def parse_integer_token(token: str, world_id: int | None) -> int:
    value = token.strip().strip("`")
    if value.upper() == "@WORLD":
        if world_id is None:
            raise ValueError("@WORLD used before a SET @WORLD declaration")
        return world_id
    return int(value, 0)


def parse_map_entrances(root: Path) -> dict[tuple[int, int], MapEntranceRow]:
    rows: dict[tuple[int, int], MapEntranceRow] = {}
    conflicts: list[str] = []

    for path in iter_sql_files(root):
        text = read_text(path)
        world_id = parse_world_variable(text)
        relative_path = str(path.relative_to(root))

        for insert_match in INSERT_MAP_ENTRANCE_RE.finditer(text):
            columns = [
                normalise_column(column)
                for column in split_top_level_commas(insert_match.group("columns"))
            ]

            for row_sql in split_value_rows(insert_match.group("values")):
                values = split_top_level_commas(row_sql)
                data = {
                    columns[index]: values[index]
                    for index in range(min(len(columns), len(values)))
                }

                try:
                    row = MapEntranceRow(
                        map_id=parse_integer_token(data["mapid"], world_id),
                        team=parse_integer_token(data["team"], world_id),
                        world_location_id=parse_integer_token(data["worldlocationid"], world_id),
                        source_file=relative_path,
                    )
                except KeyError as ex:
                    raise ValueError(f"{relative_path} map_entrance insert is missing {ex}") from ex
                except ValueError as ex:
                    raise ValueError(f"{relative_path} map_entrance row could not be parsed: {row_sql}") from ex

                previous = rows.get(row.key)
                if previous is not None and previous.world_location_id != row.world_location_id:
                    conflicts.append(
                        f"mapId={row.map_id}, team={row.team}: "
                        f"{previous.world_location_id} in {previous.source_file}, "
                        f"{row.world_location_id} in {row.source_file}"
                    )
                rows[row.key] = row

    if conflicts:
        joined = "\n".join(f"- {conflict}" for conflict in conflicts)
        raise ValueError(f"Conflicting map entrance rows were found:\n{joined}")

    return rows


def build_overlay_rows(
    laughingws_rows: dict[tuple[int, int], MapEntranceRow],
    official_rows: dict[tuple[int, int], MapEntranceRow],
) -> list[MapEntranceRow]:
    overlay_rows: list[MapEntranceRow] = []
    for key, row in laughingws_rows.items():
        if key not in official_rows:
            overlay_rows.append(row)

    return sorted(overlay_rows, key=lambda row: (row.map_id, row.team))


def write_seed(output_path: Path, rows: list[MapEntranceRow]) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "-- Generated by Tools/DataMapping/extract_laughingws_map_entrances.py.",
        "-- Source: LaughingWS/NexusForever.WorldDatabase.New-Zones-and-more map_entrance rows",
        "-- Purpose: Add missing matching map entrances without importing destructive world SQL.",
        "",
        "USE `nexus_forever_world`;",
        "",
        "START TRANSACTION;",
        "",
    ]

    if rows:
        lines.append(f"-- map_entrance: {len(rows)} row(s)")
        lines.append("INSERT IGNORE INTO `map_entrance` (`mapId`, `team`, `worldLocationId`) VALUES")
        for index, row in enumerate(rows):
            suffix = "," if index + 1 < len(rows) else ";"
            lines.append(f"    ({row.map_id}, {row.team}, {row.world_location_id}){suffix}")
        lines.extend(
            [
                "",
                "-- Sources:",
            ]
        )
        for source in sorted({row.source_file for row in rows}):
            lines.append(f"--   {source}")
        lines.append("")
    else:
        lines.append("-- No map_entrance overlay rows were found.")
        lines.append("")

    lines.extend(["COMMIT;", ""])
    output_path.write_text("\n".join(lines), encoding="ascii", newline="\n")


def parse_args() -> argparse.Namespace:
    repo_root = Path(__file__).resolve().parents[2]
    parser = argparse.ArgumentParser(
        description="Extract additive map_entrance rows from the LaughingWS world database fork.",
    )
    parser.add_argument(
        "--laughingws-path",
        type=Path,
        default=default_laughingws_path(repo_root),
        help="Path to LaughingWS/NexusForever.WorldDatabase.New-Zones-and-more.",
    )
    parser.add_argument(
        "--official-worlddb-path",
        type=Path,
        default=default_official_worlddb_path(repo_root),
        help="Path to the official NexusForever.WorldDatabase checkout.",
    )
    parser.add_argument(
        "--output-sql",
        type=Path,
        default=repo_root / "Tools" / "DataMapping" / "sql" / "laughingws_map_entrance_seed.sql",
        help="Output SQL seed path.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    laughingws_path = args.laughingws_path.resolve()
    official_path = args.official_worlddb_path.resolve()

    if not laughingws_path.is_dir():
        raise SystemExit(f"LaughingWS path does not exist: {laughingws_path}")
    if not official_path.is_dir():
        raise SystemExit(f"Official world database path does not exist: {official_path}")

    laughingws_rows = parse_map_entrances(laughingws_path)
    official_rows = parse_map_entrances(official_path)
    overlay_rows = build_overlay_rows(laughingws_rows, official_rows)
    write_seed(args.output_sql, overlay_rows)

    print(
        f"Wrote {len(overlay_rows)} map entrance row(s) to {args.output_sql.resolve()} "
        f"({len(laughingws_rows)} LaughingWS row(s), {len(official_rows)} official row(s))."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
