-- Staging schema for Tools/DataMapping/map_wildstar_data.py outputs.
-- Load this into nexus_forever_world or a scratch schema before importing CSVs.

CREATE TABLE IF NOT EXISTS nf_map_creature (
    jabbithole_creature_id INT PRIMARY KEY,
    creature2_id INT NULL,
    source_name VARCHAR(255),
    client_name VARCHAR(255),
    match_status VARCHAR(32),
    match_score INT NULL,
    candidate_count INT NOT NULL DEFAULT 0,
    entity_type TINYINT UNSIGNED NOT NULL DEFAULT 0,
    zone_id INT NULL,
    worldid INT NULL,
    worldzoneid INT NULL,
    source_faction INT NULL,
    client_faction INT NULL,
    level_min INT NULL,
    level_max INT NULL,
    client_min_level INT NULL,
    client_max_level INT NULL,
    difficulty INT NULL,
    client_difficulty INT NULL,
    health_min INT NULL,
    health_max INT NULL,
    template_base_health FLOAT NULL,
    shield INT NULL,
    interrupt_armor_max INT NULL,
    creature_type VARCHAR(32),
    is_vendor VARCHAR(8),
    is_scannable VARCHAR(8),
    is_harvestable VARCHAR(8),
    datacube_id INT NULL,
    client_datacube_id INT NULL,
    creature2_action_set_id INT NULL,
    creature2_display_group_id INT NULL,
    default_display_info INT NULL,
    creature2_outfit_group_id INT NULL,
    default_outfit_info INT NULL,
    last_seen_in INT NULL,
    original_creature2_id INT NULL,
    original_client_name VARCHAR(255),
    original_match_status VARCHAR(32),
    review_decision VARCHAR(64),
    review_reason TEXT,
    reviewer VARCHAR(255),
    reviewed_at VARCHAR(64),
    KEY ix_nf_map_creature_creature2 (creature2_id),
    KEY ix_nf_map_creature_status (match_status)
);

CREATE TABLE IF NOT EXISTS nf_map_creature_spawn (
    source_coordinate_id INT PRIMARY KEY,
    jabbithole_creature_id INT NOT NULL,
    creature2_id INT NULL,
    source_name VARCHAR(255),
    creature2_name VARCHAR(255),
    match_status VARCHAR(32),
    entity_type TINYINT UNSIGNED NULL,
    zone_id INT NULL,
    worldid INT NULL,
    worldzoneid INT NULL,
    x FLOAT NULL,
    y FLOAT NULL,
    z FLOAT NULL,
    level_min INT NULL,
    level_max INT NULL,
    health_min INT NULL,
    health_max INT NULL,
    shield INT NULL,
    interrupt_armor_max INT NULL,
    faction INT NULL,
    coordinate_last_seen_in INT NULL,
    KEY ix_nf_map_spawn_creature (jabbithole_creature_id),
    KEY ix_nf_map_spawn_creature2 (creature2_id),
    KEY ix_nf_map_spawn_world_area (worldid, worldzoneid)
);

CREATE TABLE IF NOT EXISTS nf_map_world_entity_candidate (
    source_coordinate_id INT PRIMARY KEY,
    jabbithole_creature_id INT NOT NULL,
    source_name VARCHAR(255),
    entity_id INT NULL,
    Type TINYINT UNSIGNED NULL,
    Creature INT NULL,
    World INT NULL,
    Area INT NULL,
    X FLOAT NULL,
    Y FLOAT NULL,
    Z FLOAT NULL,
    RX FLOAT NOT NULL DEFAULT 0,
    RY FLOAT NOT NULL DEFAULT 0,
    RZ FLOAT NOT NULL DEFAULT 0,
    DisplayInfo INT NULL,
    OutfitInfo INT NULL,
    Faction1 INT NULL,
    Faction2 INT NULL,
    QuestChecklistIdx TINYINT UNSIGNED NOT NULL DEFAULT 0,
    Mode TINYINT UNSIGNED NOT NULL DEFAULT 0,
    ActivePropId BIGINT UNSIGNED NOT NULL DEFAULT 0,
    WorldSocketId INT UNSIGNED NOT NULL DEFAULT 0,
    match_status VARCHAR(32),
    KEY ix_nf_map_entity_candidate_creature (Creature),
    KEY ix_nf_map_entity_candidate_world_area (World, Area)
);

CREATE TABLE IF NOT EXISTS nf_map_world_entity_stats_candidate (
    source_coordinate_id INT NOT NULL,
    jabbithole_creature_id INT NOT NULL,
    source_name VARCHAR(255),
    entity_id INT NULL,
    Stat SMALLINT UNSIGNED NOT NULL,
    StatName VARCHAR(64) NOT NULL,
    Value FLOAT NOT NULL,
    PRIMARY KEY (source_coordinate_id, Stat),
    KEY ix_nf_map_stats_candidate_entity (entity_id)
);

CREATE TABLE IF NOT EXISTS nf_map_creature_loot (
    source_drop_id INT PRIMARY KEY,
    jabbithole_creature_id INT NOT NULL,
    creature2_id INT NULL,
    source_name VARCHAR(255),
    creature2_name VARCHAR(255),
    match_status VARCHAR(32),
    jabbithole_item_id INT NULL,
    item2_id INT NULL,
    item_name VARCHAR(255),
    game_version INT NULL,
    drop_times INT NULL,
    aggregate_drop_sum INT NULL,
    aggregate_drop_count INT NULL,
    drop_probability DECIMAL(18, 10) NULL,
    versioned_item_drop_aggregate_id INT NULL,
    versioned_creature_drop_aggregate_id INT NULL,
    last_seen_in INT NULL,
    KEY ix_nf_map_loot_creature (jabbithole_creature_id),
    KEY ix_nf_map_loot_creature2 (creature2_id),
    KEY ix_nf_map_loot_item2 (item2_id)
);

CREATE TABLE IF NOT EXISTS nf_map_vendor_item (
    vendor_item_source_id INT PRIMARY KEY,
    jabbithole_creature_id INT NOT NULL,
    creature2_id INT NULL,
    source_name VARCHAR(255),
    creature2_name VARCHAR(255),
    match_status VARCHAR(32),
    jabbithole_item_id INT NULL,
    item2_id INT NULL,
    item_name VARCHAR(255),
    game_version INT NULL,
    main_currency_id INT NULL,
    main_price INT NULL,
    alt_currency_id INT NULL,
    alt_price INT NULL,
    stack_size INT NULL,
    stock_size INT NULL,
    special_item VARCHAR(8),
    prerequisite VARCHAR(255),
    last_seen_in INT NULL,
    KEY ix_nf_map_vendor_creature (jabbithole_creature_id),
    KEY ix_nf_map_vendor_creature2 (creature2_id),
    KEY ix_nf_map_vendor_item2 (item2_id)
);

CREATE TABLE IF NOT EXISTS nf_map_creature_spell (
    source_creature_spell_id INT PRIMARY KEY,
    jabbithole_creature_id INT NOT NULL,
    creature2_id INT NULL,
    source_name VARCHAR(255),
    creature2_name VARCHAR(255),
    match_status VARCHAR(32),
    jabbithole_spell_id INT NULL,
    spell4_id INT NULL,
    spell_name VARCHAR(255),
    tier INT NULL,
    base_spell4_id INT NULL,
    last_seen_in INT NULL,
    KEY ix_nf_map_spell_creature (jabbithole_creature_id),
    KEY ix_nf_map_spell_creature2 (creature2_id),
    KEY ix_nf_map_spell_spell4 (spell4_id)
);

CREATE TABLE IF NOT EXISTS nf_map_creature_quest (
    relation_type VARCHAR(16) NOT NULL,
    source_relation_id INT NOT NULL,
    jabbithole_creature_id INT NOT NULL,
    creature2_id INT NULL,
    source_name VARCHAR(255),
    creature2_name VARCHAR(255),
    match_status VARCHAR(32),
    jabbithole_quest_id INT NULL,
    quest2_id INT NULL,
    quest_name VARCHAR(255),
    quest_level INT NULL,
    quest_min_level INT NULL,
    quest_type INT NULL,
    path_quest_type INT NULL,
    last_seen_in INT NULL,
    PRIMARY KEY (relation_type, source_relation_id),
    KEY ix_nf_map_quest_creature (jabbithole_creature_id),
    KEY ix_nf_map_quest_quest2 (quest2_id)
);

CREATE TABLE IF NOT EXISTS nf_map_creature_path_mission (
    source_relation_id INT PRIMARY KEY,
    jabbithole_creature_id INT NOT NULL,
    creature2_id INT NULL,
    source_name VARCHAR(255),
    creature2_name VARCHAR(255),
    match_status VARCHAR(32),
    jabbithole_path_mission_id INT NULL,
    path_mission_id INT NULL,
    path_mission_name VARCHAR(255),
    player_path_id INT NULL,
    mission_type INT NULL,
    mission_subtype INT NULL,
    needed INT NULL,
    real_zone_id INT NULL,
    datamined_zone_id INT NULL,
    last_seen_in INT NULL,
    KEY ix_nf_map_path_creature (jabbithole_creature_id),
    KEY ix_nf_map_path_path_mission (path_mission_id)
);

CREATE TABLE IF NOT EXISTS nf_map_creature_public_event (
    source_relation_id INT PRIMARY KEY,
    jabbithole_creature_id INT NOT NULL,
    creature2_id INT NULL,
    source_name VARCHAR(255),
    creature2_name VARCHAR(255),
    match_status VARCHAR(32),
    jabbithole_public_event_id INT NULL,
    public_event_id INT NULL,
    public_event_name VARCHAR(255),
    event_type INT NULL,
    reward_type INT NULL,
    real_zone_id INT NULL,
    parent_public_event_id INT NULL,
    last_seen_in INT NULL,
    KEY ix_nf_map_public_creature (jabbithole_creature_id),
    KEY ix_nf_map_public_event (public_event_id)
);

CREATE TABLE IF NOT EXISTS nf_map_creature_ai_action (
    creature2_id INT NOT NULL,
    creature2_name VARCHAR(255),
    jabbithole_creature_ids TEXT,
    creature_action_set_id INT NOT NULL,
    action_id INT NOT NULL,
    state INT NULL,
    event INT NULL,
    order_index INT NULL,
    delay_ms INT NULL,
    action INT NULL,
    action_data_00 INT NULL,
    action_data_01 INT NULL,
    visual_effect_id INT NULL,
    prerequisite_id INT NULL,
    description VARCHAR(1024),
    PRIMARY KEY (creature2_id, action_id),
    KEY ix_nf_map_ai_action_set (creature_action_set_id)
);

CREATE TABLE IF NOT EXISTS nf_map_creature_spline_candidate (
    source_coordinate_id INT NOT NULL,
    jabbithole_creature_id INT NOT NULL,
    creature2_id INT NULL,
    source_name VARCHAR(255),
    creature2_name VARCHAR(255),
    worldid INT NULL,
    x FLOAT NULL,
    y FLOAT NULL,
    z FLOAT NULL,
    spline2_id INT NOT NULL,
    spline_start_x FLOAT NULL,
    spline_start_y FLOAT NULL,
    spline_start_z FLOAT NULL,
    distance FLOAT NULL,
    candidate_note VARCHAR(255),
    PRIMARY KEY (source_coordinate_id, spline2_id),
    KEY ix_nf_map_spline_creature (jabbithole_creature_id),
    KEY ix_nf_map_spline_spline2 (spline2_id)
);

CREATE TABLE IF NOT EXISTS nf_map_challenge (
    jabbithole_challenge_id INT PRIMARY KEY,
    challenge_id INT NULL,
    jabbithole_challenge_name VARCHAR(255),
    client_challenge_name VARCHAR(255),
    match_status VARCHAR(32),
    description VARCHAR(1024),
    goals VARCHAR(64),
    is_timed VARCHAR(8),
    challenge_type INT NULL,
    client_challenge_type INT NULL,
    zone_id INT NULL,
    client_world_zone_id INT NULL,
    zone_restriction_subzone INT NULL,
    start_location INT NULL,
    challenge_reward_track_id INT NULL,
    client_reward_track_id INT NULL,
    client_target INT NULL,
    client_completion_count INT NULL,
    challenge_reward_items_count INT NULL,
    challenge_creatures_count INT NULL,
    is_dominion VARCHAR(8),
    is_exile VARCHAR(8),
    enabled VARCHAR(8),
    last_seen_in INT NULL,
    KEY ix_nf_map_challenge_client (challenge_id),
    KEY ix_nf_map_challenge_zone (zone_id)
);

CREATE TABLE IF NOT EXISTS nf_map_challenge_creature (
    source_relation_id INT PRIMARY KEY,
    jabbithole_challenge_id INT NOT NULL,
    challenge_id INT NULL,
    challenge_name VARCHAR(255),
    client_challenge_name VARCHAR(255),
    challenge_type INT NULL,
    goals VARCHAR(64),
    zone_id INT NULL,
    jabbithole_creature_id INT NOT NULL,
    creature2_id INT NULL,
    source_name VARCHAR(255),
    creature2_name VARCHAR(255),
    match_status VARCHAR(32),
    last_seen_in INT NULL,
    KEY ix_nf_map_challenge_creature_challenge (challenge_id),
    KEY ix_nf_map_challenge_creature_creature (creature2_id)
);

CREATE TABLE IF NOT EXISTS nf_map_challenge_reward_item (
    relation_source VARCHAR(64) NOT NULL,
    source_relation_id INT NOT NULL,
    jabbithole_challenge_id INT NULL,
    challenge_id INT NULL,
    challenge_name VARCHAR(255),
    client_challenge_name VARCHAR(255),
    challenge_reward_track_id INT NULL,
    jabbithole_challenge_reward_id INT NULL,
    challenge_reward_id INT NULL,
    reward_index INT NULL,
    reward_type INT NULL,
    cost INT NULL,
    tier INT NULL,
    amount INT NULL,
    jabbithole_item_id INT NULL,
    item2_id INT NULL,
    item_name VARCHAR(255),
    last_seen_in INT NULL,
    PRIMARY KEY (relation_source, source_relation_id),
    KEY ix_nf_map_challenge_reward_challenge (challenge_id),
    KEY ix_nf_map_challenge_reward_item2 (item2_id)
);

CREATE TABLE IF NOT EXISTS nf_map_table_coverage_inventory (
    source VARCHAR(64) NOT NULL,
    filename VARCHAR(255) NOT NULL,
    table_name VARCHAR(255),
    file_size_bytes BIGINT NULL,
    column_count INT NULL,
    coverage_status VARCHAR(32) NOT NULL,
    notes TEXT,
    PRIMARY KEY (source, filename),
    KEY ix_nf_map_table_coverage_status (coverage_status)
);

CREATE TABLE IF NOT EXISTS nf_map_quest_objective (
    jabbithole_quest_objective_id INT PRIMARY KEY,
    jabbithole_quest_id INT NOT NULL,
    quest2_id INT NULL,
    quest_name VARCHAR(255),
    client_quest_name VARCHAR(255),
    objective_order INT NULL,
    quest_objective_id INT NULL,
    match_status VARCHAR(32),
    jabbithole_objective_text VARCHAR(1024),
    client_objective_text VARCHAR(1024),
    objective_type INT NULL,
    objective_data INT NULL,
    objective_count INT NULL,
    quest_direction_id INT NULL,
    world_location_0 INT NULL,
    world_location_1 INT NULL,
    world_location_2 INT NULL,
    world_location_3 INT NULL,
    last_seen_in INT NULL,
    KEY ix_nf_map_quest_objective_quest2 (quest2_id),
    KEY ix_nf_map_quest_objective_objective (quest_objective_id)
);

CREATE TABLE IF NOT EXISTS nf_map_quest_reward_item (
    source_reward_id INT PRIMARY KEY,
    jabbithole_quest_id INT NOT NULL,
    quest2_id INT NULL,
    quest_name VARCHAR(255),
    client_quest_name VARCHAR(255),
    jabbithole_item_id INT NULL,
    item2_id INT NULL,
    item_name VARCHAR(255),
    game_reward_id INT NULL,
    amount INT NULL,
    fixed_reward VARCHAR(8),
    last_seen_in INT NULL,
    KEY ix_nf_map_quest_reward_item_quest2 (quest2_id),
    KEY ix_nf_map_quest_reward_item_item2 (item2_id)
);

CREATE TABLE IF NOT EXISTS nf_map_quest_reward_currency (
    source_reward_id INT PRIMARY KEY,
    jabbithole_quest_id INT NOT NULL,
    quest2_id INT NULL,
    quest_name VARCHAR(255),
    client_quest_name VARCHAR(255),
    jabbithole_currency_id INT NULL,
    currency_type_id INT NULL,
    currency_name VARCHAR(255),
    client_currency_name VARCHAR(255),
    game_reward_id INT NULL,
    amount INT NULL,
    fixed_reward VARCHAR(8),
    last_seen_in INT NULL,
    KEY ix_nf_map_quest_reward_currency_quest2 (quest2_id),
    KEY ix_nf_map_quest_reward_currency_type (currency_type_id)
);

CREATE TABLE IF NOT EXISTS nf_map_quest_reward_reputation (
    source_reward_id INT PRIMARY KEY,
    jabbithole_quest_id INT NOT NULL,
    quest2_id INT NULL,
    quest_name VARCHAR(255),
    client_quest_name VARCHAR(255),
    jabbithole_reputation_reward_id INT NULL,
    faction2_id INT NULL,
    reputation_name VARCHAR(255),
    client_faction_name VARCHAR(255),
    amount INT NULL,
    fixed_reward VARCHAR(8),
    last_seen_in INT NULL,
    KEY ix_nf_map_quest_reward_reputation_quest2 (quest2_id),
    KEY ix_nf_map_quest_reward_reputation_faction (faction2_id)
);

CREATE TABLE IF NOT EXISTS nf_map_quest_reward_tradeskill (
    source_reward_id INT PRIMARY KEY,
    jabbithole_quest_id INT NOT NULL,
    quest2_id INT NULL,
    quest_name VARCHAR(255),
    client_quest_name VARCHAR(255),
    jabbithole_tradeskill_reward_id INT NULL,
    tradeskill_id INT NULL,
    tradeskill_name VARCHAR(255),
    client_tradeskill_name VARCHAR(255),
    game_reward_id INT NULL,
    amount INT NULL,
    fixed_reward VARCHAR(8),
    last_seen_in INT NULL,
    KEY ix_nf_map_quest_reward_tradeskill_quest2 (quest2_id),
    KEY ix_nf_map_quest_reward_tradeskill_type (tradeskill_id)
);

CREATE TABLE IF NOT EXISTS nf_map_public_event_objective (
    jabbithole_public_event_objective_id INT PRIMARY KEY,
    jabbithole_public_event_id INT NULL,
    public_event_id INT NULL,
    jabbithole_public_event_name VARCHAR(255),
    client_public_event_name VARCHAR(255),
    public_event_objective_id INT NULL,
    match_status VARCHAR(32),
    public_event_id_from_objective INT NULL,
    jabbithole_objective_text TEXT,
    client_objective_text TEXT,
    jabbithole_objective_type INT NULL,
    objective_type INT NULL,
    jabbithole_objective_category INT NULL,
    objective_category INT NULL,
    objective_flags INT NULL,
    objective_type_specific_flags INT NULL,
    objective_count INT NULL,
    objective_object_id INT NULL,
    world_location_id INT NULL,
    public_event_team_id INT NULL,
    public_event_team_name VARCHAR(255),
    parent_public_event_objective_id INT NULL,
    quest_direction_id INT NULL,
    display_order INT NULL,
    medal_point_value INT NULL,
    failure_time_ms INT NULL,
    target_group_id_reward_pane INT NULL,
    last_seen_in INT NULL,
    KEY ix_nf_map_public_event_objective_event (public_event_id),
    KEY ix_nf_map_public_event_objective_objective (public_event_objective_id),
    KEY ix_nf_map_public_event_objective_status (match_status)
);

CREATE TABLE IF NOT EXISTS nf_map_public_event_mission (
    source_public_event_mission_id INT PRIMARY KEY,
    mission_name VARCHAR(255),
    description TEXT,
    parent_jabbithole_public_event_id INT NULL,
    parent_public_event_id INT NULL,
    parent_public_event_name VARCHAR(255),
    client_parent_public_event_name VARCHAR(255),
    child_jabbithole_public_event_id INT NULL,
    child_public_event_id INT NULL,
    child_public_event_name VARCHAR(255),
    client_child_public_event_name VARCHAR(255),
    last_seen_in INT NULL,
    KEY ix_nf_map_public_event_mission_parent (parent_public_event_id),
    KEY ix_nf_map_public_event_mission_child (child_public_event_id)
);

CREATE TABLE IF NOT EXISTS nf_map_public_event_zone (
    source_public_event_zone_id INT PRIMARY KEY,
    jabbithole_public_event_id INT NULL,
    public_event_id INT NULL,
    public_event_name VARCHAR(255),
    client_public_event_name VARCHAR(255),
    jabbithole_zone_id INT NULL,
    world_zone_id INT NULL,
    jabbithole_zone_name VARCHAR(255),
    client_zone_name VARCHAR(255),
    map_asset VARCHAR(255),
    continent_id INT NULL,
    last_seen_in INT NULL,
    KEY ix_nf_map_public_event_zone_event (public_event_id),
    KEY ix_nf_map_public_event_zone_world_zone (world_zone_id)
);

CREATE TABLE IF NOT EXISTS nf_map_public_event_depot_client (
    public_event_depot_id INT PRIMARY KEY,
    creature2_id INT NULL,
    creature2_name VARCHAR(255),
    item2_id INT NULL,
    item_name VARCHAR(255),
    KEY ix_nf_map_public_event_depot_creature (creature2_id),
    KEY ix_nf_map_public_event_depot_item (item2_id)
);

CREATE TABLE IF NOT EXISTS nf_map_public_event_virtual_item_depot_client (
    public_event_virtual_item_depot_id INT NOT NULL,
    creature2_id INT NULL,
    creature2_name VARCHAR(255),
    virtual_item_slot INT NOT NULL,
    virtual_item_id INT NOT NULL,
    virtual_item_name VARCHAR(255),
    button_icon VARCHAR(1024),
    item2_type_id INT NULL,
    item_quality_id INT NULL,
    PRIMARY KEY (public_event_virtual_item_depot_id, virtual_item_slot),
    KEY ix_nf_map_public_event_virtual_depot_creature (creature2_id),
    KEY ix_nf_map_public_event_virtual_depot_item (virtual_item_id)
);

CREATE TABLE IF NOT EXISTS nf_map_item_family (
    jabbithole_id INT PRIMARY KEY,
    client_id INT NULL,
    jabbithole_name VARCHAR(255),
    client_name VARCHAR(255),
    match_status VARCHAR(32),
    items_count INT NULL,
    flags INT NULL,
    vendorMultiplier FLOAT NULL,
    turninMultiplier FLOAT NULL,
    enabled VARCHAR(8),
    last_seen_in INT NULL,
    KEY ix_nf_map_item_family_client (client_id),
    KEY ix_nf_map_item_family_status (match_status)
);

CREATE TABLE IF NOT EXISTS nf_map_item_category (
    jabbithole_id INT PRIMARY KEY,
    client_id INT NULL,
    jabbithole_name VARCHAR(255),
    client_name VARCHAR(255),
    match_status VARCHAR(32),
    items_count INT NULL,
    item2FamilyId INT NULL,
    item_family_name VARCHAR(255),
    itemProficiencyId INT NULL,
    tradeSkillId INT NULL,
    flags INT NULL,
    vendorMultiplier FLOAT NULL,
    turninMultiplier FLOAT NULL,
    armorModifier FLOAT NULL,
    armorBase FLOAT NULL,
    weaponPowerModifier FLOAT NULL,
    weaponPowerBase INT NULL,
    enabled VARCHAR(8),
    last_seen_in INT NULL,
    KEY ix_nf_map_item_category_client (client_id),
    KEY ix_nf_map_item_category_family (item2FamilyId),
    KEY ix_nf_map_item_category_status (match_status)
);

CREATE TABLE IF NOT EXISTS nf_map_item_type (
    jabbithole_id INT PRIMARY KEY,
    client_id INT NULL,
    jabbithole_name VARCHAR(255),
    client_name VARCHAR(255),
    match_status VARCHAR(32),
    items_count INT NULL,
    Item2CategoryId INT NULL,
    item_category_name VARCHAR(255),
    itemSlotId INT NULL,
    item_slot_name VARCHAR(255),
    flags INT NULL,
    vendorMultiplier FLOAT NULL,
    turninMultiplier FLOAT NULL,
    enabled VARCHAR(8),
    last_seen_in INT NULL,
    KEY ix_nf_map_item_type_client (client_id),
    KEY ix_nf_map_item_type_category (Item2CategoryId),
    KEY ix_nf_map_item_type_slot (itemSlotId),
    KEY ix_nf_map_item_type_status (match_status)
);

CREATE TABLE IF NOT EXISTS nf_map_item_slot (
    jabbithole_id INT PRIMARY KEY,
    client_id INT NULL,
    jabbithole_name VARCHAR(255),
    client_name VARCHAR(255),
    match_status VARCHAR(32),
    items_count INT NULL,
    equippedSlotFlags INT NULL,
    armorModifier FLOAT NULL,
    itemLevelModifier FLOAT NULL,
    slotBonus INT NULL,
    glyphSlotBonus INT NULL,
    minLevel INT NULL,
    enabled VARCHAR(8),
    last_seen_in INT NULL,
    KEY ix_nf_map_item_slot_client (client_id),
    KEY ix_nf_map_item_slot_status (match_status)
);

CREATE TABLE IF NOT EXISTS nf_map_item_spell_effect (
    relation_source VARCHAR(32) NOT NULL,
    source_relation_id INT NOT NULL,
    item2_id INT NULL,
    item_name VARCHAR(255),
    jabbithole_spell_id INT NULL,
    spell4_id INT NULL,
    spell_name VARCHAR(255),
    tier INT NULL,
    base_spell4_id INT NULL,
    effect_name VARCHAR(255),
    on_equip VARCHAR(8),
    on_use VARCHAR(8),
    on_proc VARCHAR(8),
    last_seen_in INT NULL,
    PRIMARY KEY (relation_source, source_relation_id),
    KEY ix_nf_map_item_spell_effect_item (item2_id),
    KEY ix_nf_map_item_spell_effect_spell (spell4_id)
);

CREATE TABLE IF NOT EXISTS nf_map_item_drop_source (
    relation_source VARCHAR(32) NOT NULL,
    source_relation_id INT NOT NULL,
    raw_item_id INT NULL,
    item2_id INT NULL,
    item_name VARCHAR(255),
    jabbithole_creature_id INT NULL,
    creature2_id INT NULL,
    source_name VARCHAR(255),
    creature2_name VARCHAR(255),
    match_status VARCHAR(32),
    drop_times INT NULL,
    last_seen_in INT NULL,
    PRIMARY KEY (relation_source, source_relation_id),
    KEY ix_nf_map_item_drop_source_item (item2_id),
    KEY ix_nf_map_item_drop_source_creature (creature2_id)
);

CREATE TABLE IF NOT EXISTS nf_map_item_container (
    source_relation_id INT PRIMARY KEY,
    raw_container_item_id INT NULL,
    container_item2_id INT NULL,
    container_item_name VARCHAR(255),
    raw_contained_item_id INT NULL,
    contained_item2_id INT NULL,
    contained_item_name VARCHAR(255),
    drop_times INT NULL,
    last_seen_in INT NULL,
    KEY ix_nf_map_item_container_container (container_item2_id),
    KEY ix_nf_map_item_container_contained (contained_item2_id)
);

CREATE TABLE IF NOT EXISTS nf_map_item_salvage (
    source_relation_id INT PRIMARY KEY,
    raw_original_item_id INT NULL,
    original_item2_id INT NULL,
    original_item_name VARCHAR(255),
    raw_salvaged_item_id INT NULL,
    salvaged_item2_id INT NULL,
    salvaged_item_name VARCHAR(255),
    drop_times INT NULL,
    last_seen_in INT NULL,
    KEY ix_nf_map_item_salvage_original (original_item2_id),
    KEY ix_nf_map_item_salvage_salvaged (salvaged_item2_id)
);

CREATE TABLE IF NOT EXISTS nf_map_item_class_requirement (
    source_relation_id INT PRIMARY KEY,
    item2_id INT NULL,
    item_name VARCHAR(255),
    jabbithole_player_class_id INT NULL,
    class_id INT NULL,
    class_name VARCHAR(255),
    client_class_name VARCHAR(255),
    last_seen_in INT NULL,
    KEY ix_nf_map_item_class_requirement_item (item2_id),
    KEY ix_nf_map_item_class_requirement_class (class_id)
);

CREATE TABLE IF NOT EXISTS nf_map_item_tradeskill_requirement (
    source_relation_id INT PRIMARY KEY,
    item2_id INT NULL,
    item_name VARCHAR(255),
    jabbithole_tradeskill_id INT NULL,
    tradeskill_id INT NULL,
    tradeskill_name VARCHAR(255),
    client_tradeskill_name VARCHAR(255),
    required_tier INT NULL,
    last_seen_in INT NULL,
    KEY ix_nf_map_item_tradeskill_requirement_item (item2_id),
    KEY ix_nf_map_item_tradeskill_requirement_trade (tradeskill_id)
);

CREATE TABLE IF NOT EXISTS nf_map_item_chip_spell (
    source_relation_id INT PRIMARY KEY,
    item2_id INT NULL,
    item_name VARCHAR(255),
    jabbithole_spell_id INT NULL,
    spell4_id INT NULL,
    spell_name VARCHAR(255),
    tier INT NULL,
    base_spell4_id INT NULL,
    last_seen_in INT NULL,
    KEY ix_nf_map_item_chip_spell_item (item2_id),
    KEY ix_nf_map_item_chip_spell_spell (spell4_id)
);

CREATE TABLE IF NOT EXISTS nf_map_item_component (
    relation_source VARCHAR(32) NOT NULL,
    source_relation_id INT NOT NULL,
    item2_id INT NULL,
    item_name VARCHAR(255),
    related_item2_id INT NULL,
    related_item_name VARCHAR(255),
    last_seen_in INT NULL,
    PRIMARY KEY (relation_source, source_relation_id),
    KEY ix_nf_map_item_component_item (item2_id),
    KEY ix_nf_map_item_component_related (related_item2_id)
);

CREATE TABLE IF NOT EXISTS nf_map_item_instance_attribute (
    source_relation_id INT PRIMARY KEY,
    item2_id INT NULL,
    item_name VARCHAR(255),
    jabbithole_attribute_id INT NULL,
    unit_property2_id INT NULL,
    attribute_name VARCHAR(255),
    client_unit_property_name VARCHAR(255),
    client_unit_property_enum VARCHAR(255),
    attribute_order INT NULL,
    attribute_bonus DECIMAL(24, 13) NULL,
    is_innate VARCHAR(8),
    KEY ix_nf_map_item_instance_attribute_item (item2_id),
    KEY ix_nf_map_item_instance_attribute_property (unit_property2_id)
);

CREATE TABLE IF NOT EXISTS nf_map_player_path (
    jabbithole_player_path_id INT PRIMARY KEY,
    path_type INT NULL,
    path_name VARCHAR(255),
    description TEXT,
    slug VARCHAR(255),
    icon VARCHAR(255),
    path_missions_count INT NULL,
    path_episodes_count INT NULL,
    KEY ix_nf_map_player_path_type (path_type)
);

CREATE TABLE IF NOT EXISTS nf_map_path_episode (
    jabbithole_path_episode_id INT PRIMARY KEY,
    path_episode_id INT NULL,
    match_status VARCHAR(32),
    jabbithole_player_path_id INT NULL,
    path_type INT NULL,
    client_path_type INT NULL,
    path_name VARCHAR(255),
    jabbithole_name VARCHAR(255),
    client_path_episode_name VARCHAR(255),
    jabbithole_summary TEXT,
    client_path_episode_summary TEXT,
    world_zone_text VARCHAR(255),
    datamined_zone_id INT NULL,
    world_zone_id INT NULL,
    zone_name VARCHAR(255),
    client_world_id INT NULL,
    client_world_zone_id INT NULL,
    client_world_zone_name VARCHAR(255),
    path_episode_rewards_count INT NULL,
    path_episode_zones_count INT NULL,
    path_episode_missions_count INT NULL,
    is_dominion VARCHAR(8),
    is_exile VARCHAR(8),
    last_seen_in INT NULL,
    KEY ix_nf_map_path_episode_client (path_episode_id),
    KEY ix_nf_map_path_episode_status (match_status),
    KEY ix_nf_map_path_episode_zone (world_zone_id)
);

CREATE TABLE IF NOT EXISTS nf_map_path_episode_mission (
    source_relation_id INT PRIMARY KEY,
    jabbithole_path_episode_id INT NULL,
    path_episode_id INT NULL,
    path_episode_name VARCHAR(255),
    client_path_episode_name VARCHAR(255),
    jabbithole_path_mission_id INT NULL,
    path_mission_id INT NULL,
    path_mission_name VARCHAR(255),
    client_path_mission_name VARCHAR(255),
    player_path_id INT NULL,
    mission_type INT NULL,
    mission_subtype INT NULL,
    needed INT NULL,
    last_seen_in INT NULL,
    KEY ix_nf_map_path_episode_mission_episode (path_episode_id),
    KEY ix_nf_map_path_episode_mission_mission (path_mission_id)
);

CREATE TABLE IF NOT EXISTS nf_map_path_episode_reward (
    source_relation_id INT PRIMARY KEY,
    jabbithole_path_episode_id INT NULL,
    path_episode_id INT NULL,
    path_episode_name VARCHAR(255),
    client_path_episode_name VARCHAR(255),
    item2_id INT NULL,
    item_name VARCHAR(255),
    amount INT NULL,
    last_seen_in INT NULL,
    KEY ix_nf_map_path_episode_reward_episode (path_episode_id),
    KEY ix_nf_map_path_episode_reward_item (item2_id)
);

CREATE TABLE IF NOT EXISTS nf_map_path_episode_zone (
    source_relation_id INT PRIMARY KEY,
    jabbithole_path_episode_id INT NULL,
    path_episode_id INT NULL,
    path_episode_name VARCHAR(255),
    client_path_episode_name VARCHAR(255),
    jabbithole_zone_id INT NULL,
    world_zone_id INT NULL,
    zone_name VARCHAR(255),
    client_zone_name VARCHAR(255),
    map_asset VARCHAR(255),
    continent_id INT NULL,
    last_seen_in INT NULL,
    KEY ix_nf_map_path_episode_zone_episode (path_episode_id),
    KEY ix_nf_map_path_episode_zone_world_zone (world_zone_id)
);

CREATE TABLE IF NOT EXISTS nf_map_path_unlock (
    source_unlock_id INT PRIMARY KEY,
    jabbithole_player_path_id INT NULL,
    path_type INT NULL,
    path_name VARCHAR(255),
    path_level INT NULL,
    title VARCHAR(255),
    description TEXT,
    icon VARCHAR(255),
    reward_type INT NULL,
    game_id INT NULL,
    extra_data INT NULL,
    item2_id INT NULL,
    item_name VARCHAR(255),
    jabbithole_spell_id INT NULL,
    spell4_id INT NULL,
    spell_name VARCHAR(255),
    side INT NULL,
    character_title_id INT NULL,
    character_title_name VARCHAR(255),
    character_title_text VARCHAR(255),
    KEY ix_nf_map_path_unlock_path (path_type, path_level),
    KEY ix_nf_map_path_unlock_item (item2_id),
    KEY ix_nf_map_path_unlock_spell (spell4_id),
    KEY ix_nf_map_path_unlock_title (character_title_id)
);

CREATE TABLE IF NOT EXISTS nf_map_path_ability (
    source_ability_id INT PRIMARY KEY,
    jabbithole_player_path_id INT NULL,
    path_type INT NULL,
    path_name VARCHAR(255),
    jabbithole_spell_id INT NULL,
    spell4_id INT NULL,
    spell_name VARCHAR(255),
    jabbithole_base_spell_id INT NULL,
    base_spell4_id INT NULL,
    game_ability_id INT NULL,
    ability_type INT NULL,
    tier INT NULL,
    path_level INT NULL,
    cost_cash INT NULL,
    cost_point INT NULL,
    tier_bonus INT NULL,
    tier_4_bonus INT NULL,
    tier_8_bonus INT NULL,
    KEY ix_nf_map_path_ability_path (path_type, path_level),
    KEY ix_nf_map_path_ability_spell (spell4_id),
    KEY ix_nf_map_path_ability_base_spell (base_spell4_id)
);

CREATE TABLE IF NOT EXISTS nf_map_spell (
    jabbithole_spell_id INT PRIMARY KEY,
    spell4_id INT NULL,
    jabbithole_spell_name VARCHAR(255),
    client_spell_name VARCHAR(255),
    match_status VARCHAR(32),
    slug VARCHAR(255),
    tier INT NULL,
    flavor TEXT,
    cast_info VARCHAR(255),
    range_min INT NULL,
    range_max INT NULL,
    cast_cost VARCHAR(255),
    target VARCHAR(64),
    cooldown VARCHAR(255),
    mobility VARCHAR(64),
    icon VARCHAR(255),
    class_id_raw INT NULL,
    class_power INT NULL,
    combat_mode INT NULL,
    school INT NULL,
    target_angle INT NULL,
    base_jabbithole_spell_id INT NULL,
    base_spell4_id INT NULL,
    client_base_spell_name VARCHAR(255),
    charges VARCHAR(64),
    gcd_time DECIMAL(16, 13) NULL,
    enabled VARCHAR(8),
    first_seen_in INT NULL,
    last_seen_in INT NULL,
    KEY ix_nf_map_spell_spell4 (spell4_id),
    KEY ix_nf_map_spell_base (base_spell4_id),
    KEY ix_nf_map_spell_status (match_status)
);

CREATE TABLE IF NOT EXISTS nf_map_class (
    jabbithole_class_id INT PRIMARY KEY,
    class_id INT NULL,
    jabbithole_class_name VARCHAR(255),
    client_class_name VARCHAR(255),
    match_status VARCHAR(32),
    description TEXT,
    client_class_description TEXT,
    slug VARCHAR(255),
    icon VARCHAR(255),
    innate_jabbithole_spell_id INT NULL,
    innate_spell4_id INT NULL,
    innate_spell_name VARCHAR(255),
    client_innate_spell_name VARCHAR(255),
    enabled VARCHAR(8),
    KEY ix_nf_map_class_client (class_id),
    KEY ix_nf_map_class_innate_spell (innate_spell4_id)
);

CREATE TABLE IF NOT EXISTS nf_map_class_ability (
    source_ability_id INT PRIMARY KEY,
    class_id INT NULL,
    jabbithole_class_name VARCHAR(255),
    client_class_name VARCHAR(255),
    jabbithole_spell_id INT NULL,
    spell4_id INT NULL,
    jabbithole_spell_name VARCHAR(255),
    client_spell_name VARCHAR(255),
    match_status VARCHAR(32),
    base_jabbithole_spell_id INT NULL,
    base_spell4_id INT NULL,
    client_base_spell_name VARCHAR(255),
    game_ability_id INT NULL,
    ability_type INT NULL,
    tier INT NULL,
    level INT NULL,
    cost_cash INT NULL,
    cost_point INT NULL,
    is_amp VARCHAR(8),
    tier_bonus TEXT,
    tier_4_bonus TEXT,
    tier_8_bonus TEXT,
    enabled VARCHAR(8),
    KEY ix_nf_map_class_ability_class (class_id),
    KEY ix_nf_map_class_ability_spell (spell4_id),
    KEY ix_nf_map_class_ability_status (match_status)
);

CREATE TABLE IF NOT EXISTS nf_map_class_amp (
    source_amp_id INT PRIMARY KEY,
    class_id INT NULL,
    jabbithole_class_name VARCHAR(255),
    client_class_name VARCHAR(255),
    jabbithole_spell_id INT NULL,
    spell4_id INT NULL,
    jabbithole_spell_name VARCHAR(255),
    client_spell_name VARCHAR(255),
    match_status VARCHAR(32),
    parent_class_amp_id INT NULL,
    parent_amp_title VARCHAR(255),
    amp_game_id INT NULL,
    title VARCHAR(255),
    description TEXT,
    category INT NULL,
    tier INT NULL,
    column_index INT NULL,
    row_index INT NULL,
    cost INT NULL,
    item2_id INT NULL,
    item_name VARCHAR(255),
    child_class_amps_count INT NULL,
    enabled VARCHAR(8),
    KEY ix_nf_map_class_amp_class (class_id),
    KEY ix_nf_map_class_amp_spell (spell4_id),
    KEY ix_nf_map_class_amp_item (item2_id),
    KEY ix_nf_map_class_amp_status (match_status)
);

CREATE TABLE IF NOT EXISTS nf_map_class_unlock (
    source_unlock_id INT PRIMARY KEY,
    class_id INT NULL,
    jabbithole_class_name VARCHAR(255),
    client_class_name VARCHAR(255),
    level INT NULL,
    title VARCHAR(255),
    description TEXT,
    icon VARCHAR(255),
    reward_type INT NULL,
    raw_game_id INT NULL,
    jabbithole_spell_id INT NULL,
    spell4_id INT NULL,
    jabbithole_spell_name VARCHAR(255),
    client_spell_name VARCHAR(255),
    match_status VARCHAR(32),
    side INT NULL,
    enabled VARCHAR(8),
    KEY ix_nf_map_class_unlock_class (class_id, level),
    KEY ix_nf_map_class_unlock_spell (spell4_id),
    KEY ix_nf_map_class_unlock_status (match_status)
);

CREATE TABLE IF NOT EXISTS nf_map_rune_set_spell (
    source_rune_set_spell_id INT PRIMARY KEY,
    item2_id INT NULL,
    item_name VARCHAR(255),
    jabbithole_spell_id INT NULL,
    spell4_id INT NULL,
    jabbithole_spell_name VARCHAR(255),
    client_spell_name VARCHAR(255),
    match_status VARCHAR(32),
    origin_create VARCHAR(255),
    last_seen_in INT NULL,
    KEY ix_nf_map_rune_set_spell_item (item2_id),
    KEY ix_nf_map_rune_set_spell_spell (spell4_id),
    KEY ix_nf_map_rune_set_spell_status (match_status)
);

CREATE TABLE IF NOT EXISTS nf_map_achievement_group (
    jabbithole_achievement_group_id INT PRIMARY KEY,
    achievement_category_id INT NULL,
    jabbithole_group_name VARCHAR(255),
    client_category_name VARCHAR(255),
    client_category_full_name VARCHAR(255),
    match_status VARCHAR(32),
    parent_jabbithole_group_id INT NULL,
    parent_group_name VARCHAR(255),
    client_parent_category_id INT NULL,
    client_parent_category_name VARCHAR(255),
    achievements_count INT NULL,
    achievements_recursive_count INT NULL,
    child_groups_count INT NULL,
    enabled VARCHAR(8),
    last_seen_in INT NULL,
    KEY ix_nf_map_achievement_group_category (achievement_category_id),
    KEY ix_nf_map_achievement_group_parent (parent_jabbithole_group_id),
    KEY ix_nf_map_achievement_group_status (match_status)
);

CREATE TABLE IF NOT EXISTS nf_map_achievement (
    jabbithole_achievement_id INT PRIMARY KEY,
    achievement_id INT NULL,
    jabbithole_title VARCHAR(255),
    client_title VARCHAR(255),
    match_status VARCHAR(32),
    slug VARCHAR(255),
    jabbithole_description TEXT,
    client_description TEXT,
    jabbithole_description_done TEXT,
    client_progress_text TEXT,
    num_required INT NULL,
    checklist TEXT,
    is_guild VARCHAR(8),
    points INT NULL,
    tier INT NULL,
    is_dominion VARCHAR(8),
    is_exile VARCHAR(8),
    jabbithole_achievement_group_id INT NULL,
    client_group_id INT NULL,
    client_group_name VARCHAR(255),
    jabbithole_achievement_category_id INT NULL,
    client_category_id INT NULL,
    client_category_name VARCHAR(255),
    jabbithole_top_group_id INT NULL,
    jabbithole_subgroup_id INT NULL,
    client_subgroup_id INT NULL,
    client_subgroup_name VARCHAR(255),
    parent_jabbithole_achievement_id INT NULL,
    tier_root_jabbithole_achievement_id INT NULL,
    world_zone_id INT NULL,
    client_world_zone_id INT NULL,
    client_world_zone_name VARCHAR(255),
    client_achievement_type_id INT NULL,
    client_character_title_id INT NULL,
    client_character_title_name VARCHAR(255),
    child_achievements_count INT NULL,
    achievement_titles_count INT NULL,
    enabled VARCHAR(8),
    game_version INT NULL,
    first_seen_in INT NULL,
    last_seen_in INT NULL,
    KEY ix_nf_map_achievement_client (achievement_id),
    KEY ix_nf_map_achievement_status (match_status),
    KEY ix_nf_map_achievement_category (client_category_id),
    KEY ix_nf_map_achievement_title (client_character_title_id)
);

CREATE TABLE IF NOT EXISTS nf_map_achievement_title (
    source_relation_id INT PRIMARY KEY,
    jabbithole_achievement_id INT NULL,
    achievement_id INT NULL,
    jabbithole_achievement_title VARCHAR(255),
    client_achievement_title VARCHAR(255),
    character_title_id INT NULL,
    jabbithole_title_name VARCHAR(255),
    jabbithole_title_format VARCHAR(255),
    client_character_title_name VARCHAR(255),
    client_character_title_text VARCHAR(255),
    match_status VARCHAR(32),
    enabled VARCHAR(8),
    KEY ix_nf_map_achievement_title_achievement (achievement_id),
    KEY ix_nf_map_achievement_title_title (character_title_id),
    KEY ix_nf_map_achievement_title_status (match_status)
);

CREATE TABLE IF NOT EXISTS nf_map_character_achievement (
    source_character_achievement_id INT PRIMARY KEY,
    character_id INT NULL,
    jabbithole_achievement_id INT NULL,
    achievement_id INT NULL,
    jabbithole_achievement_title VARCHAR(255),
    client_achievement_title VARCHAR(255),
    match_status VARCHAR(32),
    unlocked_at INT NULL,
    KEY ix_nf_map_character_achievement_character (character_id),
    KEY ix_nf_map_character_achievement_achievement (achievement_id),
    KEY ix_nf_map_character_achievement_status (match_status)
);

CREATE TABLE IF NOT EXISTS nf_map_contract (
    jabbithole_contract_id INT PRIMARY KEY,
    contract_game_id INT NULL,
    jabbithole_quest_id INT NULL,
    quest2_id INT NULL,
    jabbithole_quest_name VARCHAR(255),
    client_quest_name VARCHAR(255),
    match_status VARCHAR(32),
    quality INT NULL,
    contract_type INT NULL,
    reward_track_type INT NULL,
    xp INT NULL,
    is_exile VARCHAR(8),
    is_dominion VARCHAR(8),
    enabled VARCHAR(8),
    first_seen_in INT NULL,
    last_seen_in INT NULL,
    KEY ix_nf_map_contract_quest (quest2_id),
    KEY ix_nf_map_contract_status (match_status)
);

CREATE TABLE IF NOT EXISTS nf_map_contract_reward (
    source_reward_id INT PRIMARY KEY,
    contract_reward_game_id INT NULL,
    item2_id INT NULL,
    item_name VARCHAR(255),
    match_status VARCHAR(32),
    tier INT NULL,
    raw_item_id INT NULL,
    asset INT NULL,
    contract_type INT NULL,
    is_casque VARCHAR(8),
    cost INT NULL,
    amount INT NULL,
    choice_idx INT NULL,
    trid INT NULL,
    is_exile VARCHAR(8),
    is_dominion VARCHAR(8),
    enabled VARCHAR(8),
    last_seen_in INT NULL,
    KEY ix_nf_map_contract_reward_item (item2_id),
    KEY ix_nf_map_contract_reward_type (contract_type, tier),
    KEY ix_nf_map_contract_reward_status (match_status)
);

CREATE TABLE IF NOT EXISTS nf_map_contract_creature (
    source_relation_id INT PRIMARY KEY,
    jabbithole_quest_id INT NULL,
    quest2_id INT NULL,
    jabbithole_quest_name VARCHAR(255),
    client_quest_name VARCHAR(255),
    jabbithole_creature_id INT NULL,
    creature2_id INT NULL,
    source_name VARCHAR(255),
    creature2_name VARCHAR(255),
    match_status VARCHAR(32),
    relation_match_status VARCHAR(32),
    enabled VARCHAR(8),
    last_seen_in INT NULL,
    KEY ix_nf_map_contract_creature_quest (quest2_id),
    KEY ix_nf_map_contract_creature_creature (creature2_id),
    KEY ix_nf_map_contract_creature_status (relation_match_status)
);

CREATE TABLE IF NOT EXISTS nf_map_housing_decor_type (
    jabbithole_decor_type_id INT PRIMARY KEY,
    housing_decor_type_id INT NULL,
    jabbithole_decor_type_name VARCHAR(255),
    client_decor_type_name VARCHAR(255),
    client_lua_string VARCHAR(255),
    match_status VARCHAR(32),
    housing_decors_count INT NULL,
    enabled VARCHAR(8),
    KEY ix_nf_map_housing_decor_type_client (housing_decor_type_id),
    KEY ix_nf_map_housing_decor_type_status (match_status)
);

CREATE TABLE IF NOT EXISTS nf_map_housing_decor (
    jabbithole_decor_id INT PRIMARY KEY,
    housing_decor_info_id INT NULL,
    jabbithole_decor_name VARCHAR(255),
    client_decor_name VARCHAR(255),
    match_status VARCHAR(32),
    slug VARCHAR(255),
    jabbithole_decor_type_id INT NULL,
    housing_decor_type_id INT NULL,
    jabbithole_decor_type_name VARCHAR(255),
    client_decor_type_name VARCHAR(255),
    currency_id INT NULL,
    cost INT NULL,
    jabbithole_spell_id INT NULL,
    spell4_id INT NULL,
    jabbithole_spell_name VARCHAR(255),
    client_spell_name VARCHAR(255),
    item2_id INT NULL,
    item_name VARCHAR(255),
    active_prop_creature2_id INT NULL,
    active_prop_creature_name VARCHAR(255),
    hook_type INT NULL,
    flags INT NULL,
    hook_asset_id INT NULL,
    enabled VARCHAR(8),
    last_seen_in INT NULL,
    KEY ix_nf_map_housing_decor_client (housing_decor_info_id),
    KEY ix_nf_map_housing_decor_type (housing_decor_type_id),
    KEY ix_nf_map_housing_decor_item (item2_id),
    KEY ix_nf_map_housing_decor_status (match_status)
);

CREATE TABLE IF NOT EXISTS nf_map_housing_enhancement (
    jabbithole_enhancement_id INT PRIMARY KEY,
    housing_plug_item_id INT NULL,
    jabbithole_enhancement_name VARCHAR(255),
    client_plug_name VARCHAR(255),
    match_status VARCHAR(32),
    slug VARCHAR(255),
    description TEXT,
    client_tooltip TEXT,
    enhancement_type INT NULL,
    parent_jabbithole_enhancement_id INT NULL,
    world_id_plug_0 INT NULL,
    world_name_plug_0 VARCHAR(255),
    next_upgrade_plug_item_id INT NULL,
    next_upgrade_plug_name VARCHAR(255),
    prerequisites TEXT,
    screenshots TEXT,
    costs TEXT,
    enabled VARCHAR(8),
    last_seen_in INT NULL,
    KEY ix_nf_map_housing_enhancement_client (housing_plug_item_id),
    KEY ix_nf_map_housing_enhancement_parent (parent_jabbithole_enhancement_id),
    KEY ix_nf_map_housing_enhancement_world (world_id_plug_0),
    KEY ix_nf_map_housing_enhancement_status (match_status)
);

CREATE TABLE IF NOT EXISTS nf_map_housing_sky (
    jabbithole_sky_id INT PRIMARY KEY,
    housing_wallpaper_info_id INT NULL,
    jabbithole_sky_name VARCHAR(255),
    client_wallpaper_name VARCHAR(255),
    match_status VARCHAR(32),
    slug VARCHAR(255),
    sky_type INT NULL,
    currency_id INT NULL,
    cost INT NULL,
    client_currency_type_id INT NULL,
    client_cost INT NULL,
    client_world_sky_id INT NULL,
    enabled VARCHAR(8),
    KEY ix_nf_map_housing_sky_client (housing_wallpaper_info_id),
    KEY ix_nf_map_housing_sky_status (match_status)
);

CREATE TABLE IF NOT EXISTS nf_map_dye (
    jabbithole_dye_id INT PRIMARY KEY,
    dye_color_ramp_id INT NULL,
    jabbithole_dye_name VARCHAR(255),
    client_dye_name VARCHAR(255),
    match_status VARCHAR(32),
    slug VARCHAR(255),
    ramp_id INT NULL,
    client_ramp_index INT NULL,
    multiplier FLOAT NULL,
    client_cost_multiplier FLOAT NULL,
    enabled VARCHAR(8),
    first_seen_in INT NULL,
    KEY ix_nf_map_dye_client (dye_color_ramp_id),
    KEY ix_nf_map_dye_status (match_status)
);

CREATE TABLE IF NOT EXISTS nf_map_flair (
    jabbithole_flair_id INT PRIMARY KEY,
    pet_flair_id INT NULL,
    jabbithole_flair_name VARCHAR(255),
    client_flair_tooltip TEXT,
    match_status VARCHAR(32),
    slug VARCHAR(255),
    flair_type INT NULL,
    game_spell4_id INT NULL,
    client_spell4_id INT NULL,
    jabbithole_spell_id INT NULL,
    jabbithole_spell_name VARCHAR(255),
    client_spell_name VARCHAR(255),
    description TEXT,
    enabled VARCHAR(8),
    first_seen_in INT NULL,
    KEY ix_nf_map_flair_client (pet_flair_id),
    KEY ix_nf_map_flair_spell (client_spell4_id),
    KEY ix_nf_map_flair_status (match_status)
);

CREATE TABLE IF NOT EXISTS nf_map_mount (
    jabbithole_mount_id INT PRIMARY KEY,
    base_spell4_id INT NULL,
    base_spell_name VARCHAR(255),
    mount_name VARCHAR(255),
    description TEXT,
    slug VARCHAR(255),
    match_status VARCHAR(32),
    can_customize VARCHAR(8),
    is_hoverboard VARCHAR(8),
    is_rental_mount VARCHAR(8),
    preview_creature2_id INT NULL,
    preview_creature_name VARCHAR(255),
    preview_hoverboard_item2_id INT NULL,
    preview_hoverboard_item_name VARCHAR(255),
    secondary_bars VARCHAR(8),
    summon_spell4_id INT NULL,
    summon_spell_name VARCHAR(255),
    jabbithole_spell_id INT NULL,
    enabled VARCHAR(8),
    first_seen_in INT NULL,
    KEY ix_nf_map_mount_base_spell (base_spell4_id),
    KEY ix_nf_map_mount_summon_spell (summon_spell4_id),
    KEY ix_nf_map_mount_preview_creature (preview_creature2_id),
    KEY ix_nf_map_mount_status (match_status)
);

CREATE TABLE IF NOT EXISTS nf_map_pet (
    jabbithole_pet_id INT PRIMARY KEY,
    base_spell4_id INT NULL,
    base_spell_name VARCHAR(255),
    pet_name VARCHAR(255),
    description TEXT,
    slug VARCHAR(255),
    match_status VARCHAR(32),
    preview_creature2_id INT NULL,
    preview_creature_name VARCHAR(255),
    secondary_bars VARCHAR(8),
    summon_spell4_id INT NULL,
    summon_spell_name VARCHAR(255),
    jabbithole_spell_id INT NULL,
    enabled VARCHAR(8),
    first_seen_in INT NULL,
    KEY ix_nf_map_pet_base_spell (base_spell4_id),
    KEY ix_nf_map_pet_summon_spell (summon_spell4_id),
    KEY ix_nf_map_pet_preview_creature (preview_creature2_id),
    KEY ix_nf_map_pet_status (match_status)
);

CREATE TABLE IF NOT EXISTS nf_map_title (
    character_title_id INT PRIMARY KEY,
    title_name VARCHAR(255),
    client_title_name VARCHAR(255),
    client_title_text VARCHAR(255),
    match_status VARCHAR(32),
    slug VARCHAR(255),
    title_group VARCHAR(255),
    title_format VARCHAR(255),
    client_title_category_id INT NULL,
    client_title_category_name VARCHAR(255),
    jabbithole_path_unlock_id INT NULL,
    achievement_titles_count INT NULL,
    path_unlocks_count INT NULL,
    is_dominion VARCHAR(8),
    is_exile VARCHAR(8),
    enabled VARCHAR(8),
    first_seen_in INT NULL,
    last_seen_in INT NULL,
    KEY ix_nf_map_title_status (match_status),
    KEY ix_nf_map_title_category (client_title_category_id),
    KEY ix_nf_map_title_path_unlock (jabbithole_path_unlock_id)
);

CREATE TABLE IF NOT EXISTS nf_map_schematic (
    jabbithole_schematic_id INT PRIMARY KEY,
    tradeskill_schematic2_id INT NULL,
    jabbithole_schematic_name VARCHAR(255),
    client_schematic_name VARCHAR(255),
    match_status VARCHAR(32),
    slug VARCHAR(255),
    jabbithole_tradeskill_id INT NULL,
    trade_skill_id INT NULL,
    jabbithole_tradeskill_name VARCHAR(255),
    client_trade_skill_id INT NULL,
    client_tradeskill_name VARCHAR(255),
    jabbithole_output_item_id INT NULL,
    jabbithole_output_item_name VARCHAR(255),
    client_output_item2_id INT NULL,
    client_output_item_name VARCHAR(255),
    client_fail_item2_id INT NULL,
    client_fail_item_name VARCHAR(255),
    parent_jabbithole_schematic_id INT NULL,
    client_parent_schematic2_id INT NULL,
    client_parent_schematic_name VARCHAR(255),
    taught_by_item_id INT NULL,
    taught_by_item_name VARCHAR(255),
    tier INT NULL,
    xp_learn INT NULL,
    xp_craft INT NULL,
    xp_fail INT NULL,
    create_count INT NULL,
    create_crit_count INT NULL,
    max_additives INT NULL,
    max_catalysts INT NULL,
    sockets TEXT,
    schematic_materials_count INT NULL,
    child_schematics_count INT NULL,
    techtree_schematics_count INT NULL,
    is_autocraft VARCHAR(8),
    is_autolearn VARCHAR(8),
    is_oneuse VARCHAR(8),
    slots_resistor INT NULL,
    slots_capacitor INT NULL,
    slots_inductor INT NULL,
    slots_rnd_spec INT NULL,
    slots_lck_spec INT NULL,
    slots_rnd_attr INT NULL,
    slots_lck_attr INT NULL,
    schematic_microchips_count INT NULL,
    schematic_circuits_count INT NULL,
    material_cache TEXT,
    is_universal INT NULL,
    stats TEXT,
    enabled VARCHAR(8),
    first_seen_in INT NULL,
    last_seen_in INT NULL,
    KEY ix_nf_map_schematic_client (tradeskill_schematic2_id),
    KEY ix_nf_map_schematic_trade (trade_skill_id),
    KEY ix_nf_map_schematic_output (client_output_item2_id),
    KEY ix_nf_map_schematic_status (match_status)
);

CREATE TABLE IF NOT EXISTS nf_map_schematic_material (
    source_relation_id INT PRIMARY KEY,
    jabbithole_schematic_id INT NULL,
    tradeskill_schematic2_id INT NULL,
    jabbithole_schematic_name VARCHAR(255),
    client_schematic_name VARCHAR(255),
    jabbithole_tradeskill_id INT NULL,
    trade_skill_id INT NULL,
    jabbithole_tradeskill_name VARCHAR(255),
    client_tradeskill_name VARCHAR(255),
    item2_id INT NULL,
    item_name VARCHAR(255),
    amount INT NULL,
    match_status VARCHAR(32),
    schematic_match_status VARCHAR(32),
    item_match_status VARCHAR(32),
    enabled VARCHAR(8),
    last_seen_in INT NULL,
    KEY ix_nf_map_schematic_material_schematic (tradeskill_schematic2_id),
    KEY ix_nf_map_schematic_material_item (item2_id),
    KEY ix_nf_map_schematic_material_status (match_status)
);

CREATE TABLE IF NOT EXISTS nf_map_schematic_circuit (
    source_relation_id INT PRIMARY KEY,
    component_type VARCHAR(32),
    jabbithole_schematic_id INT NULL,
    tradeskill_schematic2_id INT NULL,
    jabbithole_schematic_name VARCHAR(255),
    client_schematic_name VARCHAR(255),
    jabbithole_tradeskill_id INT NULL,
    trade_skill_id INT NULL,
    jabbithole_tradeskill_name VARCHAR(255),
    client_tradeskill_name VARCHAR(255),
    item2_id INT NULL,
    item_name VARCHAR(255),
    match_status VARCHAR(32),
    schematic_match_status VARCHAR(32),
    item_match_status VARCHAR(32),
    origin_create VARCHAR(255),
    last_seen_in INT NULL,
    KEY ix_nf_map_schematic_circuit_schematic (tradeskill_schematic2_id),
    KEY ix_nf_map_schematic_circuit_item (item2_id),
    KEY ix_nf_map_schematic_circuit_status (match_status)
);

CREATE TABLE IF NOT EXISTS nf_map_schematic_microchip (
    source_relation_id INT PRIMARY KEY,
    component_type VARCHAR(32),
    jabbithole_schematic_id INT NULL,
    tradeskill_schematic2_id INT NULL,
    jabbithole_schematic_name VARCHAR(255),
    client_schematic_name VARCHAR(255),
    jabbithole_tradeskill_id INT NULL,
    trade_skill_id INT NULL,
    jabbithole_tradeskill_name VARCHAR(255),
    client_tradeskill_name VARCHAR(255),
    item2_id INT NULL,
    item_name VARCHAR(255),
    match_status VARCHAR(32),
    schematic_match_status VARCHAR(32),
    item_match_status VARCHAR(32),
    origin_create VARCHAR(255),
    last_seen_in INT NULL,
    KEY ix_nf_map_schematic_microchip_schematic (tradeskill_schematic2_id),
    KEY ix_nf_map_schematic_microchip_item (item2_id),
    KEY ix_nf_map_schematic_microchip_status (match_status)
);

CREATE TABLE IF NOT EXISTS nf_map_tradeskill_talent_tier (
    jabbithole_talent_tier_id INT PRIMARY KEY,
    client_tradeskill_talent_tier_id INT NULL,
    jabbithole_tradeskill_id INT NULL,
    trade_skill_id INT NULL,
    jabbithole_tradeskill_name VARCHAR(255),
    client_tradeskill_name VARCHAR(255),
    level INT NULL,
    points_required INT NULL,
    client_points_to_unlock INT NULL,
    client_respec_cost BIGINT NULL,
    client_bonus_ids TEXT,
    client_bonus_names TEXT,
    tradeskill_talents_count INT NULL,
    match_status VARCHAR(32),
    enabled VARCHAR(8),
    KEY ix_nf_map_tradeskill_talent_tier_client (client_tradeskill_talent_tier_id),
    KEY ix_nf_map_tradeskill_talent_tier_trade (trade_skill_id),
    KEY ix_nf_map_tradeskill_talent_tier_status (match_status)
);

CREATE TABLE IF NOT EXISTS nf_map_tradeskill_talent (
    jabbithole_talent_id INT PRIMARY KEY,
    tradeskill_bonus_id INT NULL,
    jabbithole_talent_name VARCHAR(255),
    client_bonus_name VARCHAR(255),
    client_bonus_tooltip TEXT,
    match_status VARCHAR(32),
    jabbithole_talent_tier_id INT NULL,
    client_tradeskill_talent_tier_id INT NULL,
    jabbithole_tradeskill_id INT NULL,
    trade_skill_id INT NULL,
    jabbithole_tradeskill_name VARCHAR(255),
    client_tradeskill_name VARCHAR(255),
    level INT NULL,
    points_required INT NULL,
    talent_order INT NULL,
    icon VARCHAR(255),
    client_icon VARCHAR(1024),
    description TEXT,
    client_achievement_id INT NULL,
    client_achievement_title VARCHAR(255),
    bonus_enums VARCHAR(255),
    primary_objects VARCHAR(255),
    secondary_objects VARCHAR(255),
    tertiary_objects VARCHAR(255),
    `values` VARCHAR(255),
    integer_values VARCHAR(255),
    enabled VARCHAR(8),
    KEY ix_nf_map_tradeskill_talent_bonus (tradeskill_bonus_id),
    KEY ix_nf_map_tradeskill_talent_tier (client_tradeskill_talent_tier_id),
    KEY ix_nf_map_tradeskill_talent_trade (trade_skill_id),
    KEY ix_nf_map_tradeskill_talent_status (match_status)
);

CREATE TABLE IF NOT EXISTS nf_map_tradeskill_techtree_group (
    jabbithole_techtree_group_id INT PRIMARY KEY,
    achievement_category_id INT NULL,
    jabbithole_group_name VARCHAR(255),
    client_category_name VARCHAR(255),
    client_category_full_name VARCHAR(255),
    match_status VARCHAR(32),
    client_parent_category_id INT NULL,
    client_parent_category_name VARCHAR(255),
    jabbithole_tradeskill_id INT NULL,
    trade_skill_id INT NULL,
    jabbithole_tradeskill_name VARCHAR(255),
    client_tradeskill_name VARCHAR(255),
    level INT NULL,
    side INT NULL,
    techtree_items_count INT NULL,
    enabled VARCHAR(8),
    KEY ix_nf_map_tradeskill_techtree_group_category (achievement_category_id),
    KEY ix_nf_map_tradeskill_techtree_group_trade (trade_skill_id),
    KEY ix_nf_map_tradeskill_techtree_group_status (match_status)
);

CREATE TABLE IF NOT EXISTS nf_map_tradeskill_techtree_item (
    jabbithole_techtree_item_id INT PRIMARY KEY,
    achievement_id INT NULL,
    jabbithole_techtree_item_name VARCHAR(255),
    client_achievement_title VARCHAR(255),
    match_status VARCHAR(32),
    progress_description TEXT,
    client_achievement_progress TEXT,
    description TEXT,
    client_achievement_description TEXT,
    num_needed INT NULL,
    achievement_points INT NULL,
    client_achievement_category_id INT NULL,
    client_achievement_category_name VARCHAR(255),
    jabbithole_techtree_group_id INT NULL,
    achievement_category_id INT NULL,
    jabbithole_group_name VARCHAR(255),
    client_group_category_name VARCHAR(255),
    jabbithole_tradeskill_id INT NULL,
    trade_skill_id INT NULL,
    jabbithole_tradeskill_name VARCHAR(255),
    client_tradeskill_name VARCHAR(255),
    location_parents TEXT,
    location_x INT NULL,
    location_y INT NULL,
    bonuses TEXT,
    bonus_talent_points INT NULL,
    checklist TEXT,
    techtree_schematics_count INT NULL,
    enabled VARCHAR(8),
    KEY ix_nf_map_tradeskill_techtree_item_achievement (achievement_id),
    KEY ix_nf_map_tradeskill_techtree_item_group (achievement_category_id),
    KEY ix_nf_map_tradeskill_techtree_item_trade (trade_skill_id),
    KEY ix_nf_map_tradeskill_techtree_item_status (match_status)
);

CREATE TABLE IF NOT EXISTS nf_map_tradeskill_techtree_schematic (
    source_relation_id INT PRIMARY KEY,
    jabbithole_techtree_item_id INT NULL,
    achievement_id INT NULL,
    jabbithole_techtree_item_name VARCHAR(255),
    client_achievement_title VARCHAR(255),
    jabbithole_techtree_group_id INT NULL,
    achievement_category_id INT NULL,
    jabbithole_group_name VARCHAR(255),
    client_group_category_name VARCHAR(255),
    jabbithole_tradeskill_id INT NULL,
    trade_skill_id INT NULL,
    jabbithole_tradeskill_name VARCHAR(255),
    client_tradeskill_name VARCHAR(255),
    jabbithole_schematic_id INT NULL,
    tradeskill_schematic2_id INT NULL,
    jabbithole_schematic_name VARCHAR(255),
    client_schematic_name VARCHAR(255),
    jabbithole_output_item_id INT NULL,
    jabbithole_output_item_name VARCHAR(255),
    client_output_item2_id INT NULL,
    client_output_item_name VARCHAR(255),
    match_status VARCHAR(32),
    achievement_match_status VARCHAR(32),
    schematic_match_status VARCHAR(32),
    enabled VARCHAR(8),
    KEY ix_nf_map_tradeskill_techtree_schematic_achievement (achievement_id),
    KEY ix_nf_map_tradeskill_techtree_schematic_schematic (tradeskill_schematic2_id),
    KEY ix_nf_map_tradeskill_techtree_schematic_trade (trade_skill_id),
    KEY ix_nf_map_tradeskill_techtree_schematic_status (match_status)
);

CREATE TABLE IF NOT EXISTS nf_map_continent (
    jabbithole_continent_id INT PRIMARY KEY,
    map_continent_id INT NULL,
    jabbithole_continent_name VARCHAR(255),
    client_continent_name VARCHAR(255),
    match_status VARCHAR(32),
    slug VARCHAR(255),
    map_asset VARCHAR(255),
    client_asset_path VARCHAR(255),
    client_image_path VARCHAR(255),
    `show` VARCHAR(8),
    zones_count INT NULL,
    enabled VARCHAR(8),
    last_seen_in INT NULL,
    KEY ix_nf_map_continent_client (map_continent_id),
    KEY ix_nf_map_continent_status (match_status)
);

CREATE TABLE IF NOT EXISTS nf_map_mapzone_poi (
    source_poi_id INT PRIMARY KEY,
    map_zone_id INT NULL,
    map_zone_name VARCHAR(255),
    map_zone_poi_id INT NULL,
    match_status VARCHAR(32),
    jabbithole_poi_name VARCHAR(255),
    client_poi_name VARCHAR(255),
    icon VARCHAR(255),
    map_zone_sprite_id INT NULL,
    client_sprite_name VARCHAR(255),
    x INT NULL,
    y INT NULL,
    z INT NULL,
    client_x INT NULL,
    client_y INT NULL,
    client_z INT NULL,
    created_at DATETIME NULL,
    updated_at DATETIME NULL,
    KEY ix_nf_map_mapzone_poi_zone (map_zone_id),
    KEY ix_nf_map_mapzone_poi_client (map_zone_poi_id),
    KEY ix_nf_map_mapzone_poi_status (match_status)
);

CREATE TABLE IF NOT EXISTS nf_map_quest_category (
    jabbithole_category_id INT PRIMARY KEY,
    quest_category_id INT NULL,
    jabbithole_category_name VARCHAR(255),
    client_category_name VARCHAR(255),
    match_status VARCHAR(32),
    client_description VARCHAR(255),
    category_type INT NULL,
    slug VARCHAR(255),
    quests_count INT NULL,
    enabled VARCHAR(8),
    last_seen_in INT NULL,
    KEY ix_nf_map_quest_category_client (quest_category_id),
    KEY ix_nf_map_quest_category_status (match_status)
);

CREATE TABLE IF NOT EXISTS nf_map_quest_episode (
    jabbithole_episode_id INT PRIMARY KEY,
    episode_id INT NULL,
    jabbithole_episode_name VARCHAR(255),
    client_episode_name VARCHAR(255),
    match_status VARCHAR(32),
    client_world_zone_id INT NULL,
    client_world_zone_name VARCHAR(255),
    slug VARCHAR(255),
    quests_count INT NULL,
    enabled VARCHAR(8),
    last_seen_in INT NULL,
    KEY ix_nf_map_quest_episode_client (episode_id),
    KEY ix_nf_map_quest_episode_world_zone (client_world_zone_id),
    KEY ix_nf_map_quest_episode_status (match_status)
);

CREATE TABLE IF NOT EXISTS nf_map_quest_zone (
    source_relation_id INT NOT NULL,
    relation_source VARCHAR(32) NOT NULL,
    jabbithole_quest_id INT NULL,
    quest2_id INT NULL,
    jabbithole_quest_name VARCHAR(255),
    client_quest_name VARCHAR(255),
    jabbithole_zone_id INT NULL,
    world_zone_id INT NULL,
    jabbithole_zone_name VARCHAR(255),
    client_world_zone_name VARCHAR(255),
    match_status VARCHAR(32),
    enabled VARCHAR(8),
    last_seen_in INT NULL,
    PRIMARY KEY (relation_source, source_relation_id),
    KEY ix_nf_map_quest_zone_quest (quest2_id),
    KEY ix_nf_map_quest_zone_world_zone (world_zone_id),
    KEY ix_nf_map_quest_zone_status (match_status)
);

CREATE TABLE IF NOT EXISTS nf_map_faction (
    jabbithole_faction_id INT PRIMARY KEY,
    source_game_id INT NULL,
    faction2_id INT NULL,
    jabbithole_faction_name VARCHAR(255),
    client_faction_name VARCHAR(255),
    match_status VARCHAR(32),
    slug VARCHAR(255),
    faction_group VARCHAR(255),
    parent_name VARCHAR(255),
    parent_faction2_id INT NULL,
    client_parent_faction_name VARCHAR(255),
    parent_match_status VARCHAR(32),
    is_dominion VARCHAR(8),
    is_exile VARCHAR(8),
    faction_reward_items_count INT NULL,
    enabled VARCHAR(8),
    first_seen_in INT NULL,
    last_seen_in INT NULL,
    KEY ix_nf_map_faction_client (faction2_id),
    KEY ix_nf_map_faction_status (match_status)
);

CREATE TABLE IF NOT EXISTS nf_map_faction_reward_item (
    source_relation_id INT PRIMARY KEY,
    jabbithole_faction_id INT NULL,
    source_faction_game_id INT NULL,
    faction2_id INT NULL,
    jabbithole_faction_name VARCHAR(255),
    client_faction_name VARCHAR(255),
    jabbithole_item_id INT NULL,
    item2_id INT NULL,
    item_name VARCHAR(255),
    required_reputation INT NULL,
    match_status VARCHAR(32),
    enabled VARCHAR(8),
    last_seen_in INT NULL,
    KEY ix_nf_map_faction_reward_faction (faction2_id),
    KEY ix_nf_map_faction_reward_item (item2_id),
    KEY ix_nf_map_faction_reward_status (match_status)
);

CREATE TABLE IF NOT EXISTS nf_map_attribute_contribution (
    source_relation_id INT PRIMARY KEY,
    primary_jabbithole_attribute_id INT NULL,
    primary_unit_property2_id INT NULL,
    primary_attribute_name VARCHAR(255),
    primary_client_attribute_name VARCHAR(255),
    primary_client_attribute_enum VARCHAR(255),
    secondary_jabbithole_attribute_id INT NULL,
    secondary_unit_property2_id INT NULL,
    secondary_attribute_name VARCHAR(255),
    secondary_client_attribute_name VARCHAR(255),
    secondary_client_attribute_enum VARCHAR(255),
    jabbithole_player_class_id INT NULL,
    class_id INT NULL,
    class_name VARCHAR(255),
    client_class_name VARCHAR(255),
    contribution DOUBLE NULL,
    match_status VARCHAR(32),
    enabled VARCHAR(8),
    KEY ix_nf_map_attribute_contribution_class (class_id),
    KEY ix_nf_map_attribute_contribution_primary (primary_unit_property2_id),
    KEY ix_nf_map_attribute_contribution_secondary (secondary_unit_property2_id),
    KEY ix_nf_map_attribute_contribution_status (match_status)
);

CREATE TABLE IF NOT EXISTS nf_map_attribute_milestone (
    source_relation_id INT PRIMARY KEY,
    primary_jabbithole_attribute_id INT NULL,
    primary_unit_property2_id INT NULL,
    primary_attribute_name VARCHAR(255),
    primary_client_attribute_name VARCHAR(255),
    primary_client_attribute_enum VARCHAR(255),
    secondary_jabbithole_attribute_id INT NULL,
    secondary_unit_property2_id INT NULL,
    secondary_attribute_name VARCHAR(255),
    secondary_client_attribute_name VARCHAR(255),
    secondary_client_attribute_enum VARCHAR(255),
    jabbithole_player_class_id INT NULL,
    class_id INT NULL,
    class_name VARCHAR(255),
    client_class_name VARCHAR(255),
    required_amount INT NULL,
    contribution DOUBLE NULL,
    match_status VARCHAR(32),
    enabled VARCHAR(8),
    KEY ix_nf_map_attribute_milestone_class (class_id),
    KEY ix_nf_map_attribute_milestone_primary (primary_unit_property2_id),
    KEY ix_nf_map_attribute_milestone_secondary (secondary_unit_property2_id),
    KEY ix_nf_map_attribute_milestone_status (match_status)
);

CREATE TABLE IF NOT EXISTS nf_map_item_instance_sigil (
    source_relation_id INT PRIMARY KEY,
    item2_id INT NULL,
    item_name VARCHAR(255),
    sigil INT NULL,
    sigil_order INT NULL,
    match_status VARCHAR(32),
    enabled VARCHAR(8),
    created_at DATETIME NULL,
    updated_at DATETIME NULL,
    KEY ix_nf_map_item_instance_sigil_item (item2_id),
    KEY ix_nf_map_item_instance_sigil_status (match_status)
);

CREATE TABLE IF NOT EXISTS nf_map_legacy_vendor_item (
    source_relation_id INT PRIMARY KEY,
    jabbithole_creature_id INT NULL,
    creature2_id INT NULL,
    source_name VARCHAR(255),
    creature2_name VARCHAR(255),
    match_status VARCHAR(32),
    raw_item_id INT NULL,
    item2_id INT NULL,
    item_name VARCHAR(255),
    main_jabbithole_currency_id INT NULL,
    main_currency_type_id INT NULL,
    main_currency_name VARCHAR(255),
    client_main_currency_name VARCHAR(255),
    alt_jabbithole_currency_id INT NULL,
    alt_currency_type_id INT NULL,
    alt_currency_name VARCHAR(255),
    client_alt_currency_name VARCHAR(255),
    special_item VARCHAR(8),
    stack_size INT NULL,
    stock_size INT NULL,
    main_price BIGINT NULL,
    alt_price BIGINT NULL,
    prerequisite TEXT,
    enabled VARCHAR(8),
    last_seen_in INT NULL,
    KEY ix_nf_map_legacy_vendor_creature (creature2_id),
    KEY ix_nf_map_legacy_vendor_item (item2_id),
    KEY ix_nf_map_legacy_vendor_status (match_status)
);

CREATE TABLE IF NOT EXISTS nf_map_item_drop_aggregate (
    source_aggregate_id INT PRIMARY KEY,
    raw_item_id INT NULL,
    item2_id INT NULL,
    item_name VARCHAR(255),
    match_status VARCHAR(32),
    versioned_item_drops_count INT NULL,
    game_version INT NULL,
    last_seen_in INT NULL,
    origin_create VARCHAR(255),
    origin_update VARCHAR(255),
    origin_before VARCHAR(255),
    created_at DATETIME NULL,
    updated_at DATETIME NULL,
    KEY ix_nf_map_item_drop_aggregate_item (item2_id),
    KEY ix_nf_map_item_drop_aggregate_status (match_status)
);

CREATE TABLE IF NOT EXISTS nf_map_character_snapshot (
    character_id INT PRIMARY KEY,
    character_name VARCHAR(255),
    fullname VARCHAR(255),
    realm_name VARCHAR(255),
    guild_name VARCHAR(255),
    jabbithole_player_class_id INT NULL,
    class_id INT NULL,
    client_class_name VARCHAR(255),
    class_level INT NULL,
    jabbithole_player_path_id INT NULL,
    path_type INT NULL,
    path_name VARCHAR(255),
    path_level INT NULL,
    faction2_id INT NULL,
    client_faction_name VARCHAR(255),
    gender INT NULL,
    race INT NULL,
    gear_score DOUBLE NULL,
    equipped_item_count INT NULL,
    build_ability_count INT NULL,
    amps TEXT,
    unified_build_key VARCHAR(255),
    unified_abilities_key VARCHAR(255),
    achievement_points INT NULL,
    ability_points_total INT NULL,
    amp_points_total INT NULL,
    match_status VARCHAR(32),
    enabled VARCHAR(8),
    created_at DATETIME NULL,
    updated_at DATETIME NULL,
    KEY ix_nf_map_character_snapshot_class (class_id),
    KEY ix_nf_map_character_snapshot_faction (faction2_id),
    KEY ix_nf_map_character_snapshot_status (match_status)
);

CREATE TABLE IF NOT EXISTS nf_map_character_item (
    character_id INT NOT NULL,
    character_name VARCHAR(255),
    equipment_slot_index INT NOT NULL,
    item2_id INT NULL,
    item_name VARCHAR(255),
    match_status VARCHAR(32),
    PRIMARY KEY (character_id, equipment_slot_index),
    KEY ix_nf_map_character_item_item (item2_id),
    KEY ix_nf_map_character_item_status (match_status)
);

CREATE TABLE IF NOT EXISTS nf_map_character_build_ability (
    character_id INT NOT NULL,
    character_name VARCHAR(255),
    build_slot_index INT NOT NULL,
    spell4_id INT NULL,
    spell_name VARCHAR(255),
    tier INT NULL,
    match_status VARCHAR(32),
    PRIMARY KEY (character_id, build_slot_index),
    KEY ix_nf_map_character_build_spell (spell4_id),
    KEY ix_nf_map_character_build_status (match_status)
);

CREATE TABLE IF NOT EXISTS nf_map_schema_migration (
    version BIGINT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS nf_map_empty_items_split (
    source_file VARCHAR(255) PRIMARY KEY,
    row_count INT NULL,
    notes TEXT
);

CREATE TABLE IF NOT EXISTS nf_map_unknown_table_loot (
    source_relation_id INT PRIMARY KEY,
    item2_id INT NULL,
    item_name VARCHAR(255),
    jabbithole_creature_id INT NULL,
    creature2_id INT NULL,
    source_name VARCHAR(255),
    creature2_name VARCHAR(255),
    match_status VARCHAR(32),
    row_match_status VARCHAR(32),
    npc_type VARCHAR(255),
    zone_name VARCHAR(255),
    drop_percent DOUBLE NULL,
    drop_count VARCHAR(255),
    npc_url VARCHAR(255),
    version INT NULL,
    raw_item_name VARCHAR(255),
    raw_item_family VARCHAR(255),
    raw_item_category VARCHAR(255),
    raw_item_slot VARCHAR(255),
    KEY ix_nf_map_unknown_table_loot_item (item2_id),
    KEY ix_nf_map_unknown_table_loot_creature (creature2_id),
    KEY ix_nf_map_unknown_table_loot_status (row_match_status)
);
