// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexusForever.Database.Group;

#nullable disable

namespace NexusForever.Database.Sqlite.Migrations.Group
{
    [DbContext(typeof(GroupContext))]
    [Migration("20260607222210_GroupSqliteInitial")]
    partial class GroupSqliteInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.16");

            modelBuilder.Entity("NexusForever.Database.Group.Model.CharacterGroupModel", b =>
                {
                    b.Property<ulong>("CharacterId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("characterId");

                    b.Property<ushort>("RealmId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("realmId");

                    b.Property<ulong>("GroupId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("groupId");

                    b.Property<uint>("Index")
                        .HasColumnType("INTEGER")
                        .HasColumnName("index");

                    b.HasKey("CharacterId", "RealmId", "GroupId");

                    b.HasIndex("CharacterId", "RealmId");

                    b.HasIndex("CharacterId", "RealmId", "Index")
                        .IsUnique();

                    b.HasIndex("GroupId", "CharacterId", "RealmId")
                        .IsUnique();

                    b.ToTable("character_group", null, t =>
                        {
                            t.HasCheckConstraint("CK_character_group_onlytwogroups", "`index` < 2");
                        });
                });

            modelBuilder.Entity("NexusForever.Database.Group.Model.CharacterModel", b =>
                {
                    b.Property<ulong>("CharacterId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("characterId");

                    b.Property<ushort>("RealmId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("realmId");

                    b.Property<byte>("Class")
                        .HasColumnType("INTEGER")
                        .HasColumnName("class");

                    b.Property<ushort>("CurrentRealm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("currentRealm");

                    b.Property<uint>("Faction")
                        .HasColumnType("INTEGER")
                        .HasColumnName("faction");

                    b.Property<uint>("MapId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mapId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<byte>("Path")
                        .HasColumnType("INTEGER")
                        .HasColumnName("path");

                    b.Property<float>("PositionX")
                        .HasColumnType("REAL")
                        .HasColumnName("positionX");

                    b.Property<float>("PositionY")
                        .HasColumnType("REAL")
                        .HasColumnName("positionY");

                    b.Property<float>("PositionZ")
                        .HasColumnType("REAL")
                        .HasColumnName("positionZ");

                    b.Property<byte>("Race")
                        .HasColumnType("INTEGER")
                        .HasColumnName("race");

                    b.Property<bool>("RealmDirty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("realmDirty");

                    b.Property<string>("RealmName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("realmName");

                    b.Property<byte>("Sex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sex");

                    b.Property<bool>("StatsDirty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("statsDirty");

                    b.Property<ushort>("WorldZoneId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("worldZoneId");

                    b.HasKey("CharacterId", "RealmId")
                        .HasName("PRIMARY");

                    b.ToTable("character", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.Group.Model.CharacterPropertyModel", b =>
                {
                    b.Property<ulong>("CharacterId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("characterId");

                    b.Property<ushort>("RealmId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("realmId");

                    b.Property<byte>("Property")
                        .HasColumnType("INTEGER")
                        .HasColumnName("property");

                    b.Property<float>("Value")
                        .HasColumnType("REAL")
                        .HasColumnName("value");

                    b.HasKey("CharacterId", "RealmId", "Property")
                        .HasName("PRIMARY");

                    b.HasIndex("CharacterId", "RealmId");

                    b.ToTable("character_property", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.Group.Model.CharacterStatModel", b =>
                {
                    b.Property<ulong>("CharacterId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("characterId");

                    b.Property<ushort>("RealmId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("realmId");

                    b.Property<byte>("Stat")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stat");

                    b.Property<float>("Value")
                        .HasColumnType("REAL")
                        .HasColumnName("value");

                    b.HasKey("CharacterId", "RealmId", "Stat")
                        .HasName("PRIMARY");

                    b.HasIndex("CharacterId", "RealmId");

                    b.ToTable("character_stat", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.Group.Model.GroupInviteModel", b =>
                {
                    b.Property<ulong>("GroupId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("groupId");

                    b.Property<ulong>("InviteeCharacterId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("inviteeCharacterId");

                    b.Property<ushort>("InviteeRealmId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("inviteeRealmId");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("TEXT")
                        .HasColumnName("expiration");

                    b.Property<ulong>("InviterCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("InviterRealmId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("inviterRealmId");

                    b.HasKey("GroupId", "InviteeCharacterId", "InviteeRealmId")
                        .HasName("PRIMARY");

                    b.HasIndex("GroupId");

                    b.HasIndex("InviteeCharacterId", "InviteeRealmId")
                        .IsUnique();

                    b.ToTable("group_invite", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.Group.Model.GroupLeaderModel", b =>
                {
                    b.Property<ulong>("GroupId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("groupId");

                    b.Property<ulong>("CharacterId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("characterId");

                    b.Property<ushort>("RealmId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("realmId");

                    b.HasKey("GroupId")
                        .HasName("PRIMARY");

                    b.HasIndex("GroupId", "CharacterId", "RealmId")
                        .IsUnique();

                    b.ToTable("group_leader", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.Group.Model.GroupMarkerModel", b =>
                {
                    b.Property<ulong>("GroupId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("groupId");

                    b.Property<int>("Marker")
                        .HasColumnType("INTEGER")
                        .HasColumnName("marker");

                    b.Property<uint>("UnitId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("unitId");

                    b.HasKey("GroupId", "Marker")
                        .HasName("PRIMARY");

                    b.HasIndex("GroupId");

                    b.HasIndex("GroupId", "UnitId")
                        .IsUnique();

                    b.ToTable("group_marker", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.Group.Model.GroupMemberModel", b =>
                {
                    b.Property<ulong>("GroupId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("groupId");

                    b.Property<ulong>("CharacterId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("characterId");

                    b.Property<ushort>("RealmId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("realmId");

                    b.Property<uint>("Flags")
                        .HasColumnType("INTEGER")
                        .HasColumnName("flags");

                    b.Property<uint>("Index")
                        .HasColumnType("INTEGER")
                        .HasColumnName("index");

                    b.Property<bool>("PositionDirty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("positionDirty");

                    b.HasKey("GroupId", "CharacterId", "RealmId")
                        .HasName("PRIMARY");

                    b.HasIndex("GroupId");

                    b.HasIndex("CharacterId", "RealmId");

                    b.HasIndex("GroupId", "Index")
                        .IsUnique();

                    b.ToTable("group_member", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.Group.Model.GroupModel", b =>
                {
                    b.Property<ulong>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("groupId");

                    b.Property<uint>("Flags")
                        .HasColumnType("INTEGER")
                        .HasColumnName("flags");

                    b.Property<byte>("LootRule")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lootRule");

                    b.Property<byte>("LootRuleHarvest")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lootRuleHarvest");

                    b.Property<byte>("LootRuleThreshold")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lootRuleThreshold");

                    b.Property<byte>("LootThreshold")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lootThreshold");

                    b.Property<Guid?>("Match")
                        .HasColumnType("TEXT")
                        .HasColumnName("match");

                    b.Property<int?>("MatchTeam")
                        .HasColumnType("INTEGER")
                        .HasColumnName("matchTeam");

                    b.HasKey("GroupId")
                        .HasName("PRIMARY");

                    b.HasIndex("Match", "MatchTeam")
                        .IsUnique();

                    b.ToTable("group", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.Group.Model.GroupRequestModel", b =>
                {
                    b.Property<ulong>("GroupId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("groupId");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("TEXT")
                        .HasColumnName("expiration");

                    b.Property<int>("RequestType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("requestType");

                    b.Property<ulong>("RequesteeCharacterId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("requesteeCharacterId");

                    b.Property<ushort>("RequesteeRealmId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("requesteeRealmId");

                    b.Property<ulong>("RequesterCharacterId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("requesterCharacterId");

                    b.Property<ushort>("RequesterRealmId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("requesterRealmId");

                    b.HasKey("GroupId")
                        .HasName("PRIMARY");

                    b.HasIndex("RequesteeCharacterId", "RequesteeRealmId")
                        .IsUnique();

                    b.HasIndex("RequesterCharacterId", "RequesterRealmId")
                        .IsUnique();

                    b.ToTable("group_request", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.Group.Model.InternalMessageModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("messageId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("createdAt");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("data");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("processedAt");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("ProcessedAt");

                    b.ToTable("internal_message", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.Group.Model.CharacterGroupModel", b =>
                {
                    b.HasOne("NexusForever.Database.Group.Model.CharacterModel", "Character")
                        .WithMany("Groups")
                        .HasForeignKey("CharacterId", "RealmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusForever.Database.Group.Model.GroupMemberModel", "Member")
                        .WithOne()
                        .HasForeignKey("NexusForever.Database.Group.Model.CharacterGroupModel", "GroupId", "CharacterId", "RealmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("NexusForever.Database.Group.Model.CharacterPropertyModel", b =>
                {
                    b.HasOne("NexusForever.Database.Group.Model.CharacterModel", "Character")
                        .WithMany("Properties")
                        .HasForeignKey("CharacterId", "RealmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("NexusForever.Database.Group.Model.CharacterStatModel", b =>
                {
                    b.HasOne("NexusForever.Database.Group.Model.CharacterModel", "Character")
                        .WithMany("Stats")
                        .HasForeignKey("CharacterId", "RealmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("NexusForever.Database.Group.Model.GroupInviteModel", b =>
                {
                    b.HasOne("NexusForever.Database.Group.Model.GroupModel", "Group")
                        .WithMany("Invites")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusForever.Database.Group.Model.CharacterModel", "InviteeCharacter")
                        .WithOne("Invite")
                        .HasForeignKey("NexusForever.Database.Group.Model.GroupInviteModel", "InviteeCharacterId", "InviteeRealmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("InviteeCharacter");
                });

            modelBuilder.Entity("NexusForever.Database.Group.Model.GroupLeaderModel", b =>
                {
                    b.HasOne("NexusForever.Database.Group.Model.GroupModel", "Group")
                        .WithOne("Leader")
                        .HasForeignKey("NexusForever.Database.Group.Model.GroupLeaderModel", "GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusForever.Database.Group.Model.GroupMemberModel", "Member")
                        .WithOne()
                        .HasForeignKey("NexusForever.Database.Group.Model.GroupLeaderModel", "GroupId", "CharacterId", "RealmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("NexusForever.Database.Group.Model.GroupMarkerModel", b =>
                {
                    b.HasOne("NexusForever.Database.Group.Model.GroupModel", "Group")
                        .WithMany("Markers")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("NexusForever.Database.Group.Model.GroupMemberModel", b =>
                {
                    b.HasOne("NexusForever.Database.Group.Model.GroupModel", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusForever.Database.Group.Model.CharacterModel", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId", "RealmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("NexusForever.Database.Group.Model.GroupRequestModel", b =>
                {
                    b.HasOne("NexusForever.Database.Group.Model.GroupModel", "Group")
                        .WithOne("Request")
                        .HasForeignKey("NexusForever.Database.Group.Model.GroupRequestModel", "GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusForever.Database.Group.Model.CharacterModel", "Requestee")
                        .WithOne()
                        .HasForeignKey("NexusForever.Database.Group.Model.GroupRequestModel", "RequesteeCharacterId", "RequesteeRealmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusForever.Database.Group.Model.CharacterModel", "Requester")
                        .WithOne()
                        .HasForeignKey("NexusForever.Database.Group.Model.GroupRequestModel", "RequesterCharacterId", "RequesterRealmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Requestee");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("NexusForever.Database.Group.Model.CharacterModel", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Invite");

                    b.Navigation("Properties");

                    b.Navigation("Stats");
                });

            modelBuilder.Entity("NexusForever.Database.Group.Model.GroupModel", b =>
                {
                    b.Navigation("Invites");

                    b.Navigation("Leader");

                    b.Navigation("Markers");

                    b.Navigation("Members");

                    b.Navigation("Request");
                });
#pragma warning restore 612, 618
        }
    }
}
