// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexusForever.Database.World;

#nullable disable

namespace NexusForever.Database.World.Migrations
{
    [DbContext(typeof(WorldContext))]
    partial class WorldContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("NexusForever.Database.World.Model.CreatureInfoPropertyModel", b =>
                {
                    b.Property<uint>("CreatureId")
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("id");

                    b.Property<byte>("Property")
                        .HasColumnType("tinyint(3) unsigned")
                        .HasColumnName("property");

                    b.Property<float>("Value")
                        .HasColumnType("float")
                        .HasColumnName("value");

                    b.HasKey("CreatureId", "Property")
                        .HasName("PRIMARY");

                    b.ToTable("creature_info_property", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.World.Model.CreatureInfoStatModel", b =>
                {
                    b.Property<uint>("CreatureId")
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("id");

                    b.Property<byte>("Stat")
                        .HasColumnType("tinyint(3) unsigned")
                        .HasColumnName("stat");

                    b.Property<float>("Value")
                        .HasColumnType("float")
                        .HasColumnName("value");

                    b.HasKey("CreatureId", "Stat")
                        .HasName("PRIMARY");

                    b.ToTable("creature_info_stat", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.World.Model.CreatureLootModel", b =>
                {
                    b.Property<uint>("CreatureId")
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("creatureId");

                    b.Property<uint>("ItemId")
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("itemId");

                    b.Property<uint>("AggregateDropCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("aggregateDropCount");

                    b.Property<uint>("AggregateDropSum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("aggregateDropSum");

                    b.Property<decimal>("Chance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,8)")
                        .HasDefaultValue(0m)
                        .HasColumnName("chance");

                    b.Property<uint>("DropTimes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("dropTimes");

                    b.Property<uint>("GameVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("gameVersion");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)")
                        .HasDefaultValue("")
                        .HasColumnName("itemName");

                    b.Property<uint>("LastSeenIn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("lastSeenIn");

                    b.Property<string>("MatchStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(32)")
                        .HasDefaultValue("")
                        .HasColumnName("matchStatus");

                    b.Property<uint>("SourceDropId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("sourceDropId");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)")
                        .HasDefaultValue("")
                        .HasColumnName("sourceName");

                    b.Property<uint>("VersionedCreatureDropAggregateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("versionedCreatureDropAggregateId");

                    b.Property<uint>("VersionedItemDropAggregateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("versionedItemDropAggregateId");

                    b.HasKey("CreatureId", "ItemId")
                        .HasName("PRIMARY");

                    b.HasIndex("Chance")
                        .HasDatabaseName("ix_creature_loot_chance");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_creature_loot_item");

                    b.ToTable("creature_loot", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.World.Model.DisableModel", b =>
                {
                    b.Property<byte>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(3) unsigned")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("type");

                    b.Property<uint>("ObjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("objectId");

                    b.Property<string>("Note")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(500)")
                        .HasDefaultValue("")
                        .HasColumnName("note");

                    b.HasKey("Type", "ObjectId")
                        .HasName("PRIMARY");

                    b.ToTable("disable", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.World.Model.EntityEventModel", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("id");

                    b.Property<uint>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("eventId");

                    b.Property<uint>("Phase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("phase");

                    b.HasKey("Id", "EventId", "Phase")
                        .HasName("PRIMARY");

                    b.HasIndex("EventId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("entity_event", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.World.Model.EntityLootModel", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("id");

                    b.Property<ulong>("LootGroupId")
                        .HasColumnType("bigint(20) unsigned")
                        .HasColumnName("lootGroupId");

                    b.Property<string>("Comment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(200)")
                        .HasDefaultValue("")
                        .HasColumnName("comment");

                    b.HasKey("Id", "LootGroupId")
                        .HasName("PRIMARY");

                    b.HasIndex("LootGroupId");

                    b.ToTable("entity_loot", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.World.Model.EntityModel", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("id");

                    b.Property<ulong>("ActivePropId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20) unsigned")
                        .HasDefaultValue(0ul)
                        .HasColumnName("activePropId");

                    b.Property<ushort>("Area")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint(5) unsigned")
                        .HasDefaultValue((ushort)0)
                        .HasColumnName("area");

                    b.Property<uint>("Creature")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("creature");

                    b.Property<uint>("DisplayInfo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("displayInfo");

                    b.Property<ushort>("Faction1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint(5) unsigned")
                        .HasDefaultValue((ushort)0)
                        .HasColumnName("faction1");

                    b.Property<ushort>("Faction2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint(5) unsigned")
                        .HasDefaultValue((ushort)0)
                        .HasColumnName("faction2");

                    b.Property<byte>("Mode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(3) unsigned")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("mode");

                    b.Property<ushort>("OutfitInfo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint(5) unsigned")
                        .HasDefaultValue((ushort)0)
                        .HasColumnName("outfitInfo");

                    b.Property<byte>("QuestChecklistIdx")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(3) unsigned")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("questChecklistIdx");

                    b.Property<float>("Rx")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0f)
                        .HasColumnName("rx");

                    b.Property<float>("Ry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0f)
                        .HasColumnName("ry");

                    b.Property<float>("Rz")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0f)
                        .HasColumnName("rz");

                    b.Property<byte>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(3) unsigned")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("type");

                    b.Property<ushort>("World")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint(5) unsigned")
                        .HasDefaultValue((ushort)0)
                        .HasColumnName("world");

                    b.Property<ushort>("WorldSocketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint(5) unsigned")
                        .HasDefaultValue((ushort)0)
                        .HasColumnName("worldSocketId");

                    b.Property<float>("X")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0f)
                        .HasColumnName("x");

                    b.Property<float>("Y")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0f)
                        .HasColumnName("y");

                    b.Property<float>("Z")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0f)
                        .HasColumnName("z");

                    b.HasKey("Id");

                    b.ToTable("entity", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.World.Model.EntityPropertyModel", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("id");

                    b.Property<byte>("Property")
                        .HasColumnType("tinyint(3) unsigned")
                        .HasColumnName("property");

                    b.Property<float>("Value")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0f)
                        .HasColumnName("value");

                    b.HasKey("Id", "Property")
                        .HasName("PRIMARY");

                    b.ToTable("entity_property", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.World.Model.EntityScriptModel", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("id");

                    b.Property<string>("ScriptName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(150)")
                        .HasDefaultValue("")
                        .HasColumnName("scriptName");

                    b.HasKey("Id", "ScriptName")
                        .HasName("PRIMARY");

                    b.ToTable("entity_script", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.World.Model.EntitySplineModel", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("id");

                    b.Property<float>("Fx")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0f)
                        .HasColumnName("fx");

                    b.Property<float>("Fy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0f)
                        .HasColumnName("fy");

                    b.Property<float>("Fz")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0f)
                        .HasColumnName("fz");

                    b.Property<byte>("Mode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(3) unsigned")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("mode");

                    b.Property<float>("Speed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0f)
                        .HasColumnName("speed");

                    b.Property<ushort>("SplineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint(5) unsigned")
                        .HasDefaultValue((ushort)0)
                        .HasColumnName("splineId");

                    b.HasKey("Id");

                    b.ToTable("entity_spline", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.World.Model.EntityStatModel", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("id");

                    b.Property<byte>("Stat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(3) unsigned")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("stat");

                    b.Property<float>("Value")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0f)
                        .HasColumnName("value");

                    b.HasKey("Id", "Stat")
                        .HasName("PRIMARY");

                    b.ToTable("entity_stats", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.World.Model.EntityVendorCategoryModel", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("id");

                    b.Property<uint>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("index");

                    b.Property<uint>("LocalisedTextId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("localisedTextId");

                    b.HasKey("Id", "Index")
                        .HasName("PRIMARY");

                    b.ToTable("entity_vendor_category", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.World.Model.EntityVendorItemModel", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("id");

                    b.Property<uint>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("index");

                    b.Property<uint>("CategoryIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("categoryIndex");

                    b.Property<uint>("ExtraCost1ItemOrCurrencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("extraCost1ItemOrCurrencyId");

                    b.Property<uint>("ExtraCost1Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("extraCost1Quantity");

                    b.Property<byte>("ExtraCost1Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(3) unsigned")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("extraCost1Type");

                    b.Property<uint>("ExtraCost2ItemOrCurrencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("extraCost2ItemOrCurrencyId");

                    b.Property<uint>("ExtraCost2Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("extraCost2Quantity");

                    b.Property<byte>("ExtraCost2Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(3) unsigned")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("extraCost2Type");

                    b.Property<uint>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("itemId");

                    b.HasKey("Id", "Index")
                        .HasName("PRIMARY");

                    b.ToTable("entity_vendor_item", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.World.Model.EntityVendorModel", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("id");

                    b.Property<float>("BuyPriceMultiplier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(1f)
                        .HasColumnName("buyPriceMultiplier");

                    b.Property<float>("SellPriceMultiplier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(1f)
                        .HasColumnName("sellPriceMultiplier");

                    b.HasKey("Id");

                    b.ToTable("entity_vendor", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.World.Model.ItemLootModel", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("id");

                    b.Property<ulong>("LootGroupId")
                        .HasColumnType("bigint(20) unsigned")
                        .HasColumnName("lootGroupId");

                    b.Property<string>("Comment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(200)")
                        .HasDefaultValue("")
                        .HasColumnName("comment");

                    b.HasKey("Id", "LootGroupId")
                        .HasName("PRIMARY");

                    b.HasIndex("LootGroupId");

                    b.ToTable("item_loot", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.World.Model.LootGroupModel", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20) unsigned")
                        .HasDefaultValue(0ul)
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(200)")
                        .HasDefaultValue("")
                        .HasColumnName("comment");

                    b.Property<uint>("Condition")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("condition");

                    b.Property<uint>("ConditionType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("conditionType");

                    b.Property<uint>("MaxDrop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("maxDrop");

                    b.Property<uint>("MinDrop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("minDrop");

                    b.Property<ulong?>("ParentId")
                        .HasColumnType("bigint(20) unsigned")
                        .HasColumnName("parentId");

                    b.Property<float>("Probability")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(100f)
                        .HasColumnName("probability");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("loot_group", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.World.Model.LootItemModel", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20) unsigned")
                        .HasDefaultValue(0ul)
                        .HasColumnName("id");

                    b.Property<uint>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("type");

                    b.Property<uint>("StaticId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("staticId");

                    b.Property<string>("Comment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(200)")
                        .HasDefaultValue("")
                        .HasColumnName("comment");

                    b.Property<uint>("MaxCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("maxCount");

                    b.Property<uint>("MinCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("minCount");

                    b.Property<float>("Probability")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(100f)
                        .HasColumnName("probability");

                    b.HasKey("Id", "Type", "StaticId")
                        .HasName("PRIMARY");

                    b.ToTable("loot_item", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.World.Model.MapEntranceModel", b =>
                {
                    b.Property<uint>("MapId")
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("mapId");

                    b.Property<byte>("Team")
                        .HasColumnType("tinyint(3) unsigned")
                        .HasColumnName("team");

                    b.Property<uint>("WorldLocationId")
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("worldLocationId");

                    b.HasKey("MapId", "Team")
                        .HasName("PRIMARY");

                    b.ToTable("map_entrance", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.World.Model.StoreCategoryModel", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(150)")
                        .HasDefaultValue("")
                        .HasColumnName("description");

                    b.Property<uint>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(1u)
                        .HasColumnName("index");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("")
                        .HasColumnName("name");

                    b.Property<uint>("ParentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(26u)
                        .HasColumnName("parentId");

                    b.Property<byte>("Visible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1) unsigned")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("visible");

                    b.HasKey("Id");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("parentId");

                    b.ToTable("store_category", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.World.Model.StoreOfferGroupCategoryModel", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("id");

                    b.Property<uint>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("categoryId");

                    b.Property<byte>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(3) unsigned")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("index");

                    b.Property<byte>("Visible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1) unsigned")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("visible");

                    b.HasKey("Id", "CategoryId")
                        .HasName("PRIMARY");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("FK__store_offer_group_category_categoryId__store_category_id");

                    b.ToTable("store_offer_group_category", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.World.Model.StoreOfferGroupModel", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(500)")
                        .HasDefaultValue("")
                        .HasColumnName("description");

                    b.Property<uint>("DisplayFlags")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("displayFlags");

                    b.Property<ushort>("DisplayInfoOverride")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint(5) unsigned")
                        .HasDefaultValue((ushort)0)
                        .HasColumnName("displayInfoOverride");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("")
                        .HasColumnName("name");

                    b.Property<byte>("Visible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1) unsigned")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("visible");

                    b.HasKey("Id");

                    b.ToTable("store_offer_group", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.World.Model.StoreOfferItemDataModel", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("id");

                    b.Property<ushort>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint(5) unsigned")
                        .HasDefaultValue((ushort)0)
                        .HasColumnName("itemId");

                    b.Property<uint>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(1u)
                        .HasColumnName("amount");

                    b.Property<uint>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("type");

                    b.HasKey("Id", "ItemId")
                        .HasName("PRIMARY");

                    b.ToTable("store_offer_item_data", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.World.Model.StoreOfferItemModel", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("id");

                    b.Property<uint>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("groupId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(500)")
                        .HasDefaultValue("")
                        .HasColumnName("description");

                    b.Property<uint>("DisplayFlags")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("displayFlags");

                    b.Property<long>("Unknown6")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasDefaultValue(0L)
                        .HasColumnName("field_6");

                    b.Property<byte>("Unknown7")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(3) unsigned")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("field_7");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("")
                        .HasColumnName("name");

                    b.Property<byte>("Visible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1) unsigned")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("visible");

                    b.HasKey("Id", "GroupId")
                        .HasName("PRIMARY");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("FK__store_offer_item_groupId__store_offer_group_id");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("id");

                    b.ToTable("store_offer_item", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.World.Model.StoreOfferItemPriceModel", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("id");

                    b.Property<byte>("CurrencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(3) unsigned")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("currencyId");

                    b.Property<byte>("DiscountType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(3) unsigned")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("discountType");

                    b.Property<float>("DiscountValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0f)
                        .HasColumnName("discountValue");

                    b.Property<long>("Expiry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasDefaultValue(0L)
                        .HasColumnName("expiry");

                    b.Property<long>("Field14")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasDefaultValue(0L)
                        .HasColumnName("field_14");

                    b.Property<float>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0f)
                        .HasColumnName("price");

                    b.HasKey("Id", "CurrencyId")
                        .HasName("PRIMARY");

                    b.ToTable("store_offer_item_price", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.World.Model.TutorialModel", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("id")
                        .HasComment("Tutorial ID");

                    b.Property<uint>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("type");

                    b.Property<uint>("TriggerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("triggerId");

                    b.Property<string>("Note")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("")
                        .HasColumnName("note");

                    b.HasKey("Id", "Type", "TriggerId")
                        .HasName("PRIMARY");

                    b.ToTable("tutorial", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.World.Model.VersionModel", b =>
                {
                    b.Property<string>("FileName")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("fileName");

                    b.Property<string>("FileHash")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("fileHash");

                    b.Property<DateTime>("AppliedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("appliedOn");

                    b.HasKey("FileName", "FileHash")
                        .HasName("PRIMARY");

                    b.ToTable("version", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.World.Model.EntityEventModel", b =>
                {
                    b.HasOne("NexusForever.Database.World.Model.EntityModel", "Entity")
                        .WithOne("EntityEvent")
                        .HasForeignKey("NexusForever.Database.World.Model.EntityEventModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__entity_event_id__entity_id");

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("NexusForever.Database.World.Model.EntityLootModel", b =>
                {
                    b.HasOne("NexusForever.Database.World.Model.LootGroupModel", "LootGroup")
                        .WithMany()
                        .HasForeignKey("LootGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_entity_loot_loot_group_lootGroupId");

                    b.Navigation("LootGroup");
                });

            modelBuilder.Entity("NexusForever.Database.World.Model.EntityPropertyModel", b =>
                {
                    b.HasOne("NexusForever.Database.World.Model.EntityModel", "Entity")
                        .WithMany("EntityProperty")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__entity_property_id__entity_id");

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("NexusForever.Database.World.Model.EntityScriptModel", b =>
                {
                    b.HasOne("NexusForever.Database.World.Model.EntityModel", "Entity")
                        .WithMany("EntityScript")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__entity_script_id__entity_id");

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("NexusForever.Database.World.Model.EntitySplineModel", b =>
                {
                    b.HasOne("NexusForever.Database.World.Model.EntityModel", "Entity")
                        .WithOne("EntitySpline")
                        .HasForeignKey("NexusForever.Database.World.Model.EntitySplineModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__entity_spline_id__entity_id");

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("NexusForever.Database.World.Model.EntityStatModel", b =>
                {
                    b.HasOne("NexusForever.Database.World.Model.EntityModel", "Entity")
                        .WithMany("EntityStat")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__entity_stats_stat_id_entity_id");

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("NexusForever.Database.World.Model.EntityVendorCategoryModel", b =>
                {
                    b.HasOne("NexusForever.Database.World.Model.EntityModel", "Entity")
                        .WithMany("EntityVendorCategory")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__entity_vendor_category_id__entity_id");

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("NexusForever.Database.World.Model.EntityVendorItemModel", b =>
                {
                    b.HasOne("NexusForever.Database.World.Model.EntityModel", "Entity")
                        .WithMany("EntityVendorItem")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__entity_vendor_item_id__entity_id");

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("NexusForever.Database.World.Model.EntityVendorModel", b =>
                {
                    b.HasOne("NexusForever.Database.World.Model.EntityModel", "Entity")
                        .WithOne("EntityVendor")
                        .HasForeignKey("NexusForever.Database.World.Model.EntityVendorModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__entity_vendor_id__entity_id");

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("NexusForever.Database.World.Model.ItemLootModel", b =>
                {
                    b.HasOne("NexusForever.Database.World.Model.LootGroupModel", "LootGroup")
                        .WithMany()
                        .HasForeignKey("LootGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_item_loot_loot_group_lootGroupId");

                    b.Navigation("LootGroup");
                });

            modelBuilder.Entity("NexusForever.Database.World.Model.LootGroupModel", b =>
                {
                    b.HasOne("NexusForever.Database.World.Model.LootGroupModel", "Parent")
                        .WithMany("ChildGroup")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("FK__loot_group_parentId__loot_group_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("NexusForever.Database.World.Model.LootItemModel", b =>
                {
                    b.HasOne("NexusForever.Database.World.Model.LootGroupModel", "LootGroup")
                        .WithMany("Item")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__loot_item_id__loot_group_id");

                    b.Navigation("LootGroup");
                });

            modelBuilder.Entity("NexusForever.Database.World.Model.StoreOfferGroupCategoryModel", b =>
                {
                    b.HasOne("NexusForever.Database.World.Model.StoreCategoryModel", "Category")
                        .WithMany("StoreOfferGroupCategory")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__store_offer_group_category_categoryId__store_category_id");

                    b.HasOne("NexusForever.Database.World.Model.StoreOfferGroupModel", "OfferGroup")
                        .WithMany("StoreOfferGroupCategory")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__store_offer_group_category_id__store_offer_group_id");

                    b.Navigation("Category");

                    b.Navigation("OfferGroup");
                });

            modelBuilder.Entity("NexusForever.Database.World.Model.StoreOfferItemDataModel", b =>
                {
                    b.HasOne("NexusForever.Database.World.Model.StoreOfferItemModel", "OfferItem")
                        .WithMany("StoreOfferItemData")
                        .HasForeignKey("Id")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__store_offer_item_data_id__store_offer_item_id");

                    b.Navigation("OfferItem");
                });

            modelBuilder.Entity("NexusForever.Database.World.Model.StoreOfferItemModel", b =>
                {
                    b.HasOne("NexusForever.Database.World.Model.StoreOfferGroupModel", "Group")
                        .WithMany("StoreOfferItem")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__store_offer_item_groupId__store_offer_group_id");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("NexusForever.Database.World.Model.StoreOfferItemPriceModel", b =>
                {
                    b.HasOne("NexusForever.Database.World.Model.StoreOfferItemModel", "OfferItem")
                        .WithMany("StoreOfferItemPrice")
                        .HasForeignKey("Id")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__store_offer_item_price_id__store_offer_item_id");

                    b.Navigation("OfferItem");
                });

            modelBuilder.Entity("NexusForever.Database.World.Model.EntityModel", b =>
                {
                    b.Navigation("EntityEvent");

                    b.Navigation("EntityProperty");

                    b.Navigation("EntityScript");

                    b.Navigation("EntitySpline");

                    b.Navigation("EntityStat");

                    b.Navigation("EntityVendor");

                    b.Navigation("EntityVendorCategory");

                    b.Navigation("EntityVendorItem");
                });

            modelBuilder.Entity("NexusForever.Database.World.Model.LootGroupModel", b =>
                {
                    b.Navigation("ChildGroup");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("NexusForever.Database.World.Model.StoreCategoryModel", b =>
                {
                    b.Navigation("StoreOfferGroupCategory");
                });

            modelBuilder.Entity("NexusForever.Database.World.Model.StoreOfferGroupModel", b =>
                {
                    b.Navigation("StoreOfferGroupCategory");

                    b.Navigation("StoreOfferItem");
                });

            modelBuilder.Entity("NexusForever.Database.World.Model.StoreOfferItemModel", b =>
                {
                    b.Navigation("StoreOfferItemData");

                    b.Navigation("StoreOfferItemPrice");
                });
#pragma warning restore 612, 618
        }
    }
}
