<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommandLineParser" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Nexus.Archive" />
  </ItemGroup>

  <ItemGroup>
    <NuGetAuditSuppress Include="https://github.com/advisories/GHSA-6c8g-7p36-r338" />
    <NuGetAuditSuppress Include="https://github.com/advisories/GHSA-jp7f-grcv-6mjf" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NexusForever.GameTable\NexusForever.GameTable.csproj" />
    <ProjectReference Include="..\NexusForever.IO\NexusForever.IO.csproj" />
    <ProjectReference Include="..\NexusForever.Shared\NexusForever.Shared.csproj" />
  </ItemGroup>

</Project>
