// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexusForever.Database.Friendship;

#nullable disable

namespace NexusForever.Database.Sqlite.Migrations.Friendship
{
    [DbContext(typeof(FriendshipContext))]
    partial class FriendshipContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.16");

            modelBuilder.Entity("NexusForever.Database.Friendship.Model.AccountFriendInverseModel", b =>
                {
                    b.Property<uint>("AccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("accountId");

                    b.Property<ulong>("FriendAccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("friendAccountId");

                    b.HasKey("AccountId", "FriendAccountId");

                    b.HasIndex("AccountId");

                    b.HasIndex("FriendAccountId")
                        .IsUnique();

                    b.ToTable("account_friend_inverse", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.Friendship.Model.AccountFriendInviteModel", b =>
                {
                    b.Property<uint>("AccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("accountId");

                    b.Property<ulong>("FriendAccountInviteId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("friendAccountInviteId");

                    b.HasKey("AccountId", "FriendAccountInviteId");

                    b.HasIndex("AccountId");

                    b.HasIndex("FriendAccountInviteId")
                        .IsUnique();

                    b.ToTable("account_friend_invite", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.Friendship.Model.AccountFriendInvitePendingModel", b =>
                {
                    b.Property<uint>("AccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("accountId");

                    b.Property<ulong>("FriendAccountInviteId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("friendAccountInviteId");

                    b.HasKey("AccountId", "FriendAccountInviteId");

                    b.HasIndex("AccountId");

                    b.HasIndex("FriendAccountInviteId")
                        .IsUnique();

                    b.ToTable("account_friend_invite_pending", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.Friendship.Model.AccountFriendModel", b =>
                {
                    b.Property<uint>("AccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("accountId");

                    b.Property<ulong>("FriendAccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("friendAccountId");

                    b.HasKey("AccountId", "FriendAccountId");

                    b.HasIndex("AccountId");

                    b.HasIndex("FriendAccountId")
                        .IsUnique();

                    b.ToTable("account_friend", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.Friendship.Model.AccountModel", b =>
                {
                    b.Property<uint>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("accountId");

                    b.Property<ulong?>("ActiveCharacterId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activeCharacterId");

                    b.Property<ushort?>("ActiveRealmId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activeRealmId");

                    b.Property<bool>("BlockAccountFriendRequests")
                        .HasColumnType("INTEGER")
                        .HasColumnName("blockAccountFriendRequests");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<bool>("InvitePrivilegesSuspended")
                        .HasColumnType("INTEGER")
                        .HasColumnName("invitePrivilegesSuspended");

                    b.Property<DateTime?>("LastOnline")
                        .HasColumnType("TEXT")
                        .HasColumnName("lastOnline");

                    b.Property<string>("Nickname")
                        .HasColumnType("TEXT")
                        .HasColumnName("nickname");

                    b.Property<int>("Presence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("presence");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("AccountId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Nickname")
                        .IsUnique();

                    b.HasIndex("ActiveCharacterId", "ActiveRealmId")
                        .IsUnique();

                    b.ToTable("account", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.Friendship.Model.CharacterFriendInverseModel", b =>
                {
                    b.Property<ulong>("CharacterId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("characterId");

                    b.Property<ushort>("RealmId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("realmId");

                    b.Property<ulong>("FriendId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("friendId");

                    b.HasKey("CharacterId", "RealmId", "FriendId");

                    b.HasIndex("FriendId")
                        .IsUnique();

                    b.HasIndex("CharacterId", "RealmId");

                    b.ToTable("character_friend_inverse", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.Friendship.Model.CharacterFriendInviteModel", b =>
                {
                    b.Property<ulong>("CharacterId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("characterId");

                    b.Property<ushort>("RealmId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("realmId");

                    b.Property<ulong>("FriendInviteId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("friendInviteId");

                    b.HasKey("CharacterId", "RealmId", "FriendInviteId");

                    b.HasIndex("FriendInviteId")
                        .IsUnique();

                    b.HasIndex("CharacterId", "RealmId");

                    b.ToTable("character_friend_invite", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.Friendship.Model.CharacterFriendInvitePendingModel", b =>
                {
                    b.Property<ulong>("CharacterId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("characterId");

                    b.Property<ushort>("RealmId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("realmId");

                    b.Property<ulong>("FriendInviteId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("friendInviteId");

                    b.HasKey("CharacterId", "RealmId", "FriendInviteId");

                    b.HasIndex("FriendInviteId")
                        .IsUnique();

                    b.HasIndex("CharacterId", "RealmId");

                    b.ToTable("character_friend_invite_pending", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.Friendship.Model.CharacterFriendModel", b =>
                {
                    b.Property<ulong>("CharacterId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("characterId");

                    b.Property<ushort>("RealmId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("realmId");

                    b.Property<ulong>("FriendId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("friendId");

                    b.HasKey("CharacterId", "RealmId", "FriendId");

                    b.HasIndex("FriendId")
                        .IsUnique();

                    b.HasIndex("CharacterId", "RealmId");

                    b.ToTable("character_friend", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.Friendship.Model.CharacterModel", b =>
                {
                    b.Property<ulong>("CharacterId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("characterId");

                    b.Property<ushort>("RealmId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("realmId");

                    b.Property<uint>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Class")
                        .HasColumnType("INTEGER")
                        .HasColumnName("class");

                    b.Property<uint>("Faction")
                        .HasColumnType("INTEGER")
                        .HasColumnName("faction");

                    b.Property<DateTime?>("LastOnline")
                        .HasColumnType("TEXT")
                        .HasColumnName("lastOnline");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<byte>("Path")
                        .HasColumnType("INTEGER")
                        .HasColumnName("path");

                    b.Property<byte>("Race")
                        .HasColumnType("INTEGER")
                        .HasColumnName("race");

                    b.Property<string>("RealmName")
                        .HasColumnType("TEXT")
                        .HasColumnName("realmName");

                    b.Property<uint>("WorldId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("worldId");

                    b.Property<ushort>("WorldZoneId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("worldZoneId");

                    b.HasKey("CharacterId", "RealmId");

                    b.HasIndex("AccountId");

                    b.ToTable("character", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.Friendship.Model.CharacterStatModel", b =>
                {
                    b.Property<ulong>("CharacterId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("characterId");

                    b.Property<ushort>("RealmId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("realmId");

                    b.Property<byte>("Stat")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stat");

                    b.Property<float>("Value")
                        .HasColumnType("REAL")
                        .HasColumnName("value");

                    b.HasKey("CharacterId", "RealmId", "Stat");

                    b.HasIndex("CharacterId", "RealmId");

                    b.ToTable("character_stat", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.Friendship.Model.FriendAccountInviteModel", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("TEXT")
                        .HasColumnName("expiration");

                    b.Property<uint>("InviteeAccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("inviteeAccountId");

                    b.Property<uint>("InviterAccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("inviterAccountId");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<bool>("Seen")
                        .HasColumnType("INTEGER")
                        .HasColumnName("seen");

                    b.HasKey("Id");

                    b.HasIndex("InviteeAccountId");

                    b.HasIndex("InviterAccountId");

                    b.ToTable("friendship_account_invite", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.Friendship.Model.FriendAccountModel", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<uint>("InviteeAccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("inviteeAccountId");

                    b.Property<uint>("InviterAccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("inviterAccountId");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.HasKey("Id");

                    b.HasIndex("InviteeAccountId");

                    b.HasIndex("InviterAccountId");

                    b.ToTable("friendship_account", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.Friendship.Model.FriendInviteModel", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("TEXT")
                        .HasColumnName("expiration");

                    b.Property<ulong>("InviteeCharacterId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("inviteeCharacterId");

                    b.Property<ushort>("InviteeRealmId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("inviteeRealmId");

                    b.Property<ulong>("InviterCharacterId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("inviterCharacterId");

                    b.Property<ushort>("InviterRealmId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("inviterRealmId");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<bool>("Seen")
                        .HasColumnType("INTEGER")
                        .HasColumnName("seen");

                    b.HasKey("Id");

                    b.HasIndex("InviteeCharacterId", "InviteeRealmId");

                    b.HasIndex("InviterCharacterId", "InviterRealmId");

                    b.ToTable("friendship_invite", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.Friendship.Model.FriendModel", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<ulong>("InviteeCharacterId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("friendCharacterId");

                    b.Property<ushort>("InviteeRealmId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("friendRealmId");

                    b.Property<ulong>("InviterCharacterId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("inviterCharacterId");

                    b.Property<ushort>("InviterRealmId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("inviterRealmId");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("InviteeCharacterId", "InviteeRealmId");

                    b.HasIndex("InviterCharacterId", "InviterRealmId", "InviteeCharacterId", "InviteeRealmId")
                        .IsUnique();

                    b.ToTable("friendship", (string)null);
                });

            modelBuilder.Entity("NexusForever.Database.Friendship.Model.InternalMessageModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("InternalMessage");
                });

            modelBuilder.Entity("NexusForever.Database.Friendship.Model.AccountFriendInverseModel", b =>
                {
                    b.HasOne("NexusForever.Database.Friendship.Model.AccountModel", "Account")
                        .WithMany("FriendsInverse")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusForever.Database.Friendship.Model.FriendAccountModel", "FriendAccount")
                        .WithOne()
                        .HasForeignKey("NexusForever.Database.Friendship.Model.AccountFriendInverseModel", "FriendAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("FriendAccount");
                });

            modelBuilder.Entity("NexusForever.Database.Friendship.Model.AccountFriendInviteModel", b =>
                {
                    b.HasOne("NexusForever.Database.Friendship.Model.AccountModel", "Account")
                        .WithMany("FriendInvites")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusForever.Database.Friendship.Model.FriendAccountInviteModel", "FriendAccountInvite")
                        .WithOne()
                        .HasForeignKey("NexusForever.Database.Friendship.Model.AccountFriendInviteModel", "FriendAccountInviteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("FriendAccountInvite");
                });

            modelBuilder.Entity("NexusForever.Database.Friendship.Model.AccountFriendInvitePendingModel", b =>
                {
                    b.HasOne("NexusForever.Database.Friendship.Model.AccountModel", "Account")
                        .WithMany("FriendInvitesPending")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusForever.Database.Friendship.Model.FriendAccountInviteModel", "FriendAccountInvite")
                        .WithOne()
                        .HasForeignKey("NexusForever.Database.Friendship.Model.AccountFriendInvitePendingModel", "FriendAccountInviteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("FriendAccountInvite");
                });

            modelBuilder.Entity("NexusForever.Database.Friendship.Model.AccountFriendModel", b =>
                {
                    b.HasOne("NexusForever.Database.Friendship.Model.AccountModel", "Account")
                        .WithMany("Friends")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusForever.Database.Friendship.Model.FriendAccountModel", "FriendAccount")
                        .WithOne()
                        .HasForeignKey("NexusForever.Database.Friendship.Model.AccountFriendModel", "FriendAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("FriendAccount");
                });

            modelBuilder.Entity("NexusForever.Database.Friendship.Model.AccountModel", b =>
                {
                    b.HasOne("NexusForever.Database.Friendship.Model.CharacterModel", "ActiveCharacter")
                        .WithOne()
                        .HasForeignKey("NexusForever.Database.Friendship.Model.AccountModel", "ActiveCharacterId", "ActiveRealmId");

                    b.Navigation("ActiveCharacter");
                });

            modelBuilder.Entity("NexusForever.Database.Friendship.Model.CharacterFriendInverseModel", b =>
                {
                    b.HasOne("NexusForever.Database.Friendship.Model.FriendModel", "Friend")
                        .WithOne()
                        .HasForeignKey("NexusForever.Database.Friendship.Model.CharacterFriendInverseModel", "FriendId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusForever.Database.Friendship.Model.CharacterModel", "Character")
                        .WithMany("FriendsInverse")
                        .HasForeignKey("CharacterId", "RealmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Friend");
                });

            modelBuilder.Entity("NexusForever.Database.Friendship.Model.CharacterFriendInviteModel", b =>
                {
                    b.HasOne("NexusForever.Database.Friendship.Model.FriendInviteModel", "FriendInvite")
                        .WithOne()
                        .HasForeignKey("NexusForever.Database.Friendship.Model.CharacterFriendInviteModel", "FriendInviteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusForever.Database.Friendship.Model.CharacterModel", "Character")
                        .WithMany("FriendInvites")
                        .HasForeignKey("CharacterId", "RealmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("FriendInvite");
                });

            modelBuilder.Entity("NexusForever.Database.Friendship.Model.CharacterFriendInvitePendingModel", b =>
                {
                    b.HasOne("NexusForever.Database.Friendship.Model.FriendInviteModel", "FriendInvite")
                        .WithOne()
                        .HasForeignKey("NexusForever.Database.Friendship.Model.CharacterFriendInvitePendingModel", "FriendInviteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusForever.Database.Friendship.Model.CharacterModel", "Character")
                        .WithMany("FriendInvitesPending")
                        .HasForeignKey("CharacterId", "RealmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("FriendInvite");
                });

            modelBuilder.Entity("NexusForever.Database.Friendship.Model.CharacterFriendModel", b =>
                {
                    b.HasOne("NexusForever.Database.Friendship.Model.FriendModel", "Friend")
                        .WithOne()
                        .HasForeignKey("NexusForever.Database.Friendship.Model.CharacterFriendModel", "FriendId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusForever.Database.Friendship.Model.CharacterModel", "Character")
                        .WithMany("Friends")
                        .HasForeignKey("CharacterId", "RealmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Friend");
                });

            modelBuilder.Entity("NexusForever.Database.Friendship.Model.CharacterModel", b =>
                {
                    b.HasOne("NexusForever.Database.Friendship.Model.AccountModel", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("NexusForever.Database.Friendship.Model.CharacterStatModel", b =>
                {
                    b.HasOne("NexusForever.Database.Friendship.Model.CharacterModel", "Character")
                        .WithMany("Stats")
                        .HasForeignKey("CharacterId", "RealmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("NexusForever.Database.Friendship.Model.FriendAccountInviteModel", b =>
                {
                    b.HasOne("NexusForever.Database.Friendship.Model.AccountModel", "InviteeAccount")
                        .WithMany()
                        .HasForeignKey("InviteeAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusForever.Database.Friendship.Model.AccountModel", "InviterAccount")
                        .WithMany()
                        .HasForeignKey("InviterAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InviteeAccount");

                    b.Navigation("InviterAccount");
                });

            modelBuilder.Entity("NexusForever.Database.Friendship.Model.FriendAccountModel", b =>
                {
                    b.HasOne("NexusForever.Database.Friendship.Model.AccountModel", "InviteeAccount")
                        .WithMany()
                        .HasForeignKey("InviteeAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusForever.Database.Friendship.Model.AccountModel", "InviterAccount")
                        .WithMany()
                        .HasForeignKey("InviterAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InviteeAccount");

                    b.Navigation("InviterAccount");
                });

            modelBuilder.Entity("NexusForever.Database.Friendship.Model.FriendInviteModel", b =>
                {
                    b.HasOne("NexusForever.Database.Friendship.Model.CharacterModel", "InviteeCharacter")
                        .WithMany()
                        .HasForeignKey("InviteeCharacterId", "InviteeRealmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusForever.Database.Friendship.Model.CharacterModel", "InviterCharacter")
                        .WithMany()
                        .HasForeignKey("InviterCharacterId", "InviterRealmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InviteeCharacter");

                    b.Navigation("InviterCharacter");
                });

            modelBuilder.Entity("NexusForever.Database.Friendship.Model.FriendModel", b =>
                {
                    b.HasOne("NexusForever.Database.Friendship.Model.CharacterModel", "InviteeCharacter")
                        .WithMany()
                        .HasForeignKey("InviteeCharacterId", "InviteeRealmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusForever.Database.Friendship.Model.CharacterModel", "InviterCharacter")
                        .WithMany()
                        .HasForeignKey("InviterCharacterId", "InviterRealmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InviteeCharacter");

                    b.Navigation("InviterCharacter");
                });

            modelBuilder.Entity("NexusForever.Database.Friendship.Model.AccountModel", b =>
                {
                    b.Navigation("FriendInvites");

                    b.Navigation("FriendInvitesPending");

                    b.Navigation("Friends");

                    b.Navigation("FriendsInverse");
                });

            modelBuilder.Entity("NexusForever.Database.Friendship.Model.CharacterModel", b =>
                {
                    b.Navigation("FriendInvites");

                    b.Navigation("FriendInvitesPending");

                    b.Navigation("Friends");

                    b.Navigation("FriendsInverse");

                    b.Navigation("Stats");
                });
#pragma warning restore 612, 618
        }
    }
}
