<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <OutputPath>$(MSBuildThisFileDirectory)..\NexusForever.WorldServer\bin\$(Configuration)</OutputPath>
  </PropertyGroup>

</Project>
