namespace NexusForever.Game.Static.Achievement
{
    public enum AchievementType
    {
        KillCreatureEntry     = 1,
        KillCreatureGroup     = 2,
        QuestComplete         = 3,
        KillCreatureChecklist  = 5,
        QuestCompleteChecklist = 6,
        AchievementComplete   = 7,
        EnterWorldZone        = 8,
        DiscoverObject        = 15,
        ActivateCreature      = 16,
        CraftItem             = 35,
        TradeskillTier        = 37,
        CostumeUnlock         = 38,
        CraftItemChecklist    = 40,
        ReputationLevel        = 42,
        QuestCompleteChecklistCount = 45,
        MapComplete            = 53,
        CharacterLevel         = 54,
        TitleEarned            = 56,
        PathLevel              = 64,
        GuildBelovedReputation = 67,
        CurrencyEarned         = 75,
        ItemConsume            = 80,
        FindSecretStash        = 82,
        GuildMaxPathLevel      = 92,
        DuelParticipate        = 97,
        DuelWin                = 98,
        ClassLevel50           = 103,
        EmoteTargetCreature    = 104,
        CriticalDeathblow      = 105,
        GuildOrCircleJoin      = 106,
        GroupJoin              = 107,
        FriendAdd              = 108,
        HousingPlugPlace       = 111,
        HousingDecorPurchase   = 113,
        RealmFirst             = 116,
        ContractQualityComplete = 130,
        ContractTypeComplete    = 131,
        ContractComplete        = 133,
        AccountCurrencyEarned   = 137,
        CostumeSetUnlock        = 141,
        PublicEventObjectiveComplete = 143,
        PrimalEssenceEarned     = 152
    }
}
