// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexusForever.Database.Query;

#nullable disable

namespace NexusForever.Database.Sqlite.Migrations.Query
{
    [DbContext(typeof(QueryContext))]
    [Migration("20260728193658_QuerySqliteInitial")]
    partial class QuerySqliteInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("NexusForever.Database.Query.Model.CharacterModel", b =>
                {
                    b.Property<ulong>("CharacterId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("characterId");

                    b.Property<ushort>("RealmId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("realmId");

                    b.Property<byte>("Class")
                        .HasColumnType("INTEGER")
                        .HasColumnName("class");

                    b.Property<ushort>("CurrentRealmId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("currentRealmId");

                    b.Property<uint>("Faction")
                        .HasColumnType("INTEGER")
                        .HasColumnName("faction");

                    b.Property<string>("GuildName")
                        .HasColumnType("TEXT")
                        .HasColumnName("guildName");

                    b.Property<DateTime?>("LastOnline")
                        .HasColumnType("TEXT")
                        .HasColumnName("lastOnline");

                    b.Property<uint>("Level")
                        .HasColumnType("INTEGER")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<byte>("Path")
                        .HasColumnType("INTEGER")
                        .HasColumnName("path");

                    b.Property<byte>("Race")
                        .HasColumnType("INTEGER")
                        .HasColumnName("race");

                    b.Property<string>("RealmName")
                        .HasColumnType("TEXT")
                        .HasColumnName("realmName");

                    b.Property<byte>("Sex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sex");

                    b.Property<ushort>("WorldZoneId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("worldZoneId");

                    b.HasKey("CharacterId", "RealmId");

                    b.HasIndex("Class");

                    b.HasIndex("CurrentRealmId");

                    b.HasIndex("GuildName");

                    b.HasIndex("Level");

                    b.HasIndex("Name");

                    b.HasIndex("Path");

                    b.HasIndex("Race");

                    b.HasIndex("WorldZoneId");

                    b.ToTable("character", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
