-- Generated by Tools/DataMapping/extract_laughingws_quest_instances.py.
-- Source: LaughingWS Map/Open World/The Dust Stalker.sql.
-- Purpose: preserve the small quest-instance overlay for quest 4516 without importing the source world delete or @GUID allocation.
-- WIP/GUESSED: Boss Xagg and the bridge controls are corroborated by DataMapping quest/objective/spawn evidence, but the exit panel is source-only and marked 'place for real' upstream.
-- WIP/GUESSED: current-schema overrides replace the source bridge-control type 20 with SimpleCollidable type 32 and replace source Boss Xagg health=1 with DataMapping stats.

USE `nexus_forever_world`;

START TRANSACTION;

-- entity: 3 row(s)
INSERT INTO `entity` (`id`, `type`, `creature`, `world`, `area`, `x`, `y`, `z`, `rx`, `ry`, `rz`, `displayInfo`, `outfitInfo`, `faction1`, `faction2`, `questChecklistIdx`, `activePropId`, `worldSocketId`, `mode`) VALUES
  (1100100001, 0, 16707, 1138, 950, -0.05071211, 6.279976, 243.2797, 0, 0, 0, 24369, 8782, 771, 771, 0, 0, 0, 0),
  (1100100002, 32, 16733, 1138, 950, -0.08464324, 8.691921, 258.9572, 0, 0, 0, 24632, 0, 219, 219, 0, 0, 0, 0),
  (1100100003, 10, 23758, 1138, 950, -7.8, 1.5, -15.4, 0, 0, 0, 23952, 0, 219, 219, 0, 0, 0, 0)
ON DUPLICATE KEY UPDATE `type` = VALUES(`type`), `creature` = VALUES(`creature`), `world` = VALUES(`world`), `area` = VALUES(`area`), `x` = VALUES(`x`), `y` = VALUES(`y`), `z` = VALUES(`z`), `rx` = VALUES(`rx`), `ry` = VALUES(`ry`), `rz` = VALUES(`rz`), `displayInfo` = VALUES(`displayInfo`), `outfitInfo` = VALUES(`outfitInfo`), `faction1` = VALUES(`faction1`), `faction2` = VALUES(`faction2`), `questChecklistIdx` = VALUES(`questChecklistIdx`), `activePropId` = VALUES(`activePropId`), `worldSocketId` = VALUES(`worldSocketId`), `mode` = VALUES(`mode`);

-- entity_stats: 4 row(s)
INSERT INTO `entity_stats` (`id`, `stat`, `value`) VALUES
  (1100100001, 0, 8767),
  (1100100001, 10, 19),
  (1100100001, 20, 2352),
  (1100100001, 21, 0)
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`);

-- Sources:
--   Map/Open World/The Dust Stalker.sql

COMMIT;
