-- Generated by Tools/DataMapping/extract_laughingws_city_content.py.
-- Source: Curated LaughingWS city/museum/quest-terminal entity rows.
-- Purpose: Add placed transport, Illium Museum, housing intro checklist, and Skull's Eye escape-pod content without importing broad world replacement SQL.
-- WIP/GUESSED: Skull's Eye terminal placement is branch-authored and still needs manual quest smoke for exact retail parity.
-- WIP/GUESSED: Ringo Hax Illium placement and Thayd/Illium housing questChecklistIdx updates are evidence-backed but still need manual client smoke.

USE `nexus_forever_world`;

START TRANSACTION;

-- entity: 17 row(s)
INSERT IGNORE INTO `entity` (`id`, `type`, `creature`, `world`, `area`, `x`, `y`, `z`, `rx`, `ry`, `rz`, `displayinfo`, `outfitinfo`, `faction1`, `faction2`, `questchecklistidx`, `activepropid`, `worldsocketid`, `mode`) VALUES
    (1100000001,14,46183,51,2548,4005.568,-803.212,-2302.32,-1.49E-08,0,0,24632,0,219,219,0,0,0,0),
    (1100000002,14,46184,1068,868,-11883.715,79.83,-3932.77,-1.17722,0,0,24632,0,219,219,0,0,0,0),
    (1100000003,14,46185,1068,868,-11870.43,79.83,-3926.266294,0.514,0,0,24632,0,219,219,0,0,0,0),
    (1100000004,20,53610,22,4380,-3372.154,-1032.306,-1673.113,-1.570796,0,0,21375,0,219,219,0,0,0,0),
    (1100000005,20,53615,22,4380,-3381.194,-1033.2065,-1721.921,-3.1415926536,0,0,27450,0,219,219,0,0,0,0),
    (1100000006,10,53616,22,4380,-3381.194,-1031.039,-1721.921,-3.1415926536,0,0,25236,9080,170,170,0,0,0,0),
    (1100000007,20,53703,22,4380,-3372.123,-1032.306,-1698.38,1.570796,0,0,21375,0,219,219,0,0,0,0),
    (1100000008,20,53803,22,4380,-3389.728,-1033.423,-1663.021,-1.570796,0,0,28700,0,219,219,0,0,0,0),
    (1100000009,20,53813,22,4380,-3390.033,-1032.306,-1673.228,-1.570796,0,0,21375,0,219,219,0,0,0,0),
    (1100000010,20,53834,22,4380,-3372.087,-1032.306,-1685.699,1.570796,0,0,21375,0,219,219,0,0,0,0),
    (1100000011,20,53836,22,4380,-3390.102,-1032.306,-1698.539,-1.570796,0,0,21375,0,219,219,0,0,0,0),
    (1100000012,20,53837,22,4380,-3381.156,-1032.018,-1653.297,0,0,0,21375,0,219,219,0,0,0,0),
    (1100000013,20,53856,22,4380,-3389.938,-1032.306,-1685.809,-1.570796,0,0,21375,0,219,219,0,0,0,0),
    (1100000014,10,62465,22,4380,-3376.684,-1031.522,-1876.902,1.570796,0,0,27415,0,219,219,0,0,0,0),
    (1100000015,10,44961,22,2193,-3450.17,-890.5897,-739.757,0,0,0,27341,9016,170,170,0,0,0,0),
    (1100000016,14,46182,22,2193,-3605.21,-878.0894,-786.391,-2.34866,0,0,24632,0,219,219,0,0,0,0),
    (1100000017,14,13306,930,695,-7.47,0,19.02,0,0,0,23553,0,219,219,0,0,0,0);

-- official Thayd/Illium housing intro questChecklistIdx reconciliation: 8 row(s)
-- WIP/GUESSED: branch QuestChecklistIdx values match the existing HousingIntroEntityScript creature/story-panel mapping and are keyed to official worlddb rows by creature, ActivePropId, and exact coordinates.
-- WIP/GUESSED: fallback INSERT statements add the exact source row only when an older local import lacks the official housing prop.
--   Zen Pond: questChecklistIdx 1; source Map/Open World/Olyssia/Illium.sql
UPDATE `entity` SET `questChecklistIdx` = 1 WHERE `world` = 22 AND `creature` = 65296 AND `activePropId` = 2619935741074 AND ABS(`x` - (-3309.436)) < 0.001 AND ABS(`y` - (-903.7229)) < 0.001 AND ABS(`z` - (-859.9409)) < 0.001;
INSERT INTO `entity` (`id`, `type`, `creature`, `world`, `area`, `x`, `y`, `z`, `rx`, `ry`, `rz`, `displayinfo`, `outfitinfo`, `faction1`, `faction2`, `questchecklistidx`, `activepropid`, `worldsocketid`, `mode`)
SELECT 1100010001,10,65296,22,3014,-3309.436,-903.7229,-859.9409,0.1227484,0.5534987,-4.247763E-07,27725,0,219,219,1,2619935741074,0,0 WHERE NOT EXISTS (SELECT 1 FROM `entity` WHERE `world` = 22 AND `creature` = 65296 AND `activePropId` = 2619935741074 AND ABS(`x` - (-3309.436)) < 0.001 AND ABS(`y` - (-903.7229)) < 0.001 AND ABS(`z` - (-859.9409)) < 0.001);
--   Windmill: questChecklistIdx 2; source Map/Open World/Olyssia/Illium.sql
UPDATE `entity` SET `questChecklistIdx` = 2 WHERE `world` = 22 AND `creature` = 65297 AND `activePropId` = 2602755871890 AND ABS(`x` - (-3307.637)) < 0.001 AND ABS(`y` - (-903.723)) < 0.001 AND ABS(`z` - (-901.6152)) < 0.001;
INSERT INTO `entity` (`id`, `type`, `creature`, `world`, `area`, `x`, `y`, `z`, `rx`, `ry`, `rz`, `displayinfo`, `outfitinfo`, `faction1`, `faction2`, `questchecklistidx`, `activepropid`, `worldsocketid`, `mode`)
SELECT 1100010002,10,65297,22,3014,-3307.637,-903.723,-901.6152,3.044327,0.553498,7.926234E-07,27725,0,219,219,2,2602755871890,0,0 WHERE NOT EXISTS (SELECT 1 FROM `entity` WHERE `world` = 22 AND `creature` = 65297 AND `activePropId` = 2602755871890 AND ABS(`x` - (-3307.637)) < 0.001 AND ABS(`y` - (-903.723)) < 0.001 AND ABS(`z` - (-901.6152)) < 0.001);
--   Power Generator: questChecklistIdx 3; source Map/Open World/Olyssia/Illium.sql
UPDATE `entity` SET `questChecklistIdx` = 3 WHERE `world` = 22 AND `creature` = 65298 AND `activePropId` = 283473532050 AND ABS(`x` - (-3329.727)) < 0.001 AND ABS(`y` - (-903.7228)) < 0.001 AND ABS(`z` - (-879.0459)) < 0.001;
INSERT INTO `entity` (`id`, `type`, `creature`, `world`, `area`, `x`, `y`, `z`, `rx`, `ry`, `rz`, `displayinfo`, `outfitinfo`, `faction1`, `faction2`, `questchecklistidx`, `activepropid`, `worldsocketid`, `mode`)
SELECT 1100010003,10,65298,22,3014,-3329.727,-903.7228,-879.0459,-1.448045,0.5534992,7.006621E-08,27725,0,219,219,3,283473532050,0,0 WHERE NOT EXISTS (SELECT 1 FROM `entity` WHERE `world` = 22 AND `creature` = 65298 AND `activePropId` = 283473532050 AND ABS(`x` - (-3329.727)) < 0.001 AND ABS(`y` - (-903.7228)) < 0.001 AND ABS(`z` - (-879.0459)) < 0.001);
--   Storage Unit: questChecklistIdx 4; source Map/Open World/Olyssia/Illium.sql
UPDATE `entity` SET `questChecklistIdx` = 4 WHERE `world` = 22 AND `creature` = 65299 AND `activePropId` = 2791734432914 AND ABS(`x` - (-3287.171)) < 0.001 AND ABS(`y` - (-903.7228)) < 0.001 AND ABS(`z` - (-882.6173)) < 0.001;
INSERT INTO `entity` (`id`, `type`, `creature`, `world`, `area`, `x`, `y`, `z`, `rx`, `ry`, `rz`, `displayinfo`, `outfitinfo`, `faction1`, `faction2`, `questchecklistidx`, `activepropid`, `worldsocketid`, `mode`)
SELECT 1100010004,10,65299,22,3014,-3287.171,-903.7228,-882.6173,1.488564,0.5534986,3.85364E-07,27725,0,219,219,4,2791734432914,0,0 WHERE NOT EXISTS (SELECT 1 FROM `entity` WHERE `world` = 22 AND `creature` = 65299 AND `activePropId` = 2791734432914 AND ABS(`x` - (-3287.171)) < 0.001 AND ABS(`y` - (-903.7228)) < 0.001 AND ABS(`z` - (-882.6173)) < 0.001);
--   Zen Pond: questChecklistIdx 1; source Map/Open World/Alizar/Thayd.sql
UPDATE `entity` SET `questChecklistIdx` = 1 WHERE `world` = 51 AND `creature` = 54400 AND `activePropId` = 2619935753624 AND ABS(`x` - (4078.783)) < 0.001 AND ABS(`y` - (-818.9699)) < 0.001 AND ABS(`z` - (-1653.37)) < 0.001;
INSERT INTO `entity` (`id`, `type`, `creature`, `world`, `area`, `x`, `y`, `z`, `rx`, `ry`, `rz`, `displayinfo`, `outfitinfo`, `faction1`, `faction2`, `questchecklistidx`, `activepropid`, `worldsocketid`, `mode`)
SELECT 1100010005,10,54400,51,3015,4078.783,-818.9699,-1653.37,3.00633,0.5534987,-4.072597E-07,27725,0,219,219,1,2619935753624,0,0 WHERE NOT EXISTS (SELECT 1 FROM `entity` WHERE `world` = 51 AND `creature` = 54400 AND `activePropId` = 2619935753624 AND ABS(`x` - (4078.783)) < 0.001 AND ABS(`y` - (-818.9699)) < 0.001 AND ABS(`z` - (-1653.37)) < 0.001);
--   Windmill: questChecklistIdx 2; source Map/Open World/Alizar/Thayd.sql
UPDATE `entity` SET `questChecklistIdx` = 2 WHERE `world` = 51 AND `creature` = 54401 AND `activePropId` = 2602755884440 AND ABS(`x` - (4066.41)) < 0.001 AND ABS(`y` - (-818.9699)) < 0.001 AND ABS(`z` - (-1613.534)) < 0.001;
INSERT INTO `entity` (`id`, `type`, `creature`, `world`, `area`, `x`, `y`, `z`, `rx`, `ry`, `rz`, `displayinfo`, `outfitinfo`, `faction1`, `faction2`, `questchecklistidx`, `activepropid`, `worldsocketid`, `mode`)
SELECT 1100010006,10,54401,51,3015,4066.41,-818.9699,-1613.534,-0.3552767,0.553498,7.707278E-07,27725,0,219,219,2,2602755884440,0,0 WHERE NOT EXISTS (SELECT 1 FROM `entity` WHERE `world` = 51 AND `creature` = 54401 AND `activePropId` = 2602755884440 AND ABS(`x` - (4066.41)) < 0.001 AND ABS(`y` - (-818.9699)) < 0.001 AND ABS(`z` - (-1613.534)) < 0.001);
--   Power Generator: questChecklistIdx 3; source Map/Open World/Alizar/Thayd.sql
UPDATE `entity` SET `questChecklistIdx` = 3 WHERE `world` = 51 AND `creature` = 54403 AND `activePropId` = 283473544600 AND ABS(`x` - (4093.528)) < 0.001 AND ABS(`y` - (-818.9697)) < 0.001 AND ABS(`z` - (-1629.719)) < 0.001;
INSERT INTO `entity` (`id`, `type`, `creature`, `world`, `area`, `x`, `y`, `z`, `rx`, `ry`, `rz`, `displayinfo`, `outfitinfo`, `faction1`, `faction2`, `questchecklistidx`, `activepropid`, `worldsocketid`, `mode`)
SELECT 1100010007,10,54403,51,3015,4093.528,-818.9697,-1629.719,1.435536,0.5534995,-1.751655E-07,27725,0,219,219,3,283473544600,0,0 WHERE NOT EXISTS (SELECT 1 FROM `entity` WHERE `world` = 51 AND `creature` = 54403 AND `activePropId` = 283473544600 AND ABS(`x` - (4093.528)) < 0.001 AND ABS(`y` - (-818.9697)) < 0.001 AND ABS(`z` - (-1629.719)) < 0.001);
--   Storage Unit: questChecklistIdx 4; source Map/Open World/Alizar/Thayd.sql
UPDATE `entity` SET `questChecklistIdx` = 4 WHERE `world` = 51 AND `creature` = 54404 AND `activePropId` = 2791734445464 AND ABS(`x` - (4051.468)) < 0.001 AND ABS(`y` - (-818.9697)) < 0.001 AND ABS(`z` - (-1637.125)) < 0.001;
INSERT INTO `entity` (`id`, `type`, `creature`, `world`, `area`, `x`, `y`, `z`, `rx`, `ry`, `rz`, `displayinfo`, `outfitinfo`, `faction1`, `faction2`, `questchecklistidx`, `activepropid`, `worldsocketid`, `mode`)
SELECT 1100010008,10,54404,51,3015,4051.468,-818.9697,-1637.125,-1.911039,0.5534988,4.729468E-07,27725,0,219,219,4,2791734445464,0,0 WHERE NOT EXISTS (SELECT 1 FROM `entity` WHERE `world` = 51 AND `creature` = 54404 AND `activePropId` = 2791734445464 AND ABS(`x` - (4051.468)) < 0.001 AND ABS(`y` - (-818.9697)) < 0.001 AND ABS(`z` - (-1637.125)) < 0.001);

-- Sources:
--   Map/Open World/Alizar/Thayd.sql
--   Map/Open World/Alizar/z Thayd Halon Ring update.sql
--   Map/Open World/New Zones/Halon Ring.sql
--   Map/Open World/Olyssia/Illium Museum.sql
--   Map/Open World/Olyssia/Illium.sql
--   Map/Open World/Olyssia/z Illium Halon Ring Update.sql
--   Map/Open World/Skulls Eye.sql

COMMIT;
