-- Generated by Tools/DataMapping/extract_laughingws_map_entrances.py.
-- Source: LaughingWS/NexusForever.WorldDatabase.New-Zones-and-more map_entrance rows
-- Purpose: Add missing matching map entrances without importing destructive world SQL.

USE `nexus_forever_world`;

START TRANSACTION;

-- map_entrance: 23 row(s)
INSERT IGNORE INTO `map_entrance` (`mapId`, `team`, `worldLocationId`) VALUES
    (382, 0, 1275),
    (797, 0, 7188),
    (797, 1, 7189),
    (1149, 0, 13390),
    (1181, 0, 13662),
    (1233, 0, 37409),
    (1263, 0, 17726),
    (1271, 0, 16348),
    (1323, 0, 32423),
    (1336, 0, 18557),
    (1393, 0, 38048),
    (2166, 0, 38485),
    (2166, 1, 38486),
    (2980, 0, 42236),
    (3009, 0, 50843),
    (3044, 0, 46354),
    (3045, 0, 45947),
    (3094, 0, 47085),
    (3173, 0, 48284),
    (3176, 0, 49019),
    (3449, 0, 51426),
    (3449, 1, 51427),
    (3522, 0, 53153);

-- Sources:
--   Map\Instances\Adventures\Bay of Betrayal.sql
--   Map\Instances\Adventures\Crimelords of Whitevale.sql
--   Map\Instances\Adventures\Hycrest Insurrection.sql
--   Map\Instances\Adventures\Malgrave Trail.sql
--   Map\Instances\Adventures\The Siege of Tempest Refuge.sql
--   Map\Instances\Adventures\War of the Wilds.sql
--   Map\Instances\Dungeons\Coldblood Citadel.sql
--   Map\Instances\Dungeons\Protogames Academy.sql
--   Map\Instances\Dungeons\Ruins of Kel Voreth.sql
--   Map\Instances\Dungeons\Sanctuary of the Swordmaiden.sql
--   Map\Instances\Dungeons\Skullcano.sql
--   Map\Instances\Dungeons\Stormtalon's Lair.sql
--   Map\Instances\Dungeons\Ultimate Protogames.sql
--   Map\Instances\Event instances\Protostar SuperMall-In-The-Sky.sql
--   Map\Instances\Event instances\Shade's Eve.sql
--   Map\Instances\PvP\Battle Grounds\Daggerstone Pass.sql
--   Map\Instances\PvP\Battle Grounds\Halls of the Bloodsworn Reloaded.sql
--   Map\Instances\PvP\Battle Grounds\Walatiki Temple.sql
--   Map\Instances\World Stories\Journey into OMNICore-1.sql
--   Map\Instances\World Stories\Vault of the Archon.sql

COMMIT;
