-- Generated by Tools/DataMapping/extract_laughingws_instance_entities.py.
-- Source: selected LaughingWS instance entity/event/script rows with matching current WIP script support.
-- Purpose: preserve useful instance-local rows without importing source world deletes or @GUID allocation.
-- WIP/GUESSED: instance placement/choreography is branch-authored; manual client smoke is required before retail parity is claimed.

USE `nexus_forever_world`;

START TRANSACTION;

-- Entity evidence and WIP scope:
--   1100300001: Coldblood Citadel Hailstone Gatecrasher; source creature 75508; event 907 phase 1; Branch SQL supplies event 907 phase 1, level stat 50, and HailstoneGatecrasherEntityScript; current C# has the WIP-guessed event script and matching entity script.
--   1100300002: Coldblood Citadel Gather Ring; source creature 75624; event 907 phase 0; Branch SQL supplies event 907 phase 0; current C# tracks and removes PublicEventCreature.GatherRing during the WIP-guessed phase handoff.
--   1100300003: Coldblood Citadel Coldblood Gate; source creature 75698; event 907 phase 2; Branch SQL supplies event 907 phase 2; exact door choreography is still blocked, so this remains a WIP placement row.
--   1100300004: Protostar SuperMall Gather Marker; source creature 68636; event 679 phase 0; Branch SQL supplies event 679 phase 0; current runtime only has the map binding, so event routing/cinematics remain blocked.
--   1100300005: Space Madness Captain Tero; source creature 45900; event 390 phase 0; Branch SQL supplies event 390 phase 0 and the current Space Madness event script starts at TalkToCaptainTero; placement is preserved as WIP/GUESSED pending manual expedition smoke.
--   1100300006: Space Madness Major Lee Barmy; source creature 45812; event 390 phase 1; Branch SQL supplies event 390 phase 1 and the current Space Madness event script advances to TalkToMajorLeeBarmy; placement is preserved as WIP/GUESSED pending manual expedition smoke.
--   1100300007: Space Madness Observation Deck Computer; source creature 45972; event 390 phase 2; Branch SQL supplies event 390 phase 2 for the observation-deck computer; the source comment says coordinates need fixing, so this remains WIP/GUESSED placement data.
--   1100300008: Space Madness Hazmat Control Panel; source creature 46092; event 390 phase 3; Branch SQL supplies event 390 phase 3 for the hazmat control panel; the source comment says coordinates need fixing, so this remains WIP/GUESSED placement data.
--   1100300009: Space Madness Exact Change 3.0; source creature 46483; event 390 phase 4; Branch SQL supplies event 390 phase 4 and source level/stat notes for Exact Change 3.0; current script only activates the livestock phase objective, so combat behavior remains blocked.
--   1100300010: Space Madness Blazing Crewman A; source creature 46714; event 390 phase 4; Branch SQL supplies the first event 390 phase 4 Blazing Crewman row; current script only activates phase objectives, so spawn/combat behavior remains WIP/GUESSED.
--   1100300011: Space Madness Blazing Crewman B; source creature 46714; event 390 phase 4; Branch SQL supplies the second event 390 phase 4 Blazing Crewman row; current script only activates phase objectives, so spawn/combat behavior remains WIP/GUESSED.
--   1100300012: Space Madness Hazmat Suit; source creature 45981; event 390 phase 5; Branch SQL supplies event 390 phase 5 for the hazmat suit; the source comment says coordinates need fixing, so this remains WIP/GUESSED placement data.
--   1100300013: Gauntlet Pilot Taboro; source creature 48580; event 446 phase 0; Branch SQL supplies event 446 phase 0 and the current Gauntlet event script starts at TalkToPilotTaboro; placement is preserved as WIP/GUESSED pending manual expedition smoke.
--   1100300014: Gauntlet Gather Marker; source creature 58979; no source entity_event row; Branch SQL supplies a static gather marker with no entity_event row; current Gauntlet script creates gather triggers dynamically, so this placement stays WIP/GUESSED and choreography-blocked.
--   1100300015: Fragment Zero Freight Supervisor Lola; source creature 71762; no source entity_event row; Branch SQL supplies Freight Supervisor Lola as a static Fragment Zero row; current script uses Supervisor Lola communicator ids, but exact NPC phase/timing proof remains blocked.
--   1100300016: Infestation Captain Tolben; source creature 71764; no source entity_event row; Branch SQL supplies Captain Tolben as a static Infestation row; current script starts the cargo-ship objective chain, but exact NPC interaction/timing proof remains blocked.
--   1100300017: Outpost M-13 Captain Milo; source creature 41201; event 108 phase 0; Branch SQL supplies event 108 phase 0 and the current Outpost M-13 event script starts at TalkToCaptainMilo; placement is preserved as WIP/GUESSED pending manual expedition smoke.
--   1100300018: Evil from the Ether Drive Spark A; source creature 71847; event 781 phase 23; Branch SQL supplies event 781 phase 23, which maps to the current PickUpDriveSchematics phase; official DB has no matching row, so this is WIP/GUESSED visual/objective-phase placement only.
--   1100300019: Evil from the Ether Drive Spark B; source creature 71847; event 781 phase 23; Branch SQL supplies event 781 phase 23, which maps to the current PickUpDriveSchematics phase; official DB has no matching row, so this is WIP/GUESSED visual/objective-phase placement only.
--   1100300020: Evil from the Ether Drive Spark C; source creature 71847; event 781 phase 23; Branch SQL supplies event 781 phase 23, which maps to the current PickUpDriveSchematics phase; official DB has no matching row, so this is WIP/GUESSED visual/objective-phase placement only.
--   1100300021: Evil from the Ether Drive Spark D; source creature 71847; event 781 phase 23; Branch SQL supplies event 781 phase 23, which maps to the current PickUpDriveSchematics phase; official DB has no matching row, so this is WIP/GUESSED visual/objective-phase placement only.
--   1100300022: Evil from the Ether Drive Spark E; source creature 71847; event 781 phase 23; Branch SQL supplies event 781 phase 23, which maps to the current PickUpDriveSchematics phase; official DB has no matching row, so this is WIP/GUESSED visual/objective-phase placement only.
--   1100300023: Evil from the Ether Drive Spark F; source creature 71847; event 781 phase 23; Branch SQL supplies event 781 phase 23, which maps to the current PickUpDriveSchematics phase; official DB has no matching row, so this is WIP/GUESSED visual/objective-phase placement only.
--   1100300024: Evil from the Ether Drive Spark G; source creature 71847; event 781 phase 23; Branch SQL supplies event 781 phase 23, which maps to the current PickUpDriveSchematics phase; official DB has no matching row, so this is WIP/GUESSED visual/objective-phase placement only.
--   1100300025: Evil from the Ether Drive Spark H; source creature 71847; event 781 phase 23; Branch SQL supplies event 781 phase 23, which maps to the current PickUpDriveSchematics phase; official DB has no matching row, so this is WIP/GUESSED visual/objective-phase placement only.
--   1100300026: Evil from the Ether Drive Spark I; source creature 71847; event 781 phase 23; Branch SQL supplies event 781 phase 23, which maps to the current PickUpDriveSchematics phase; official DB has no matching row, so this is WIP/GUESSED visual/objective-phase placement only.
--   1100300027: Evil from the Ether Drive Spark J; source creature 71847; event 781 phase 23; Branch SQL supplies event 781 phase 23, which maps to the current PickUpDriveSchematics phase; official DB has no matching row, so this is WIP/GUESSED visual/objective-phase placement only.
--   1100300028: Evil from the Ether Drive Spark K; source creature 71847; event 781 phase 23; Branch SQL supplies event 781 phase 23, which maps to the current PickUpDriveSchematics phase; official DB has no matching row, so this is WIP/GUESSED visual/objective-phase placement only.
--   1100300029: Protogames Academy portal A; source creature 62475; event 667 phase 8; Branch SQL supplies event 667 phase 8, but the source notes the portal may belong only to Ultimate Protogames; current C# uses a dynamic WIP teleporter trigger, so this static portal remains WIP/GUESSED.
--   1100300030: Protogames Academy portal B; source creature 62475; event 667 phase 16; Branch SQL supplies event 667 phase 16, but the source notes the portal may belong only to Ultimate Protogames; current C# uses a dynamic WIP teleporter trigger, so this static portal remains WIP/GUESSED.
--   1100300031: Protogames Academy Invulnotron; source creature 67475; event 667 phase 3; Branch SQL supplies event 667 phase 3 and InvulnotronEntityScript; current C# has a WIP objective-credit script, while combat behavior and spawn timing remain blocked.
--   1100300032: Protogames Academy Room 1 Launcher; source creature 67539; event 667 phase 4; Branch SQL supplies event 667 phase 4 and notes the faction is uncertain; current C# uses WIP gather/teleporter triggers, so launcher interaction/choreography remains blocked.
--   1100300033: Protogames Academy Gromka; source creature 67594; event 667 phase 5; Branch SQL supplies event 667 phase 5 and GromkaEntityScript; current C# has a WIP objective-credit script, while combat behavior and spawn timing remain blocked.
--   1100300034: Protogames Academy Iruki Boldbeard; source creature 67663; event 667 phase 7; Branch SQL supplies event 667 phase 7 and IrukiBoldbeardEntityScript; current C# has a WIP objective-credit script, while combat behavior and spawn timing remain blocked.
--   1100300035: Protogames Academy Seek-N-Slaughter; source creature 67668; event 667 phase 11; Branch SQL supplies event 667 phase 11 and current C# activates DefeatSeekNSlaughter; this WIP objective-credit script only grants death credit, while combat behavior remains blocked.
--   1100300036: Protogames Academy Icebox Mk. 2; source creature 67757; event 667 phase 13; Branch SQL supplies event 667 phase 13 and current C# activates DefeatIceboxMk2; this WIP objective-credit script only grants death credit, while combat behavior remains blocked.
--   1100300037: Protogames Academy Initiation Button; source creature 68339; no source entity_event row; Branch SQL supplies a static initiation button but no entity_event row, and the source questions the ActivePropId; current C# starts the initiation objective, so this remains WIP/GUESSED placement data.
--   1100300038: Protogames Academy gather marker Invulnotron; source creature 70003; event 667 phase 1; Branch SQL supplies the first event 667 gather marker; current C# creates WIP gather triggers dynamically, so the static placement remains WIP/GUESSED pending trigger cleanup proof.
--   1100300039: Protogames Academy gather marker Gromka; source creature 70003; event 667 phase 4; Branch SQL supplies the second event 667 gather marker; current C# creates WIP gather triggers dynamically, so the static placement remains WIP/GUESSED pending trigger cleanup proof.
--   1100300041: Protogames Academy gather marker arena A; source creature 70003; event 667 phase 9; Branch SQL supplies the fourth event 667 gather marker; current C# creates WIP gather triggers dynamically, so the static placement remains WIP/GUESSED pending trigger cleanup proof.
--   1100300044: Ruins of Kel Voreth Forgemaster Trogun; source creature 32531; event 161 phase 3; Branch SQL supplies event 161 phase 3 and ForgemasterTrogunEntityScript; current C# has a WIP objective-credit script, while exact boss combat and door choreography remain blocked.
--   1100300045: Ruins of Kel Voreth Grond the Corpsemaker; source creature 32534; event 161 phase 1; Branch SQL supplies event 161 phase 1 and GrondTheCorpsemakerEntityScript; current C# has a WIP objective-credit script, while exact boss combat and encounter choreography remain blocked.
--   1100300046: Ruins of Kel Voreth Slavemaster Drokk; source creature 32536; event 161 phase 2; Branch SQL supplies event 161 phase 2 and SlavemasterDrokkEntityScript; current C# has a WIP objective-credit script, while exact boss combat and faction-specific messaging remain blocked.
--   1100300047: Stormtalon's Lair Aethros; source creature 32703; event 145 phase 2; Branch SQL supplies event 145 phase 2 and AethrosVeteranEntityScript; current C# has a WIP objective-credit script, while exact boss combat and Stormtalon choreography remain blocked.
--   1100300048: Stormtalon's Lair Blade-Wind the Invoker; source creature 33405; event 145 phase 1; Branch SQL supplies event 145 phase 1 and BladeWindTheInvokerVeteranEntityScript; current C# has a WIP objective-credit script, while exact boss combat and optional route availability remain blocked.
--   1100300049: Skullcano Thunderfoot; source creature 24475; event 148 phase 0; Branch SQL supplies event 148 phase 0 and ThunderfootNormalEntityScript; current C# has a WIP objective-credit script, while exact boss combat and route choreography remain blocked.
--   1100300050: Skullcano Stew-Shaman Tugga; source creature 24493; event 148 phase 0; Branch SQL supplies event 148 phase 0 and StewShamanTuggaNormalEntityScript; current C# has a WIP objective-credit script, while exact boss combat and cave/chasm route selection remain blocked.
--   1100300051: Sanctuary of the Swordmaiden Flame-Crazed Demon; source creature 29254; event 166 phase 4; Branch SQL supplies event 166 phase 4 and FlameCrazedDemonEntityScript; current C# has a WIP objective-credit script, while exact miniboss combat and path selection remain blocked.
--   1100300052: Genetic Archives Experiment X-89; source creature 49198; no source entity_event row; Branch SQL supplies ExperimentX-89EntityScript without an entity_event row; current C# has a WIP objective-credit script, while raid encounter choreography remains blocked.
--   1100300053: Genetic Archives Kuralak the Defiler; source creature 52969; no source entity_event row; Branch SQL supplies KuralakTheDefilerEntityScript without an entity_event row; current C# has a WIP objective-credit script, while raid encounter choreography remains blocked.
--   1100300054: Genetic Archives Pillar of the Genetic Library; source creature 53031; no source entity_event row; Branch SQL supplies KuralakPillarEntityScript without an entity_event row; current C# intentionally keeps the script as a WIP no-op loader hook until Kuralak pillar mechanics are mapped.
--   1100300055: Ultimate Protogames Bev-O-Rage; source creature 61463; event 594 phase 5; Branch SQL supplies event 594 phase 5 and level stat 50; current runtime only has the map binding, so event routing, objective credit, combat behavior, and manual dungeon smoke remain blocked.
--   1100300056: Red Moon Terror Laveka; source creature 65997; no source entity_event row; Branch SQL supplies a static Laveka row with health marker and level stats; current C# has the WIP-guessed Red Moon Terror event chain and a WIP objective-credit script for the final Laveka objective, while boss choreography, awakening/challenge logic, and manual raid smoke remain blocked.
--   1100300057: Shade's Eve Etty Windsen; source creature 62747; event 597 phase 1; Branch SQL supplies event 597 phase 1 and source level stat 50; current Shade's Eve script advances to SpeakWithEttyWindsen, but exact NPC interaction and cinematic/vote timing remain blocked.
--   1100300058: Shade's Eve Fountain Gathering Circle; source creature 64820; event 597 phase 0; Branch SQL supplies event 597 phase 0 and the current Shade's Eve script starts at FindTheFountain; gather cleanup and exact cinematic timing remain WIP/GUESSED.
--   1100300059: Datascape Optimized Memory Probe ED-1; source creature 61819; event 157 phase 0; Branch SQL supplies placed ED-1 coordinates and commented event 157 phase 0; current C# activates DefeatOptimizedMemoryProbeED1, while exact mechanics remain blocked.
--   1100300060: Datascape Optimized Memory Probe TX-67; source creature 61818; event 157 phase 0; Branch SQL supplies placed TX-67 coordinates and commented event 157 phase 0; current C# has the WIP objective-credit script, while exact mechanics remain blocked.
--   1100300061: Datascape Optimized Memory Probe P2-Z; source creature 31667; event 157 phase 0; Branch SQL supplies placed P2-Z coordinates and commented event 157 phase 0; current C# activates DefeatOptimizedMemoryProbeP2Z, while exact mechanics remain blocked.
--   1100300062: Datascape Null System Daemon; source creature 30495; event 157 phase 0; Branch SQL supplies event 157 phase 0 and current C# starts by activating DefeatTheSystemDaemons; exact daemon encounter mechanics remain blocked.
--   1100300063: Datascape Binary System Daemon; source creature 30496; event 157 phase 0; Branch SQL supplies event 157 phase 0 and current C# starts by activating DefeatTheSystemDaemons; exact daemon encounter mechanics remain blocked.
--   1100300064: Datascape First Frost Boulder Avalanche; source creature 31677; event 157 phase 3; Branch SQL supplies placed Frost Boulder coordinates; phase 3 is WIP-guessed from the current Datascape event script's FirstFrostBoulder phase.
--   1100300065: Datascape Second Frost Boulder Avalanche; source creature 56200; event 157 phase 4; Branch SQL supplies placed Frost Boulder coordinates; phase 4 is WIP-guessed from the current Datascape event script's SecondFrostBoulder phase.
--   1100300066: Datascape Frostbringer Warlock; source creature 31674; event 157 phase 5; Branch SQL supplies placed Frostbringer Warlock coordinates; phase 5 is WIP-guessed from the current Datascape event script's FrostbringerWarlock phase.
--   1100300067: Datascape Bio-Enhanced Broodmother; source creature 31885; event 157 phase 0; Branch SQL supplies placed Bio-Enhanced Broodmother coordinates; current C# activates this objective from ED-1 completion without a mapped separate phase, so phase 0 is WIP-guessed.
--   1100300068: Datascape Gloomclaw; source creature 30498; event 157 phase 11; Branch SQL supplies placed Gloomclaw coordinates; phase 11 is WIP-guessed from the current Datascape event script's Gloomclaw phase.
--   1100300069: Datascape Hyper-Accelerated Skeledroid; source creature 48065; event 157 phase 12; Branch SQL supplies placed Hyper-Accelerated Skeledroid coordinates; current C# activates this sub-objective during LogicWingRoom1, so phase 12 is WIP-guessed.
--   1100300070: Datascape Augmented Herald of Avatus; source creature 48374; event 157 phase 14; Branch SQL supplies placed Augmented Herald coordinates; current C# activates this sub-objective during LogicWingRoom3, so phase 14 is WIP-guessed.
--   1100300071: Datascape Warmonger Agratha; source creature 48295; event 157 phase 19; Branch SQL supplies placed Warmonger Agratha coordinates; phase 19 is WIP-guessed from the current Datascape event script.
--   1100300072: Datascape Warmonger Chuna; source creature 48916; event 157 phase 20; Branch SQL supplies placed Warmonger Chuna coordinates; phase 20 is WIP-guessed from the current Datascape event script.
--   1100300073: Datascape Warmonger Talarii; source creature 48917; event 157 phase 21; Branch SQL supplies placed Warmonger Talarii coordinates; phase 21 is WIP-guessed from the current Datascape event script.
--   1100300074: Datascape Grand Warmonger Targresh; source creature 48177; event 157 phase 22; Branch SQL supplies placed Grand Warmonger Targresh coordinates; phase 22 is WIP-guessed from the current Datascape event script.
--   1100300075: Datascape Avatus; source creature 30505; event 157 phase 26; Branch SQL supplies placed Avatus coordinates; phase 26 is WIP-guessed from the current Datascape event script's Avatus phase.

-- entity: 72 row(s)
INSERT INTO `entity` (`id`, `type`, `creature`, `world`, `area`, `x`, `y`, `z`, `rx`, `ry`, `rz`, `displayInfo`, `outfitInfo`, `faction1`, `faction2`, `questChecklistIdx`, `activePropId`, `worldSocketId`, `mode`) VALUES
  (1100300001, 0, 75508, 3522, 0, 459.544, -467.2018, -596.769, 0, 0, 0, 24808, 0, 691, 691, 0, 0, 0, 0),
  (1100300002, 10, 75624, 3522, 0, 604.33, -475.452, -322.957, 0, 0, 0, 30327, 0, 219, 219, 0, 0, 0, 0),
  (1100300003, 4, 75698, 3522, 0, 371, -456.92, -592.31, 1.570796327, 0, 0, 36619, 0, 219, 219, 0, 0, 0, 0),
  (1100300004, 10, 68636, 3094, 0, 560.946, -908.0902, 119.026, 0, 0, 0, 30327, 0, 219, 219, 0, 0, 0, 0),
  (1100300005, 0, 45900, 2149, 2483, -14.70037, 4.950619, 337.0874, 0, 0, 0, 28578, 0, 466, 466, 0, 0, 0, 0),
  (1100300006, 0, 45812, 2149, 2482, -40.0482, 4.858062, 310.5947, 0, 0, 0, 29020, 9128, 219, 219, 0, 0, 0, 0),
  (1100300007, 10, 45972, 2149, 2415, -39.72298, 7.399887, 158.1838, 0, 0, 0, 23951, 0, 219, 219, 0, 0, 0, 0),
  (1100300008, 10, 46092, 2149, 2415, 7.77, 7.399887, 84.36, 0, 0, 0, 23951, 0, 219, 219, 0, 0, 0, 0),
  (1100300009, 0, 46483, 2149, 2415, 25.23, -2.91, 120.42, 1.57079, 0, 0, 27827, 0, 218, 218, 0, 0, 0, 0),
  (1100300010, 0, 46714, 2149, 2415, 7.12621, -2.9093, 112.0714, 2.64731, 0, 0, 26022, 9347, 218, 218, 0, 0, 0, 0),
  (1100300011, 0, 46714, 2149, 2415, 12.919, -2.91, 124.5722, 2.64731, 0, 0, 26022, 9347, 218, 218, 0, 0, 0, 0),
  (1100300012, 10, 45981, 2149, 2415, 4.41, 0, 72.89, 0, 0, 0, 23951, 0, 219, 219, 0, 0, 0, 0),
  (1100300013, 0, 48580, 2183, 2620, 541.0117, 0.2229719, -513.6139, 0, 0, 0, 21338, 0, 219, 219, 0, 0, 0, 0),
  (1100300014, 10, 58979, 2183, 2620, 523.0805, 0.1994047, -507.9437, 0, 0, 0, 30327, 0, 219, 219, 0, 0, 0, 0),
  (1100300015, 0, 71762, 3180, 4619, 9873.75, -765.9531, -5848.58, 0, 0, 0, 32807, 0, 219, 219, 0, 0, 0, 0),
  (1100300016, 0, 71764, 1232, 1158, 4.41241, -500, 14.0114, 0, 0, 0, 28578, 0, 219, 219, 0, 0, 0, 0),
  (1100300017, 0, 41201, 1319, 1540, 9791.18, -932.668, 5264.279, 0, 0, 0, 28578, 0, 466, 466, 0, 0, 0, 0),
  (1100300018, 0, 71847, 3404, 0, -62.29986, -826.7423, 315.39798, -3.1415925, -0, 0, 24324, 0, 219, 219, 0, 0, 0, 0),
  (1100300019, 0, 71847, 3404, 0, -42.11708, -819.4943, 316.413, -3.1415925, -0, 0, 24324, 0, 219, 219, 0, 0, 0, 0),
  (1100300020, 0, 71847, 3404, 0, -50.01624, -826.74396, 309.8, -3.1415925, -0, 0, 24324, 0, 219, 219, 0, 0, 0, 0),
  (1100300021, 0, 71847, 3404, 0, -63.714478, -817.7603, 312.456, -3.1415925, -0, 0, 24324, 0, 219, 219, 0, 0, 0, 0),
  (1100300022, 0, 71847, 3404, 0, -43.03138, -826.57556, 313.40698, -3.1415925, -0, 0, 24324, 0, 219, 219, 0, 0, 0, 0),
  (1100300023, 0, 71847, 3404, 0, -51.01272, -819.90674, 320.367, -3.1415925, -0, 0, 24324, 0, 219, 219, 0, 0, 0, 0),
  (1100300024, 0, 71847, 3404, 0, -59.60385, -818.0261, 320.757, -3.1415925, -0, 0, 24324, 0, 219, 219, 0, 0, 0, 0),
  (1100300025, 0, 71847, 3404, 0, -47.63262, -813.7216, 320.81198, -3.1415925, -0, 0, 24324, 0, 219, 219, 0, 0, 0, 0),
  (1100300026, 0, 71847, 3404, 0, -55.35622, -815.50745, 306.914, -3.1415925, -0, 0, 24324, 0, 219, 219, 0, 0, 0, 0),
  (1100300027, 0, 71847, 3404, 0, -58.10405, -818.83215, 310.94598, -3.1415925, -0, 0, 24324, 0, 219, 219, 0, 0, 0, 0),
  (1100300028, 0, 71847, 3404, 0, -51.504288, -820.1912, 304.748, -3.1415925, -0, 0, 24324, 0, 219, 219, 0, 0, 0, 0),
  (1100300029, 20, 62475, 3173, 4651, -24400.19, -974.6682, -28977.15, 0, 0, 0, 35019, 0, 219, 219, 0, 0, 0, 0),
  (1100300030, 20, 62475, 3173, 4507, -19804.34, -945.5437, -29483.94, 0, 0, 0, 35019, 0, 219, 219, 0, 1, 0, 0),
  (1100300031, 0, 67475, 3173, 4651, -24330.6, -974.0855, -28917.8, 0, 0, 0, 24783, 0, 1322, 1322, 0, 0, 0, 0),
  (1100300032, 0, 67539, 3173, 4651, -24330.6, -974.0855, -28950.8, 0, 0, 0, 23539, 0, 219, 219, 0, 0, 0, 0),
  (1100300033, 0, 67594, 3173, 4507, -24424.6, -974.0912, -28788.1, 0, 0, 0, 28878, 0, 1322, 1322, 0, 0, 0, 0),
  (1100300034, 0, 67663, 3173, 4507, -24360.97, -972.6974, -28943.9, 0, 0, 0, 32741, 0, 1322, 1322, 0, 0, 0, 0),
  (1100300035, 0, 67668, 3173, 4507, -19777.14, -946.8414, -29457.42, 0, 0, 0, 21309, 0, 233, 233, 0, 0, 0, 0),
  (1100300036, 0, 67757, 3173, 4507, -19777.14, -946.8414, -29457.42, 0, 0, 0, 21323, 0, 233, 233, 0, 0, 0, 0),
  (1100300037, 10, 68339, 3173, 4509, -29439.2, -776.479, -29381.5, 0, 0, 0, 25115, 0, 219, 219, 0, 202490, 0, 0),
  (1100300038, 10, 70003, 3173, 4651, -24400.12, -974.6682, -28977.07, 0, 0, 0, 30327, 0, 219, 219, 0, 0, 0, 0),
  (1100300039, 10, 70003, 3173, 4507, -24504.89, -974.7488, -28857.48, 0, 0, 0, 30327, 0, 219, 219, 0, 0, 0, 0),
  (1100300041, 10, 70003, 3173, 4507, -19804.34, -945.5437, -29483.94, 0, 0, 0, 30327, 0, 219, 219, 0, 0, 0, 0),
  (1100300044, 0, 32531, 1336, 0, -24.77, -737.08, 990.32, 0, 0, 0, 29203, 0, 691, 691, 0, 0, 0, 0),
  (1100300045, 0, 32534, 1336, 0, 195.41, -899.36, 225.65, 0, 0, 0, 27715, 0, 691, 691, 0, 0, 0, 0),
  (1100300046, 0, 32536, 1336, 0, 596.36, -882.84, 976.53, 0, 0, 0, 27104, 0, 691, 691, 0, 0, 0, 0),
  (1100300047, 0, 32703, 382, 271, -52.71065, -48.68514, 220.7862, 0, 0, 0, 27874, 0, 586, 586, 0, 0, 0, 0),
  (1100300048, 0, 33405, 382, 271, -88.49673, -11.51191, 123.5562, 0, 0, 0, 23629, 0, 586, 586, 0, 0, 0, 0),
  (1100300049, 0, 24475, 1263, 4793, 115.26, -923.71, -491.56, 0, 0, 0, 21318, 0, 242, 242, 0, 0, 0, 0),
  (1100300050, 0, 24493, 1263, 1220, 508.5147, -978.8553, -367.8973, 0, 0, 0, 27916, 0, 868, 868, 0, 0, 0, 0),
  (1100300051, 0, 29254, 1271, 1556, 4877.322, -797.6906, -3318.368, 0, 0, 0, 24811, 0, 978, 978, 0, 0, 0, 0),
  (1100300052, 0, 49198, 1462, 0, -1147.055, -111.3793, -520.5323, -2, 0, 0, 27899, 0, 1209, 1209, 0, 0, 0, 0),
  (1100300053, 0, 52969, 1462, 0, 169.4765, -110.4199, -489.5547, 2.093871, 0, 0, 30276, 0, 1209, 1209, 0, 0, 0, 0),
  (1100300054, 0, 53031, 1462, 0, 133.965, -111.45, -505.34, 0, 0, 0, 27557, 0, 1209, 1209, 0, 0, 0, 0),
  (1100300055, 0, 61463, 2980, 0, -12737.13, -797.0872, 1326.347, 0, 0, 0, 36682, 0, 219, 219, 0, 0, 0, 0),
  (1100300056, 0, 65997, 3032, 5996, -723.7178, 186.8427, -265.1872, 3.1415926536, 0, 0, 38426, 0, 1351, 1351, 0, 0, 0, 0),
  (1100300057, 0, 62747, 3044, 0, 340.9081115722656, -869.3984375, -256.90118408203125, 2.9192612171173096, 0, 0, 23053, 7913, 219, 219, 0, 0, 0, 0),
  (1100300058, 10, 64820, 3044, 0, 333.415283203125, -871.3636474609375, -242.43496704101562, -3.141592502593994, 0, 0, 30327, 0, 219, 219, 0, 0, 0, 0),
  (1100300059, 0, 61819, 1333, 1301, 618.551, -215.61023, 75, 0, 0, 0, 30425, 0, 1171, 1171, 0, 0, 0, 0),
  (1100300060, 0, 61818, 1333, 1301, 865, -215.6028, -173.5, 1.55485, 0, 0, 30425, 0, 1171, 1171, 0, 0, 0, 0),
  (1100300061, 0, 31667, 1333, 1301, 618, -216.15657, -421, 3.10206, 0, 0, 30425, 0, 1171, 1171, 0, 0, 0, 0),
  (1100300062, 0, 30495, 1333, 1349, 132.5, -226.5, -67, 0, 0, 0, 33172, 0, 1171, 1171, 0, 0, 0, 0),
  (1100300063, 0, 30496, 1333, 1349, 132.5, -226.5, -263, 3.08953, 0, 0, 33172, 0, 1171, 1171, 0, 0, 0, 0),
  (1100300064, 0, 31677, 1333, 4475, 3356.48, -765.57, -3246.29, 0.17427, 0, 0, 27434, 0, 1171, 1171, 0, 0, 0, 0),
  (1100300065, 0, 56200, 1333, 4476, 3635.073, -745.20, -3373.29, 1.11529, 0, 0, 27434, 0, 1171, 1171, 0, 0, 0, 0),
  (1100300066, 0, 31674, 1333, 4476, 3328.50, -696.86, -3639.44, -1.42842, 0, 0, 23490, 0, 1171, 1171, 0, 0, 0, 0),
  (1100300067, 0, 31885, 1333, 1590, 2985.78, -794.348, 3396.41, -0.693315, 0, 0, 27107, 0, 1171, 1171, 0, 0, 0, 0),
  (1100300068, 0, 30498, 1333, 1609, 4310, -567.817, -16812, -3.08841, 0, 0, 32992, 0, 1171, 1171, 0, 0, 0, 0),
  (1100300069, 0, 48065, 1333, 2371, -22076.3, 598.146, -15934.1, 1, 0, 0, 28678, 0, 1171, 1171, 0, 0, 0, 0),
  (1100300070, 0, 48374, 1333, 2373, -22050.2, 619.71, -14309.2, 2.56983, 0, 0, 28901, 0, 1171, 1171, 0, 0, 0, 0),
  (1100300071, 0, 48295, 1333, 1594, -4018.35, -905.709, 2575.45, -1.7226, 0, 0, 36939, 0, 1171, 1171, 0, 0, 0, 0),
  (1100300072, 0, 48916, 1333, 4478, -4350.04, -913.187, 2404.41, -1.44454, 0, 0, 36939, 0, 1171, 1171, 0, 0, 0, 0),
  (1100300073, 0, 48917, 1333, 4479, -4359.49, -903.383, 2590.74, 0.19367, 0, 0, 36939, 0, 1171, 1171, 0, 0, 0, 0),
  (1100300074, 0, 48177, 1333, 1479, -4403.72, -821.913, 2679.14, -1.63275, 0, 0, 36938, 0, 1171, 1171, 0, 0, 0, 0),
  (1100300075, 0, 30505, 1333, 1301, 618, -198.7, -174, 1.61258, 0, 0, 28937, 0, 1171, 1171, 0, 0, 0, 0)
ON DUPLICATE KEY UPDATE `type` = VALUES(`type`), `creature` = VALUES(`creature`), `world` = VALUES(`world`), `area` = VALUES(`area`), `x` = VALUES(`x`), `y` = VALUES(`y`), `z` = VALUES(`z`), `rx` = VALUES(`rx`), `ry` = VALUES(`ry`), `rz` = VALUES(`rz`), `displayInfo` = VALUES(`displayInfo`), `outfitInfo` = VALUES(`outfitInfo`), `faction1` = VALUES(`faction1`), `faction2` = VALUES(`faction2`), `questChecklistIdx` = VALUES(`questChecklistIdx`), `activePropId` = VALUES(`activePropId`), `worldSocketId` = VALUES(`worldSocketId`), `mode` = VALUES(`mode`);

-- entity_event: 64 row(s)
INSERT INTO `entity_event` (`id`, `eventId`, `phase`) VALUES
  (1100300001, 907, 1),
  (1100300002, 907, 0),
  (1100300003, 907, 2),
  (1100300004, 679, 0),
  (1100300005, 390, 0),
  (1100300006, 390, 1),
  (1100300007, 390, 2),
  (1100300008, 390, 3),
  (1100300009, 390, 4),
  (1100300010, 390, 4),
  (1100300011, 390, 4),
  (1100300012, 390, 5),
  (1100300013, 446, 0),
  (1100300017, 108, 0),
  (1100300018, 781, 23),
  (1100300019, 781, 23),
  (1100300020, 781, 23),
  (1100300021, 781, 23),
  (1100300022, 781, 23),
  (1100300023, 781, 23),
  (1100300024, 781, 23),
  (1100300025, 781, 23),
  (1100300026, 781, 23),
  (1100300027, 781, 23),
  (1100300028, 781, 23),
  (1100300029, 667, 8),
  (1100300030, 667, 16),
  (1100300031, 667, 3),
  (1100300032, 667, 4),
  (1100300033, 667, 5),
  (1100300034, 667, 7),
  (1100300035, 667, 11),
  (1100300036, 667, 13),
  (1100300038, 667, 1),
  (1100300039, 667, 4),
  (1100300041, 667, 9),
  (1100300044, 161, 3),
  (1100300045, 161, 1),
  (1100300046, 161, 2),
  (1100300047, 145, 2),
  (1100300048, 145, 1),
  (1100300049, 148, 0),
  (1100300050, 148, 0),
  (1100300051, 166, 4),
  (1100300055, 594, 5),
  (1100300057, 597, 1),
  (1100300058, 597, 0),
  (1100300059, 157, 0),
  (1100300060, 157, 0),
  (1100300061, 157, 0),
  (1100300062, 157, 0),
  (1100300063, 157, 0),
  (1100300064, 157, 3),
  (1100300065, 157, 4),
  (1100300066, 157, 5),
  (1100300067, 157, 0),
  (1100300068, 157, 11),
  (1100300069, 157, 12),
  (1100300070, 157, 14),
  (1100300071, 157, 19),
  (1100300072, 157, 20),
  (1100300073, 157, 21),
  (1100300074, 157, 22),
  (1100300075, 157, 26)
ON DUPLICATE KEY UPDATE `id` = VALUES(`id`);

-- entity_script: 35 row(s)
INSERT INTO `entity_script` (`id`, `scriptName`) VALUES
  (1100300001, 'HailstoneGatecrasherEntityScript'),
  (1100300031, 'InvulnotronEntityScript'),
  (1100300033, 'GromkaEntityScript'),
  (1100300034, 'IrukiBoldbeardEntityScript'),
  (1100300035, 'SeekNSlaughterEntityScript'),
  (1100300036, 'IceboxMk2EntityScript'),
  (1100300044, 'ForgemasterTrogunEntityScript'),
  (1100300045, 'GrondTheCorpsemakerEntityScript'),
  (1100300046, 'SlavemasterDrokkEntityScript'),
  (1100300047, 'AethrosVeteranEntityScript'),
  (1100300048, 'BladeWindTheInvokerVeteranEntityScript'),
  (1100300049, 'ThunderfootNormalEntityScript'),
  (1100300050, 'StewShamanTuggaNormalEntityScript'),
  (1100300051, 'FlameCrazedDemonEntityScript'),
  (1100300052, 'ExperimentX-89EntityScript'),
  (1100300053, 'KuralakTheDefilerEntityScript'),
  (1100300054, 'KuralakPillarEntityScript'),
  (1100300056, 'LavekaTheDarkHeartedEntityScript'),
  (1100300059, 'OptimizedMemoryProbeED1EntityScript'),
  (1100300060, 'OptimizedMemoryProbeTX-67EntityScript'),
  (1100300061, 'OptimizedMemoryProbeP2ZEntityScript'),
  (1100300062, 'NullSystemDaemonEntityScript'),
  (1100300063, 'BinarySystemDaemonEntityScript'),
  (1100300064, 'FrostBoulderAvalancheFirstEntityScript'),
  (1100300065, 'FrostBoulderAvalancheSecondEntityScript'),
  (1100300066, 'FrostbringerWarlockEntityScript'),
  (1100300067, 'BioEnhancedBroodmotherEntityScript'),
  (1100300068, 'GloomclawEntityScript'),
  (1100300069, 'HyperAcceleratedSkeledroidEntityScript'),
  (1100300070, 'AugmentedHeraldOfAvatusEntityScript'),
  (1100300071, 'WarmongerAgrathaEntityScript'),
  (1100300072, 'WarmongerChunaEntityScript'),
  (1100300073, 'WarmongerTalariiEntityScript'),
  (1100300074, 'GrandWarmongerTargreshEntityScript'),
  (1100300075, 'DatascapeAvatusEntityScript')
ON DUPLICATE KEY UPDATE `id` = VALUES(`id`);

-- entity_stats: 80 row(s)
INSERT INTO `entity_stats` (`id`, `stat`, `value`) VALUES
  (1100300001, 10, 50),
  (1100300005, 0, 1),
  (1100300006, 0, 1),
  (1100300009, 0, 1),
  (1100300009, 10, 32),
  (1100300010, 0, 1),
  (1100300010, 10, 32),
  (1100300011, 0, 1),
  (1100300011, 10, 32),
  (1100300013, 0, 1),
  (1100300015, 0, 1),
  (1100300015, 20, 0),
  (1100300015, 22, 0),
  (1100300016, 0, 1),
  (1100300017, 0, 1),
  (1100300031, 0, 1),
  (1100300031, 10, 10),
  (1100300033, 0, 1),
  (1100300033, 10, 10),
  (1100300034, 0, 1),
  (1100300034, 10, 10),
  (1100300035, 0, 1),
  (1100300035, 10, 10),
  (1100300036, 0, 1),
  (1100300036, 10, 10),
  (1100300044, 10, 25),
  (1100300045, 10, 25),
  (1100300046, 10, 25),
  (1100300047, 0, 1),
  (1100300047, 10, 50),
  (1100300048, 0, 1),
  (1100300048, 10, 50),
  (1100300049, 10, 35),
  (1100300050, 10, 35),
  (1100300051, 10, 40),
  (1100300052, 0, 1),
  (1100300052, 10, 50),
  (1100300053, 0, 1),
  (1100300053, 10, 50),
  (1100300054, 0, 1),
  (1100300054, 10, 50),
  (1100300055, 10, 50),
  (1100300056, 0, 1),
  (1100300056, 10, 50),
  (1100300057, 0, 1),
  (1100300057, 10, 50),
  (1100300059, 0, 15900000),
  (1100300059, 10, 50),
  (1100300060, 0, 15900000),
  (1100300060, 10, 50),
  (1100300061, 0, 15900000),
  (1100300061, 10, 50),
  (1100300062, 0, 14400000),
  (1100300062, 10, 50),
  (1100300063, 0, 14400000),
  (1100300063, 10, 50),
  (1100300064, 0, 14500000),
  (1100300064, 10, 50),
  (1100300065, 0, 14500000),
  (1100300065, 10, 50),
  (1100300066, 0, 15900000),
  (1100300066, 10, 50),
  (1100300067, 0, 18000000),
  (1100300067, 10, 50),
  (1100300068, 0, 21000000),
  (1100300068, 10, 50),
  (1100300069, 0, 21300000),
  (1100300069, 10, 50),
  (1100300070, 0, 9100000),
  (1100300070, 10, 50),
  (1100300071, 0, 12500000),
  (1100300071, 10, 50),
  (1100300072, 0, 12500000),
  (1100300072, 10, 50),
  (1100300073, 0, 12500000),
  (1100300073, 10, 50),
  (1100300074, 0, 14500000),
  (1100300074, 10, 50),
  (1100300075, 0, 72000000),
  (1100300075, 10, 50)
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`);

-- official entity reconciliation: 14 row update(s)
--   Evil from the Ether Captain Weir area: Branch SQL narrows Captain Weir to area 4836; official import has the same coordinate with area 0. WIP/GUESSED pending manual expedition smoke.
UPDATE `entity`
SET `area` = 4836
WHERE `world` = 3404 AND `creature` = 70999 AND ABS(`x` - (-422.1375)) < 0.001 AND ABS(`y` - (-844.95026)) < 0.001 AND ABS(`z` - (122.07739)) < 0.001;
--   Evil from the Ether Gather Ring area: Branch SQL narrows the gather ring used by the current WIP GoToAirlock trigger to area 4836; official import has the same coordinate with area 0.
UPDATE `entity`
SET `area` = 4836
WHERE `world` = 3404 AND `creature` = 71003 AND ABS(`x` - (-396.43555)) < 0.001 AND ABS(`y` - (-840.7188)) < 0.001 AND ABS(`z` - (119.74138)) < 0.001;
--   Evil from the Ether Medbay Door Control area: Branch SQL narrows the medbay door control used by the current WIP RepairDoor cleanup to area 4823; official import has the same coordinate with area 0.
UPDATE `entity`
SET `area` = 4823
WHERE `world` = 3404 AND `creature` = 71283 AND ABS(`x` - (54.22043)) < 0.001 AND ABS(`y` - (-848.04)) < 0.001 AND ABS(`z` - (-159.99998)) < 0.001;
--   Evil from the Ether Spare Parts Crate 1 area: Branch SQL narrows this ScavengeSpareParts crate to area 4823; official import has the same coordinate with area 0. Objective timing remains WIP/GUESSED.
UPDATE `entity`
SET `area` = 4823
WHERE `world` = 3404 AND `creature` = 71322 AND ABS(`x` - (92.72337)) < 0.001 AND ABS(`y` - (-852.9272)) < 0.001 AND ABS(`z` - (-110.27059)) < 0.001;
--   Evil from the Ether Spare Parts Crate 2 area: Branch SQL narrows this ScavengeSpareParts crate to area 4823; official import has the same coordinate with area 0. Objective timing remains WIP/GUESSED.
UPDATE `entity`
SET `area` = 4823
WHERE `world` = 3404 AND `creature` = 71322 AND ABS(`x` - (93.24837)) < 0.001 AND ABS(`y` - (-852.92975)) < 0.001 AND ABS(`z` - (-74.36311)) < 0.001;
--   Evil from the Ether Spare Parts Crate 3 area: Branch SQL narrows this ScavengeSpareParts crate to area 4823; official import has the same coordinate with area 0. Objective timing remains WIP/GUESSED.
UPDATE `entity`
SET `area` = 4823
WHERE `world` = 3404 AND `creature` = 71322 AND ABS(`x` - (65.68544)) < 0.001 AND ABS(`y` - (-852.9225)) < 0.001 AND ABS(`z` - (-140.38359)) < 0.001;
--   Evil from the Ether Repaired Medbay Door Control area: Branch SQL narrows the repaired medbay door control to area 4823; official import has the same coordinate with area 0. Repair-door cleanup remains WIP/GUESSED.
UPDATE `entity`
SET `area` = 4823
WHERE `world` = 3404 AND `creature` = 71323 AND ABS(`x` - (54.22043)) < 0.001 AND ABS(`y` - (-848.0354)) < 0.001 AND ABS(`z` - (-159.99869)) < 0.001;
--   Evil from the Ether Crew Log 1: Branch and official SQL agree on this row; it is included so verification can assert all seven crew logs.
UPDATE `entity`
SET `questChecklistIdx` = 0
WHERE `world` = 3404 AND `creature` = 71234 AND ABS(`x` - (31.47145)) < 0.001 AND ABS(`y` - (-849.1181)) < 0.001 AND ABS(`z` - (-152.4904)) < 0.001;
--   Evil from the Ether Crew Log 2: Branch checklist index drives CrewLog2; official DB imports this coordinate as index 3.
UPDATE `entity`
SET `questChecklistIdx` = 1
WHERE `world` = 3404 AND `creature` = 71234 AND ABS(`x` - (-65.33878)) < 0.001 AND ABS(`y` - (-844.1473)) < 0.001 AND ABS(`z` - (-150.08818)) < 0.001;
--   Evil from the Ether Crew Log 3: Branch checklist index drives CrewLog3; official DB imports this coordinate as index 1.
UPDATE `entity`
SET `questChecklistIdx` = 2
WHERE `world` = 3404 AND `creature` = 71234 AND ABS(`x` - (68.89046)) < 0.001 AND ABS(`y` - (-849.1848)) < 0.001 AND ABS(`z` - (-182.18137)) < 0.001;
--   Evil from the Ether Crew Log 4: Branch checklist index drives CrewLog4; official DB imports this coordinate as index 6.
UPDATE `entity`
SET `questChecklistIdx` = 3
WHERE `world` = 3404 AND `creature` = 71234 AND ABS(`x` - (44.647617)) < 0.001 AND ABS(`y` - (-840.1598)) < 0.001 AND ABS(`z` - (184.907)) < 0.001;
--   Evil from the Ether Crew Log 5: Branch checklist index drives CrewLog5; official DB imports this coordinate as index 5.
UPDATE `entity`
SET `questChecklistIdx` = 4
WHERE `world` = 3404 AND `creature` = 71234 AND ABS(`x` - (-32.94068)) < 0.001 AND ABS(`y` - (-843.9746)) < 0.001 AND ABS(`z` - (143.43298)) < 0.001;
--   Evil from the Ether Crew Log 6: Branch checklist index drives CrewLog6; official DB imports this coordinate as index 2.
UPDATE `entity`
SET `questChecklistIdx` = 5
WHERE `world` = 3404 AND `creature` = 71234 AND ABS(`x` - (18.839134)) < 0.001 AND ABS(`y` - (-840.56036)) < 0.001 AND ABS(`z` - (-113.37005)) < 0.001;
--   Evil from the Ether Crew Log 7: Branch checklist index drives CrewLog7; official DB imports this coordinate as index 4.
UPDATE `entity`
SET `questChecklistIdx` = 6
WHERE `world` = 3404 AND `creature` = 71234 AND ABS(`x` - (-17.037079)) < 0.001 AND ABS(`y` - (-843.8909)) < 0.001 AND ABS(`z` - (46.10919)) < 0.001;

-- Sources:
--   Map/Instances/Dungeons/Coldblood Citadel.sql
--   Map/Instances/Dungeons/Protogames Academy.sql
--   Map/Instances/Dungeons/Ruins of Kel Voreth.sql
--   Map/Instances/Dungeons/Sanctuary of the Swordmaiden.sql
--   Map/Instances/Dungeons/Skullcano.sql
--   Map/Instances/Dungeons/Stormtalon's Lair.sql
--   Map/Instances/Dungeons/Ultimate Protogames.sql
--   Map/Instances/Event instances/Protostar SuperMall-In-The-Sky.sql
--   Map/Instances/Event instances/Shade's Eve.sql
--   Map/Instances/Expeditions/Evil from the Ether.sql
--   Map/Instances/Expeditions/Fragment Zero.sql
--   Map/Instances/Expeditions/Gauntlet.sql
--   Map/Instances/Expeditions/Infestation.sql
--   Map/Instances/Expeditions/Outpost M13.sql
--   Map/Instances/Expeditions/Space Madness.sql
--   Map/Instances/Raids/Datascape.sql
--   Map/Instances/Raids/Genetic Archives.sql
--   Map/Instances/Raids/Redmoon Terror.sql
--   I:/GIT/NexusForever.WorldDatabase/Instance/Expedition/Evil from the Ether.sql

COMMIT;
